<?php

$dictionary['EC_Customer'] = array(
    'table' => 'ec_customer',
    'audited' => true,
    'inline_edit' => true,
    'duplicate_merge' => true,
    'fields' => array(
		'phone' =>
		array(
			'required' => true,
			'name' => 'phone',
			'vname' => 'LBL_PHONE',
			'type' => 'phone',
			'massupdate' => 0,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '',
			'audited' => 1,
			'reportable' => 0,
			'len' => '25',
			'dbType' => 'varchar',
		),
		'email' =>
		array(
			'required' => '0',
			'name' => 'email',
			'vname' => 'LBL_EMAIL',
			'type' => 'varchar',
			'massupdate' => 0,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '',
			'audited' => 1,
			'reportable' => 0,
			'len' => '255',
		),
		'birthday' =>
		array(
			'required' => false,
			'name' => 'birthday',
			'vname' => 'LBL_BIRTHDAY',
			'type' => 'date',
			'massupdate' => 0,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => ' ',
			'audited' => 1,
			'reportable' => 0,
		),
		'gender' =>
		array(
			'required' => false,
			'name' => 'gender',
			'vname' => 'LBL_GENDER',
			'type' => 'enum',
			'massupdate' => 0,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => ' ',
			'audited' => 1,
			'reportable' => 0,
			'len' => '10',
			'options' => 'gender_list',
			'default' => '0',
		),
		'type' =>
		array(
			'required' => false,
			'name' => 'type',
			'vname' => 'LBL_CUSTOMER_TYPE',
			'type' => 'enum',
			'massupdate' => '1',
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => ' ',
			'audited' => 1,
			'reportable' => 0,
			'len' => 100,
			'options' => 'customer_type_list',
			'studio' => 'visible',
			'dependency' => false,
		),
		'source' =>
		array(
			'required' => '0',
			'name' => 'source',
			'vname' => 'LBL_SOURCE',
			'type' => 'varchar',
			'massupdate' => 0,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '',
			'audited' => 1,
			'reportable' => 0,
			'len' => '50',
		),
		'info_data' =>
		array(
			'required' => false,
			'name' => 'info_data',
			'vname' => 'LBL_INFO_DATA',
			'type' => 'longtext',
			'massupdate' => 0,
			'comments' => 'danh sach booking cua mot hanh khach',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '',
			'audited' => 1,
			'reportable' => 0,
			'studio' => 'visible',
		),
	),
	'indices' => array(
		array('name' => 'idx_contact_phone', 'type' => 'index', 'fields' => array('phone')),
	 ),
    'relationships' => array (
),
    'optimistic_locking' => true,
    'unified_search' => true,
);
if (!class_exists('VardefManager')) {
        require_once('include/SugarObjects/VardefManager.php');
}
VardefManager::createVardef('EC_Customer', 'EC_Customer', array('basic','assignable','security_groups'));
