<?php
if (!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');
function generate_xls($content)
{
    global $app_list_strings;

    $xls = '<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>
<meta http-equiv=Content-Type content="text/html; charset=windows-1252">
<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 12">
<link rel=File-List href="PhieuChi_files/filelist.xml">
<style id="PhieuChi_4238_Styles">
<!--table
	{mso-displayed-decimal-separator:"\.";
	mso-displayed-thousand-separator:"\,";}
.xl634238
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:11.0pt;
	font-weight:700;
	font-style:normal;
	text-decoration:none;
	font-family:Tahoma, sans-serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl644238
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:Tahoma, sans-serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:general;
	vertical-align:middle;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl654238
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:Tahoma, sans-serif;
	mso-font-charset:0;
	mso-number-format:"dd\\-mm\\-yyyy";
	text-align:center;
	vertical-align:middle;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl664238
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:Tahoma, sans-serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl674238
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:Tahoma, sans-serif;
	mso-font-charset:0;
	mso-number-format:"_\(* \#\,\#\#0_\)\;_\(* \\\(\#\,\#\#0\\\)\;_\(* \0022-\0022??_\)\;_\(\@_\)";
	text-align:right;
	vertical-align:middle;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl684238
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:Tahoma, sans-serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:left;
	vertical-align:middle;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl694238
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:Tahoma, sans-serif;
	mso-font-charset:0;
	mso-number-format:"dd\\-mm\\-yyyy\\ hh\:mm";
	text-align:center;
	vertical-align:middle;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
-->
</style>
</head>

<body>
<!--[if !excel]>&nbsp;&nbsp;<![endif]-->
<!--The following information was generated by Microsoft Office Excel"s Publish
as Web Page wizard.-->
<!--If the same item is republished from Excel, all information between the DIV
tags will be replaced.-->
<!----------------------------->
<!--START OF OUTPUT FROM EXCEL PUBLISH AS WEB PAGE WIZARD -->
<!----------------------------->

<div id="PhieuChi_4238" align=center x:publishsource="Excel">

<table border=0 cellpadding=0 cellspacing=0 width=1208 class=xl644238
 style="border-collapse:collapse;table-layout:fixed;width:907pt">
 <col class=xl644238 width=118 style="mso-width-source:userset;mso-width-alt:
 4315;width:89pt">
 <col class=xl644238 width=147 style="mso-width-source:userset;mso-width-alt:
 5376;width:110pt">
 <col class=xl644238 width=100 style="mso-width-source:userset;mso-width-alt:
 3657;width:75pt">
 <col class=xl644238 width=105 style="mso-width-source:userset;mso-width-alt:
 3840;width:79pt">
 <col class=xl644238 width=177 style="mso-width-source:userset;mso-width-alt:
 6473;width:133pt">
 <col class=xl644238 width=291 style="mso-width-source:userset;mso-width-alt:
 10642;width:218pt">
 <col class=xl644238 width=128 style="mso-width-source:userset;mso-width-alt:
 4681;width:96pt">
 <col class=xl644238 width=142 style="mso-width-source:userset;mso-width-alt:
 5193;width:107pt">
 <tr height=19 style="height:14.25pt">
  <td height=19 class=xl634238 width=118 style="height:14.25pt;width:89pt">Ngày
  ch&#7913;ng t&#7915;</td>
  <td class=xl634238 width=147 style="width:110pt">S&#7889; ch&#7913;ng
  t&#7915;</td>
  <td class=xl634238 width=100 style="width:75pt">Tình tr&#7841;ng</td>
  <td class=xl634238 width=105 style="width:79pt">S&#7889; ti&#7873;n</td>
  <td class=xl634238 width=177 style="width:133pt">Ng&#432;&#7901;i nh&#7853;n</td>
  <td class=xl634238 width=291 style="width:218pt">N&#7897;i dung chi</td>
  <td class=xl634238 width=128 style="width:96pt">Hình th&#7913;c</td>
  <td class=xl634238 width=142 style="width:107pt">Ngày t&#7841;o</td>
 </tr>';

    $content_arr = explode("\"\r\n", $content);
    for ($i = 1; $i < count($content_arr) - 1; $i++) {
        $dataRow = explode("\",\"", $content_arr[$i]);
        $ngaychungtu = date('m/d/Y', strtotime($dataRow[22]));
        $sochungtu = $dataRow[1];
        $tinhtrang = $app_list_strings['payment_voucher_status_list'][$dataRow[26]];
        $sotien = $dataRow[12];
        $nguoinhan = $dataRow[10];
        $noidung = $dataRow[6];
        $hinhthuc = $app_list_strings['receipt_type_list'][$dataRow[23]];
        $ngaytao = date('m/d/Y g:i:s A', strtotime($dataRow[2]));

        $xls .= '<tr height=19 style="height:14.25pt">
  <td height=19 class=xl654238 style="height:14.25pt">'.$ngaychungtu.'</td>
  <td class=xl664238>'.$sochungtu.'</td>
  <td class=xl644238>'.$tinhtrang.'</td>
  <td class=xl674238>'.$sotien.'</td>
  <td class=xl684238>'.$nguoinhan.'</td>
  <td class=xl644238>'.$noidung.'</td>
  <td class=xl684238>'.$hinhthuc.'</td>
  <td class=xl694238>'.$ngaytao.'</td>
 </tr>';

    }

    $xls .= '<![if supportMisalignedColumns]>
 <tr height=0 style="display:none">
  <td width=118 style="width:89pt"></td>
  <td width=147 style="width:110pt"></td>
  <td width=100 style="width:75pt"></td>
  <td width=105 style="width:79pt"></td>
  <td width=177 style="width:133pt"></td>
  <td width=291 style="width:218pt"></td>
  <td width=128 style="width:96pt"></td>
  <td width=142 style="width:107pt"></td>
 </tr>
 <![endif]>
</table>

</div>


<!----------------------------->
<!--END OF OUTPUT FROM EXCEL PUBLISH AS WEB PAGE WIZARD-->
<!----------------------------->
</body>

</html>';

    return $xls;
}

?>
