<?php

$dictionary['EC_Payment_Voucher'] = array(
    'table' => 'ec_payment_voucher',
    'audited' => true,
    'inline_edit' => true,
    'duplicate_merge' => true,
    'fields' => array(
        'pv_notes' =>
        array(
            'required' => false,
            'name' => 'pv_notes',
            'vname' => 'LBL_PV_NOTES',
            'type' => 'text',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 1,
            'reportable' => 0,
            'studio' => 'visible',
        ),
        'receipent_name' =>
        array(
            'required' => '1',
            'name' => 'receipent_name',
            'vname' => 'LBL_RECEIPENT_NAME',
            'type' => 'varchar',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 1,
            'reportable' => 0,
            'len' => '255',
        ),
        'receipent_phone' =>
        array(
            'required' => false,
            'name' => 'receipent_phone',
            'vname' => 'LBL_RECEIPENT_PHONE',
            'type' => 'varchar',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 1,
            'reportable' => 0,
            'len' => '25',
        ),
        'receipent_phone_fax' =>
        array(
            'required' => false,
            'name' => 'receipent_phone_fax',
            'vname' => 'LBL_RECEIPENT_PHONE_FAX',
            'type' => 'varchar',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 1,
            'reportable' => 0,
            'len' => '25',
        ),
        'receipent_phone_mobile' =>
        array(
            'required' => false,
            'name' => 'receipent_phone_mobile',
            'vname' => 'LBL_RECEIPENT_PHONE_MOBILE',
            'type' => 'varchar',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 1,
            'reportable' => 0,
            'len' => '25',
        ),
        'receipent_email' =>
        array(
            'required' => '0',
            'name' => 'receipent_email',
            'vname' => 'LBL_RECEIPENT_EMAIL',
            'type' => 'varchar',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 1,
            'reportable' => 0,
            'len' => '100',
        ),
        'amount' =>
        array(
            'required' => true,
            'name' => 'amount',
            'vname' => 'LBL_AMOUNT',
            'type' => 'currency',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => ' ',
            'audited' => 1,
            'reportable' => 0,
            'len' => 26,
        ),
        'amount_type' =>
        array(
            'required' => false,
            'name' => 'amount_type',
            'vname' => 'LBL_AMOUNT_TYPE',
            'type' => 'enum',
            'massupdate' => 0,
            'default' => 'vnd',
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 1,
            'reportable' => 0,
            'len' => 100,
            'options' => 'loaitien_list',
            'studio' => 'visible',
            'dependency' => false,
        ),
        'pv_number' =>
        array(
            'required' => false,
            'name' => 'pv_number',
            'vname' => 'LBL_PV_NUMBER',
            'type' => 'varchar',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 1,
            'reportable' => 0,
            'len' => '100',
        ),
        'receipent_address' =>
        array(
            'required' => false,
            'name' => 'receipent_address',
            'vname' => 'LBL_RECEIPENT_ADDRESS',
            'type' => 'text',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 1,
            'reportable' => 0,
            'studio' => 'visible',
        ),
        'ec_payment_types_id_c' =>
        array(
            'required' => false,
            'name' => 'ec_payment_types_id_c',
            'vname' => '',
            'type' => 'id',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => 0,
            'audited' => 1,
            'reportable' => 0,
            'len' => 36,
        ),
        'payment_type' =>
        array(
            'required' => true,
            'source' => 'non-db',
            'name' => 'payment_type',
            'vname' => 'LBL_PAYMENT_TYPE',
            'type' => 'relate',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 1,
            'reportable' => 0,
            'len' => '255',
            'id_name' => 'ec_payment_types_id_c',
            'ext2' => 'EC_Payment_Types',
            'module' => 'EC_Payment_Types',
            'rname' => 'name',
            'quicksearch' => 'enabled',
            'studio' => 'visible',
        ),
        'supplier_id' =>
        array(
            'required' => false,
            'name' => 'supplier_id',
            'vname' => '',
            'type' => 'id',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => 0,
            'audited' => 1,
            'reportable' => 0,
            'len' => 36,
        ),
        'supplier' =>
        array(
            'required' => false,
            'source' => 'non-db',
            'name' => 'supplier',
            'vname' => 'LBL_SUPPLIER',
            'type' => 'relate',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 1,
            'reportable' => 0,
            'len' => '255',
            'id_name' => 'supplier_id',
            'ext2' => 'Accounts',
            'module' => 'Accounts',
            'rname' => 'name',
            'quicksearch' => 'enabled',
            'studio' => 'visible',
        ),
        'account_id' =>
        array(
            'required' => false,
            'name' => 'account_id',
            'vname' => '',
            'type' => 'id',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => 0,
            'audited' => 1,
            'reportable' => 0,
            'len' => 36,
        ),
        'account_name' =>
        array(
            'required' => 0,
            'source' => 'non-db',
            'name' => 'account_name',
            'vname' => 'LBL_ACCOUNT_NAME',
            'type' => 'relate',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 1,
            'reportable' => 0,
            'len' => '255',
            'id_name' => 'account_id',
            'ext2' => 'Accounts',
            'module' => 'Accounts',
            'rname' => 'name',
            'quicksearch' => 'enabled',
            'studio' => 'visible',
        ),
        'ngaychungtu' =>
        array(
            'required' => '1',
            'name' => 'ngaychungtu',
            'vname' => 'LBL_NGAYCHUNGTU',
            'type' => 'date',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => ' ',
            'audited' => 1,
            'reportable' => 0,
            'display_default' => 'now',
            // 'enable_range_search' => true,
            // 'options' => 'date_range_search_dom',
        ),
        'hinhthucchi' =>
        array(
            'required' => false,
            'name' => 'hinhthucchi',
            'vname' => 'LBL_HINHTHUCCHI',
            'type' => 'enum',
            'massupdate' => 0,
            'default' => 'cash',
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 1,
            'reportable' => 0,
            'len' => 100,
            'options' => 'receipt_type_list',
            'studio' => 'visible',
            'dependency' => false,
        ),
        'tknganhang_id' =>
        array(
            'required' => false,
            'name' => 'tknganhang_id',
            'vname' => 'LBL_TKNGANHANG',
            'type' => 'id',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => 0,
            'audited' => 1,
            'reportable' => 0,
            'len' => 36,
        ),
        'tknganhang' =>
        array(
            'required' => false,
            'source' => 'non-db',
            'name' => 'tknganhang',
            'vname' => 'LBL_TKNGANHANG',
            'type' => 'relate',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 1,
            'reportable' => 0,
            'len' => '255',
            'id_name' => 'tknganhang_id',
            'ext2' => 'EC_Bank_Account',
            'module' => 'EC_Bank_Account',
            'rname' => 'name',
            'quicksearch' => 'enabled',
            'studio' => 'visible',
        ),
        'tk_ketoan' =>
        array(
            'required' => false,
            'name' => 'tk_ketoan',
            'vname' => 'LBL_TK_KETOAN',
            'type' => 'varchar',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 1,
            'reportable' => 0,
            'len' => '10',
        ),
        'pv_status' =>
        array(
            'required' => false,
            'name' => 'pv_status',
            'vname' => 'LBL_PV_STATUS',
            'type' => 'enum',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 1,
            'reportable' => 0,
            'len' => 100,
            'options' => 'payment_voucher_status_list',
            'studio' => 'visible',
            'dependency' => false,
            'default' => '0',
        ),
        'ngayhachtoan' =>
        array(
            'required' => '1',
            'name' => 'ngayhachtoan',
            'vname' => 'LBL_NGAYHACHTOAN',
            'type' => 'datetimecombo',
            'dbType' => 'datetime',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '',
            'audited' => 1,
            'reportable' => 0,
        ),
        'is_margin' =>
        array(
            'required' => false,
            'name' => 'is_margin',
            'vname' => 'LBL_IS_MARGIN',
            'type' => 'bool',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '',
            'audited' => 1,
            'reportable' => 0,
            'len' => '1',
            'default' => '0',
        ),
        'hoanve_id' =>
        array(
            'required' => false,
            'name' => 'hoanve_id',
            'vname' => '',
            'type' => 'id',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => 0,
            'audited' => 1,
            'reportable' => 0,
            'len' => 36,
        ),
        'hoanve' =>
        array(
            'required' => false,
            'source' => 'non-db',
            'name' => 'hoanve',
            'vname' => 'LBL_HOANVE',
            'type' => 'relate',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 1,
            'reportable' => 0,
            'len' => '255',
            'id_name' => 'hoanve_id',
            'ext2' => 'EC_HoanVe',
            'module' => 'EC_HoanVe',
            'rname' => 'name',
            'quicksearch' => 'enabled',
            'studio' => 'visible',
        ),

        // Loại chi "Hoàn tiền khác" kèm theo PT
        'phieuthu_id' =>
        array(
            'required' => false,
            'name' => 'phieuthu_id',
            'vname' => '',
            'type' => 'id',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => 0,
            'audited' => 1,
            'reportable' => 0,
            'len' => 36,
        ),
        'phieuthu' =>
        array(
            'required' => false,
            'source' => 'non-db',
            'name' => 'phieuthu',
            'vname' => 'LBL_PHIEUTHU',
            'type' => 'relate',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 1,
            'reportable' => 0,
            'len' => '255',
            'id_name' => 'phieuthu_id',
            'ext2' => 'EC_Receipt_Voucher',
            'module' => 'EC_Receipt_Voucher',
            'rname' => 'name',
            'quicksearch' => 'enabled',
            'studio' => 'visible',
        ),

        'location' =>
        array(
            'required' => false,
            'name' => 'location',
            'vname' => 'LBL_LOCATION',
            'type' => 'enum',
            'massupdate' => 0,
            'default' => '',
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 1,
            'reportable' => 0,
            'len' => 100,
            'options' => 'location_list',
            'studio' => 'visible',
            'dependency' => false,
        ),
        'com_location_id' =>
        array(
            'required' => false,
            'name' => 'com_location_id',
            'vname' => '',
            'type' => 'id',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => 0,
            'audited' => 1,
            'reportable' => 0,
            'len' => 36,
        ),
        'com_location' =>
        array(
            'required' => false,
            'source' => 'non-db',
            'name' => 'com_location',
            'vname' => 'LBL_COM_LOCATION',
            'type' => 'relate',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 1,
            'reportable' => 0,
            'len' => '255',
            'id_name' => 'com_location_id',
            'ext2' => 'EC_Location',
            'module' => 'EC_Location',
            'rname' => 'name',
            'quicksearch' => 'enabled',
            'studio' => 'visible',
        ),
        'booking_id' =>
        array(
            'required' => false,
            'name' => 'booking_id',
            'vname' => '',
            'type' => 'id',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => 0,
            'audited' => 1,
            'reportable' => 0,
            'len' => 36,
        ),
        'booking' =>
        array(
            'required' => false,
            'source' => 'non-db',
            'name' => 'booking',
            'vname' => 'LBL_BOOKING',
            'type' => 'relate',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 1,
            'reportable' => 0,
            'len' => '255',
            'id_name' => 'booking_id',
            'ext2' => 'EC_Flight_Bookings',
            'module' => 'EC_Flight_Bookings',
            'rname' => 'name',
            'quicksearch' => 'enabled',
            'studio' => 'visible',
        ),
        'employee_id' =>
        array(
            'required' => 0,
            'name' => 'employee_id',
            'vname' => '',
            'type' => 'id',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => 0,
            'audited' => 1,
            'reportable' => 0,
            'len' => 36,
        ),
        'employee_name' =>
        array(
            'required' => 0,
            'source' => 'non-db',
            'name' => 'employee_name',
            'vname' => 'LBL_EMPLOYEE_NAME',
            'type' => 'relate',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 1,
            'reportable' => 0,
            'len' => '255',
            'id_name' => 'employee_id',
            'ext2' => 'Users',
            'module' => 'Users',
            'rname' => 'name',
            'quicksearch' => 'enabled',
            'studio' => 'visible',
        ),
    ),
    'indices' =>
    array(
        0 => array('name' => 'idx_pv_name', 'type' => 'index', 'fields' => array('name')),
        1 => array('name' => 'idx_pv_del', 'type' => 'index', 'fields' => array('deleted')),
        2 => array('name' => 'idx_pv_supplier', 'type' => 'index', 'fields' => array('supplier_id')),
        3 => array('name' => 'idx_pv_debt', 'type' => 'index', 'fields' => array('debt_id')),
        4 => array('name' => 'idx_pv_paytype', 'type' => 'index', 'fields' => array('ec_payment_types_id_c')),
        5 => array('name' => 'idx_pv_tknganhang', 'type' => 'index', 'fields' => array('tknganhang_id')),
        6 => array('name' => 'idx_pv_hv', 'type' => 'index', 'fields' => array('hoanve_id')),
        7 => array('name' => 'idx_pv_pt', 'type' => 'index', 'fields' => array('phieuthu_id')),
        8 => array('name' => 'idx_pv_location', 'type' => 'index', 'fields' => array('location')),
        0 => array('name' => 'idx_pv_comlocation', 'type' => 'index', 'fields' => array('com_location_id')),
    ),
    'relationships' => array (),
    'optimistic_locking' => true,
    'unified_search' => true,
);
if (!class_exists('VardefManager')) {
        require_once('include/SugarObjects/VardefManager.php');
}
VardefManager::createVardef('EC_Payment_Voucher', 'EC_Payment_Voucher', array('basic','assignable','security_groups'));
