<?php


// THIS CONTENT IS GENERATED BY MBPackage.php
$manifest = array(
  0 =>
  array(
    'acceptable_sugar_versions' =>
    array(
      0 => '',
    ),
  ),
  1 =>
  array(
    'acceptable_sugar_flavors' =>
    array(
      0 => 'CE',
      1 => 'PRO',
      2 => 'ENT',
    ),
  ),
  'readme' => '',
  'key' => 'EC',
  'author' => 'DucPham',
  'description' => 'Save message between OA and Zalo user',
  'icon' => '',
  'is_uninstallable' => true,
  'name' => 'Zalo_Messages',
  'published_date' => '2025-03-24 02:04:09',
  'type' => 'module',
  'version' => 1742781849,
  'remove_tables' => 'prompt',
);
