<?php

$dictionary['EC_WorkingOverTimeDetails'] = array(
    'table' => 'ec_workingovertimedetails',
    'audited' => true,
    'inline_edit' => true,
    'duplicate_merge' => true,
    'fields' =>
  array(
    'register_date' =>
    array(
      'required' => false,
      'name' => 'register_date',
      'vname' => 'LBL_REGISTER_DATE',
      'type' => 'date',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 1,
      'reportable' => 0,
    ),
    'ec_workingovertimes_id_c' =>
    array(
      'required' => false,
      'name' => 'ec_workingovertimes_id_c',
      'vname' => '',
      'type' => 'id',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => 0,
      'audited' => 0,
      'reportable' => 0,
      'len' => 36,
    ),
    'overtime_name' =>
    array(
      'required' => false,
      'source' => 'non-db',
      'name' => 'overtime_name',
      'vname' => 'LBL_OVERTIME_NAME',
      'type' => 'relate',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 1,
      'reportable' => 0,
      'len' => '255',
      'id_name' => 'ec_workingovertimes_id_c',
      'ext2' => 'EC_WorkingOverTimes',
      'module' => 'EC_WorkingOverTimes',
      'rname' => 'name',
      'quicksearch' => 'enabled',
      'studio' => 'visible',
    ),
    'from_time' =>
    array(
      'required' => false,
      'name' => 'from_time',
      'vname' => 'LBL_FROM_TIME',
      'type' => 'datetime',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '',
      'audited' => 1,
      'reportable' => 0,
    ),
    'to_time' =>
    array(
      'required' => false,
      'name' => 'to_time',
      'vname' => 'LBL_TO_TIME',
      'type' => 'datetime',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '',
      'audited' => 1,
      'reportable' => 0,
    ),
    'multiplier' =>
    array(
      'required' => false,
      'name' => 'multiplier',
      'vname' => 'LBL_MULTIPLIER',
      'type' => 'int',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => '11',
      'disable_num_format' => 1,
    ),
    'working_hour' =>
    array(
      'required' => false,
      'name' => 'working_hour',
      'vname' => 'LBL_WORKING_HOUR',
      'type' => 'int',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => '11',
      'disable_num_format' => 1,
    ),
    'status' =>
    array(
      'required' => false,
      'name' => 'status',
      'vname' => 'LBL_STATUS',
      'type' => 'enum',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 1,
      'reportable' => 0,
      'len' => 100,
      'options' => 'overtime_status_list',
      'studio' => 'visible',
      'dependency' => false,
      'default' => '0',
    ),
  ),
    'relationships' => array (),
    'optimistic_locking' => true,
    'unified_search' => true,
);
if (!class_exists('VardefManager')) {
        require_once('include/SugarObjects/VardefManager.php');
}
VardefManager::createVardef('EC_WorkingOverTimeDetails', 'EC_WorkingOverTimeDetails', array('basic','assignable','security_groups'));
