r<?php
function generateXLSTemplate($data, $from_date, $to_date){
	$xls = "<html xmlns:o=\"urn:schemas-microsoft-com:office:office\"
	xmlns:x=\"urn:schemas-microsoft-com:office:excel\"
	xmlns=\"http://www.w3.org/TR/REC-html40\">

	<head>
	<meta http-equiv=Content-Type content=\"text/html; charset=windows-1252\">
	<meta name=ProgId content=Excel.Sheet>
	<meta name=Generator content=\"Microsoft Excel 12\">
	<link rel=File-List href=\"doanhthubanve_files/filelist.xml\">
	<style id=\"doanhthubanve_24108_Styles\">
	<!--table
		{mso-displayed-decimal-separator:\"\.\";
		mso-displayed-thousand-separator:\"\,\";}
	.xl6324108
		{padding-top:1px;
		padding-right:1px;
		padding-left:1px;
		mso-ignore:padding;
		color:black;
		font-size:10.0pt;
		font-weight:400;
		font-style:normal;
		text-decoration:none;
		font-family:Arial, sans-serif;
		mso-font-charset:0;
		mso-number-format:General;
		text-align:general;
		vertical-align:middle;
		mso-background-source:auto;
		mso-pattern:auto;
		white-space:nowrap;}
	.xl6424108
		{padding-top:1px;
		padding-right:1px;
		padding-left:1px;
		mso-ignore:padding;
		color:black;
		font-size:10.0pt;
		font-weight:400;
		font-style:normal;
		text-decoration:none;
		font-family:Arial, sans-serif;
		mso-font-charset:0;
		mso-number-format:General;
		text-align:center;
		vertical-align:middle;
		mso-background-source:auto;
		mso-pattern:auto;
		white-space:nowrap;}
	.xl6524108
		{padding-top:1px;
		padding-right:1px;
		padding-left:1px;
		mso-ignore:padding;
		color:black;
		font-size:10.0pt;
		font-weight:700;
		font-style:normal;
		text-decoration:none;
		font-family:Arial, sans-serif;
		mso-font-charset:0;
		mso-number-format:General;
		text-align:center;
		vertical-align:middle;
		border:.5pt solid windowtext;
		mso-background-source:auto;
		mso-pattern:auto;
		white-space:nowrap;}
	.xl6624108
		{padding-top:1px;
		padding-right:1px;
		padding-left:1px;
		mso-ignore:padding;
		color:black;
		font-size:10.0pt;
		font-weight:400;
		font-style:normal;
		text-decoration:none;
		font-family:Arial, sans-serif;
		mso-font-charset:0;
		mso-number-format:General;
		text-align:center;
		vertical-align:middle;
		border:.5pt solid windowtext;
		mso-background-source:auto;
		mso-pattern:auto;
		white-space:nowrap;}
	.xl6724108
		{padding-top:1px;
		padding-right:1px;
		padding-left:1px;
		mso-ignore:padding;
		color:black;
		font-size:10.0pt;
		font-weight:400;
		font-style:normal;
		text-decoration:none;
		font-family:Arial, sans-serif;
		mso-font-charset:0;
		mso-number-format:\"\@\";
		text-align:center;
		vertical-align:middle;
		border:.5pt solid windowtext;
		mso-background-source:auto;
		mso-pattern:auto;
		white-space:nowrap;}
	.xl6824108
		{padding-top:1px;
		padding-right:1px;
		padding-left:1px;
		mso-ignore:padding;
		color:black;
		font-size:10.0pt;
		font-weight:400;
		font-style:normal;
		text-decoration:none;
		font-family:Arial, sans-serif;
		mso-font-charset:0;
		mso-number-format:\"\#\,\#\#0\";
		text-align:right;
		vertical-align:middle;
		border:.5pt solid windowtext;
		mso-background-source:auto;
		mso-pattern:auto;
		white-space:nowrap;}
	.xl6924108
		{padding-top:1px;
		padding-right:1px;
		padding-left:1px;
		mso-ignore:padding;
		color:black;
		font-size:10.0pt;
		font-weight:400;
		font-style:normal;
		text-decoration:none;
		font-family:Arial, sans-serif;
		mso-font-charset:0;
		mso-number-format:General;
		text-align:general;
		vertical-align:middle;
		border:.5pt solid windowtext;
		mso-background-source:auto;
		mso-pattern:auto;
		white-space:nowrap;}
	.xl7024108
		{padding-top:1px;
		padding-right:1px;
		padding-left:1px;
		mso-ignore:padding;
		color:black;
		font-size:10.0pt;
		font-weight:700;
		font-style:normal;
		text-decoration:none;
		font-family:Arial, sans-serif;
		mso-font-charset:0;
		mso-number-format:\"\#\,\#\#0\";
		text-align:general;
		vertical-align:middle;
		border:.5pt solid windowtext;
		mso-background-source:auto;
		mso-pattern:auto;
		white-space:nowrap;}
	.xl7124108
		{padding-top:1px;
		padding-right:1px;
		padding-left:1px;
		mso-ignore:padding;
		color:black;
		font-size:13.0pt;
		font-weight:700;
		font-style:normal;
		text-decoration:none;
		font-family:Arial, sans-serif;
		mso-font-charset:0;
		mso-number-format:General;
		text-align:center;
		vertical-align:middle;
		mso-background-source:auto;
		mso-pattern:auto;
		white-space:nowrap;}
	-->
	</style>
	</head>

	<body>
	<!--[if !excel]>&nbsp;&nbsp;<![endif]-->
	<!--The following information was generated by Microsoft Office Excel's Publish
	as Web Page wizard.-->
	<!--If the same item is republished from Excel, all information between the DIV
	tags will be replaced.-->
	<!----------------------------->
	<!--START OF OUTPUT FROM EXCEL PUBLISH AS WEB PAGE WIZARD -->
	<!----------------------------->

	<div id=\"doanhthubanve_24108\" align=center x:publishsource=\"Excel\">

	<table border=0 cellpadding=0 cellspacing=0 width=868 class=xl6324108
	style='border-collapse:collapse;table-layout:fixed;width:652pt'>
	<col class=xl6324108 width=35 style='mso-width-source:userset;mso-width-alt:
	1280;width:26pt'>
	<col class=xl6324108 width=90 style='mso-width-source:userset;mso-width-alt:
	3291;width:68pt'>
	<col class=xl6324108 width=45 style='mso-width-source:userset;mso-width-alt:
	1645;width:34pt'>
	<col class=xl6324108 width=93 style='mso-width-source:userset;mso-width-alt:
	3401;width:70pt'>
	<col class=xl6324108 width=93 style='mso-width-source:userset;mso-width-alt:
	3401;width:70pt'>
	<col class=xl6324108 width=95 style='mso-width-source:userset;mso-width-alt:
	3474;width:71pt'>
	<col class=xl6324108 width=86 style='mso-width-source:userset;mso-width-alt:
	3145;width:65pt'>
	<col class=xl6324108 width=100 style='mso-width-source:userset;mso-width-alt:
	3657;width:75pt'>
	<col class=xl6324108 width=91 style='mso-width-source:userset;mso-width-alt:
	3328;width:68pt'>
	<col class=xl6324108 width=91 style='mso-width-source:userset;mso-width-alt:
	3328;width:68pt'>
	<col class=xl6324108 width=89 style='mso-width-source:userset;mso-width-alt:
	3254;width:67pt'>
	<col class=xl6324108 width=91 style='mso-width-source:userset;mso-width-alt:
	3328;width:68pt'>
	<col class=xl6324108 width=87 style='mso-width-source:userset;mso-width-alt:
	3181;width:65pt'>
	<col class=xl6324108 width=57 style='mso-width-source:userset;mso-width-alt:
	2084;width:43pt'>
	<col class=xl6324108 width=57 style='mso-width-source:userset;mso-width-alt:
	2084;width:43pt'>
	<col class=xl6324108 width=57 style='mso-width-source:userset;mso-width-alt:
	2084;width:43pt'>
	<col class=xl6324108 width=57 style='mso-width-source:userset;mso-width-alt:
	2084;width:43pt'>
	<tr height=17 style='height:12.75pt'>
	<td height=17 class=xl6324108 width=35 style='height:12.75pt;width:26pt'></td>
	<td class=xl6324108 width=90 style='width:68pt'></td>
	<td class=xl6324108 width=45 style='width:34pt'></td>
	<td class=xl6324108 width=93 style='width:70pt'></td>
	<td class=xl6324108 width=93 style='width:70pt'></td>
	<td class=xl6324108 width=95 style='width:71pt'></td>
	<td class=xl6324108 width=86 style='width:65pt'></td>
	<td class=xl6324108 width=100 style='width:75pt'></td>
	<td class=xl6324108 width=91 style='width:68pt'></td>
	<td class=xl6324108 width=91 style='width:68pt'></td>
	<td class=xl6324108 width=89 style='width:67pt'></td>
	<td class=xl6324108 width=91 style='width:68pt'></td>
	<td class=xl6324108 width=87 style='width:65pt'></td>
	<td class=xl6324108 width=57 style='width:43pt'></td>
	<td class=xl6324108 width=57 style='width:43pt'></td>
	<td class=xl6324108 width=57 style='width:43pt'></td>
	<td class=xl6324108 width=57 style='width:43pt'></td>
	<td class=xl6324108 width=57 style='width:43pt'></td>
	</tr>
	<tr height=22 style='height:16.5pt'>
	<td colspan=17 height=22 class=xl7124108 style='height:16.5pt'>DOANH THU BÁN
	VÉ</td>
	</tr>
	<tr height=17 style='height:12.75pt'>
	<td colspan=17 height=17 class=xl6424108 style='height:12.75pt'>Từ ngày
	".$from_date." đến ngày ".$to_date."</td>
	</tr>
	<tr height=17 style='height:12.75pt'>
	<td height=17 class=xl6324108 style='height:12.75pt'></td>
	<td class=xl6324108></td>
	<td class=xl6324108></td>
	<td class=xl6324108></td>
	<td class=xl6324108></td>
	<td class=xl6324108></td>
	<td class=xl6324108></td>
	<td class=xl6324108></td>
	<td class=xl6324108></td>
	<td class=xl6324108></td>
	<td class=xl6324108></td>
	<td class=xl6324108></td>
	<td class=xl6324108></td>
	<td class=xl6324108></td>
	<td class=xl6324108></td>
	<td class=xl6324108></td>
	<td class=xl6324108></td>
	</tr>
	<tr height=26 style='mso-height-source:userset;height:19.5pt'>
	<td height=26 class=xl6524108 style='height:19.5pt'>STT</td>
	<td class=xl6524108 style='border-left:none'>Booking</td>
	<td class=xl6524108 style='border-left:none'>SL Vé</td>
	<td class=xl6524108 style='border-left:none'>Doanh thu</td>
	<td class=xl6524108 style='border-left:none'>Giá mua</td>
	<td class=xl6524108 style='border-left:none'>Phiếu thu</td>
	<td class=xl6524108 style='border-left:none'>Hãng bay</td>
	<td class=xl6524108 style='border-left:none'>Loại CB</td>
	<td class=xl6524108 style='border-left:none'>Hạng vé</td>
	<td class=xl6524108 style='border-left:none'>Nơi đi</td>
	<td class=xl6524108 style='border-left:none'>Ngày đi</td>
	<td class=xl6524108 style='border-left:none'>Nơi đến</td>
	<td class=xl6524108 style='border-left:none'>Ngày đến</td>
	<td class=xl6524108 style='border-left:none'>Tình trạng</td>
	<td class=xl6524108 style='border-left:none'>User</td>
	<td class=xl6524108 style='border-left:none'>Thu tiền</td>
	<td class=xl6524108 style='border-left:none'>Thành phố</td>
	<td class=xl6524108 style='border-left:none'>Ngày xuất vé</td>
	</tr>";
	
	$xls .= $data;
	
	
	$xls .= "<![if supportMisalignedColumns]>
	<tr height=0 style='display:none'>
	<td width=35 style='width:26pt'></td>
	<td width=90 style='width:68pt'></td>
	<td width=45 style='width:34pt'></td>
	<td width=93 style='width:70pt'></td>
	<td width=93 style='width:70pt'></td>
	<td width=95 style='width:71pt'></td>
	<td width=86 style='width:65pt'></td>
	<td width=100 style='width:75pt'></td>
	<td width=91 style='width:68pt'></td>
	<td width=91 style='width:68pt'></td>
	<td width=89 style='width:67pt'></td>
	<td width=91 style='width:68pt'></td>
	<td width=87 style='width:65pt'></td>
	<td width=57 style='width:43pt'></td>
	<td width=57 style='width:43pt'></td>
	<td width=57 style='width:43pt'></td>
	<td width=57 style='width:43pt'></td>
	</tr>
	<![endif]>
	</table>

	</div>


	<!----------------------------->
	<!--END OF OUTPUT FROM EXCEL PUBLISH AS WEB PAGE WIZARD-->
	<!----------------------------->
	</body>

	</html>";
 	
	return $xls;
}
