<?php
$dictionary['EC_Contact_Points_Log'] = array(
    'table' => 'ec_contact_points_log',
    'audited' => true,
    'inline_edit' => false,
    'duplicate_merge' => true,
    'fields' => array(
        'contact_phone' => array(
            'name'       => 'contact_phone',
            'vname'      => 'LBL_CONTACT_PHONE',
            'type'       => 'varchar',
            'length'     => 16,
            'default'    => '',
            'required'   => true,
            'importable' => false,
            'reportable' => false,
            'audited'    => true,
        ),
        'contact_id' => array(
            'name'       => 'contact_id',
            'vname'      => 'LBL_CONTACT_ID',
            'type'       => 'id',
            'length'     => 36,
            'default'    => '',
            'required'   => true,
            'importable' => false,
            'reportable' => false,
            'audited'    => true,
        ),
        'contact' => array(
            'name'       => 'contact',
            'vname'      => 'LBL_CONTACT',
            'source'     => 'non-db',
            'type'       => 'relate',
            'length'     => 255,
            'default'    => '',
            'massupdate' => false,
            'required'   => false,
            'importable' => false,
            'reportable' => false,
            'audited'    => true,
            'id_name'   => 'contact_id',
            'ext2'      => 'Contacts',
            'module'    => 'Contacts',
            'rname'     => 'name',
        ),

        'parent_type' => array(
            'name'       => 'parent_type',
            'vname'      => 'LBL_PARENT_TYPE',
            'type'       => 'varchar',
            'len'        => 64,
            'required'   => false,
            'default'    => '',
            'audited'    => true,
            'importable' => true,
            'reportable' => false,
            'studio'     => 'hidden',
        ),
        'parent_id' => array(
            'name'       => 'parent_id',
            'vname'      => 'LBL_PARENT_ID',
            'type'       => 'id',
            'len'        => 36,
            'required'   => false,
            'default'    => '',
            'audited'    => true,
            'importable' => true,
            'reportable' => false,
        ),

        'up' => array(
            'name'       => 'up',
            'vname'      => 'LBL_UP',
            'type'       => 'int',
            'dbtype'     => 'smallint',
            'default'    => 0,
            'importable' => true,
            'reportable' => false,
            'audited'    => true,
        ),

        'down' => array(
            'name'       => 'down',
            'vname'      => 'LBL_DOWN',
            'type'       => 'int',
            'dbtype'     => 'smallint',
            'default'    => 0,
            'importable' => false,
            'reportable' => false,
            'audited'    => true,
        ),
        
        'current_point' => array(
            'name'       => 'current_point',
            'vname'      => 'LBL_CURRENT_POINT',
            'type'       => 'int',
            'dbtype'     => 'int',
            'default'    => 0,
            'importable' => false,
            'reportable' => false,
            'audited'    => true,
        ),
    ),
    'indices' => array(
        array('name' => 'index_contact_id', 'type' => 'index', 'fields' => array('contact_id')),
        array('name' => 'index_contact_phone', 'type' => 'index', 'fields' => array('contact_phone')),
        array('name' => 'index_parent', 'type' => 'index', 'fields' => array('parent_id')),
    ),
    'relationships' => array(),
    'optimistic_locking' => true,
    'unified_search' => true,
);
if (!class_exists('VardefManager')) {
    require_once('include/SugarObjects/VardefManager.php');
}
VardefManager::createVardef('EC_Contact_Points_Log', 'EC_Contact_Points_Log', array('basic', 'assignable', 'security_groups'));
