<?php

$dictionary['EC_Targets'] = array(
    'table' => 'ec_targets',
    'audited' => true,
    'inline_edit' => true,
    'duplicate_merge' => true,
    'fields' => 
    array(
        'year' =>
        array(
            'required' => false,
            'name' => 'year',
            'vname' => 'LBL_YEAR',
            'type' => 'int',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 1,
            'reportable' => 0,
            'len' => '11',
            'disable_num_format' => 1,
        ),
        'target_year' =>
        array(
            'required' => false,
            'name' => 'target_year',
            'vname' => 'LBL_TARGET_YEAR',
            'type' => 'currency',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 1,
            'reportable' => 0,
            'len' => 26,
        ),
        'currency_id' =>
        array(
            'required' => false,
            'name' => 'currency_id',
            'vname' => 'LBL_CURRENCY',
            'type' => 'id',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => 0,
            'audited' => 0,
            'reportable' => 0,
            'len' => 36,
            'studio' => 'visible',
            'function' =>
            array(
                'name' => 'getCurrencyDropDown',
                'returns' => 'html',
            ),
        ),
        'target_quarter1' =>
        array(
            'required' => false,
            'name' => 'target_quarter1',
            'vname' => 'LBL_TARGET_QUARTER1',
            'type' => 'currency',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 1,
            'reportable' => 0,
            'len' => 26,
        ),
        'target_quarter2' =>
        array(
            'required' => false,
            'name' => 'target_quarter2',
            'vname' => 'LBL_TARGET_QUARTER2',
            'type' => 'currency',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 1,
            'reportable' => 0,
            'len' => 26,
        ),
        'target_quarter3' =>
        array(
            'required' => false,
            'name' => 'target_quarter3',
            'vname' => 'LBL_TARGET_QUARTER3',
            'type' => 'currency',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 1,
            'reportable' => 0,
            'len' => 26,
        ),
        'target_quarter4' =>
        array(
            'required' => false,
            'name' => 'target_quarter4',
            'vname' => 'LBL_TARGET_QUARTER4',
            'type' => 'currency',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 1,
            'reportable' => 0,
            'len' => 26,
        ),
        'target_month1' =>
        array(
            'required' => false,
            'name' => 'target_month1',
            'vname' => 'LBL_TARGET_MONTH1',
            'type' => 'currency',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 1,
            'reportable' => 0,
            'len' => 26,
        ),
        'target_month2' =>
        array(
            'required' => false,
            'name' => 'target_month2',
            'vname' => 'LBL_TARGET_MONTH2',
            'type' => 'currency',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 1,
            'reportable' => 0,
            'len' => 26,
        ),
        'target_month3' =>
        array(
            'required' => false,
            'name' => 'target_month3',
            'vname' => 'LBL_TARGET_MONTH3',
            'type' => 'currency',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 1,
            'reportable' => 0,
            'len' => 26,
        ),
        'target_month4' =>
        array(
            'required' => false,
            'name' => 'target_month4',
            'vname' => 'LBL_TARGET_MONTH4',
            'type' => 'currency',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 1,
            'reportable' => 0,
            'len' => 26,
        ),
        'target_month5' =>
        array(
            'required' => false,
            'name' => 'target_month5',
            'vname' => 'LBL_TARGET_MONTH5',
            'type' => 'currency',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 1,
            'reportable' => 0,
            'len' => 26,
        ),
        'target_month6' =>
        array(
            'required' => false,
            'name' => 'target_month6',
            'vname' => 'LBL_TARGET_MONTH6',
            'type' => 'currency',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 1,
            'reportable' => 0,
            'len' => 26,
        ),
        'target_month7' =>
        array(
            'required' => false,
            'name' => 'target_month7',
            'vname' => 'LBL_TARGET_MONTH7',
            'type' => 'currency',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 1,
            'reportable' => 0,
            'len' => 26,
        ),
        'target_month8' =>
        array(
            'required' => false,
            'name' => 'target_month8',
            'vname' => 'LBL_TARGET_MONTH8',
            'type' => 'currency',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 1,
            'reportable' => 0,
            'len' => 26,
        ),
        'target_month9' =>
        array(
            'required' => false,
            'name' => 'target_month9',
            'vname' => 'LBL_TARGET_MONTH9',
            'type' => 'currency',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 1,
            'reportable' => 0,
            'len' => 26,
        ),
        'target_month10' =>
        array(
            'required' => false,
            'name' => 'target_month10',
            'vname' => 'LBL_TARGET_MONTH10',
            'type' => 'currency',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 1,
            'reportable' => 0,
            'len' => 26,
        ),
        'target_month11' =>
        array(
            'required' => false,
            'name' => 'target_month11',
            'vname' => 'LBL_TARGET_MONTH11',
            'type' => 'currency',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 1,
            'reportable' => 0,
            'len' => 26,
        ),
        'target_month12' =>
        array(
            'required' => false,
            'name' => 'target_month12',
            'vname' => 'LBL_TARGET_MONTH12',
            'type' => 'currency',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 1,
            'reportable' => 0,
            'len' => 26,
        ),
        'target_type' =>
        array(
            'required' => false,
            'name' => 'target_type',
            'vname' => 'LBL_TARGET_TYPE',
            'type' => 'enum',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '',
            'audited' => 1,
            'reportable' => 0,
            'len' => 100,
            'options' => 'target_type_list',
            'studio' => 'visible',
            'dependency' => false,
        ),
        'user_id_c' =>
        array(
            'required' => false,
            'name' => 'user_id_c',
            'vname' => '',
            'type' => 'id',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => 0,
            'audited' => 0,
            'reportable' => 0,
            'len' => 36,
        ),
        'approved_by_user' =>
        array(
            'required' => false,
            'source' => 'non-db',
            'name' => 'approved_by_user',
            'vname' => 'LBL_APPROVED_BY_USER',
            'type' => 'relate',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 0,
            'reportable' => 0,
            'len' => '255',
            'id_name' => 'user_id_c',
            'ext2' => 'Users',
            'module' => 'Users',
            'rname' => 'name',
            'quicksearch' => 'enabled',
            'studio' => 'visible',
        ),
        'status' =>
        array(
            'required' => false,
            'name' => 'status',
            'vname' => 'LBL_STATUS',
            'type' => 'enum',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 1,
            'reportable' => 0,
            'len' => 100,
            'options' => 'target_status_list',
            'studio' => 'visible',
            'dependency' => false,
            'default' => '0',
        ),
        'approved_date' =>
        array(
            'required' => false,
            'name' => 'approved_date',
            'vname' => 'LBL_APPROVED_DATE',
            'type' => 'datetime',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 1,
            'reportable' => 0,
        ),
    ),
    'relationships' => array(),
    'optimistic_locking' => true,
    'unified_search' => true,
);
if (!class_exists('VardefManager')) {
    require_once('include/SugarObjects/VardefManager.php');
}
VardefManager::createVardef('EC_Targets', 'EC_Targets', array('basic', 'assignable', 'security_groups'));
