<?php


// THIS CONTENT IS GENERATED BY MBPackage.php
$manifest = array(
  0 =>
  array(
    'acceptable_sugar_versions' =>
    array(
      0 => '',
    ),
  ),
  1 =>
  array(
    'acceptable_sugar_flavors' =>
    array(
      0 => 'CE',
      1 => 'PRO',
      2 => 'ENT',
    ),
  ),
  'readme' => '',
  'key' => 'EC',
  'author' => 'Duc Pham',
  'description' => 'Records the history of accumulated points of contact,',
  'icon' => '',
  'is_uninstallable' => true,
  'name' => 'Contact_Points_Log',
  'published_date' => '2025-03-08 07:13:17',
  'type' => 'module',
  'version' => 1741417997,
  'remove_tables' => 'prompt',
);
