<?php


// THIS CONTENT IS GENERATED BY MBPackage.php
$manifest = array(
  0 =>
  array(
    'acceptable_sugar_versions' =>
    array(
      0 => '',
    ),
  ),
  1 =>
  array(
    'acceptable_sugar_flavors' =>
    array(
      0 => 'CE',
      1 => 'PRO',
      2 => 'ENT',
    ),
  ),
  'readme' => '',
  'key' => 'EC',
  'author' => 'DucPham',
  'description' => 'Quản lý tin nhắn SMS, ZNS,...',
  'icon' => '',
  'is_uninstallable' => true,
  'name' => 'Messages',
  'published_date' => '2024-08-14 03:08:39',
  'type' => 'module',
  'version' => 1723604919,
  'remove_tables' => 'prompt',
);
