<?php
// created: 2024-06-06 00:58:51
$sugar_config = array(
  'addAjaxBannedModules' =>
  array(
    0 => 'SecurityGroups',
    1 => 'EC_Flight_Bookings',
  ),
  'admin_access_control' => false,
  'admin_export_only' => false,
  'allowed_preview' =>
  array(
    0 => 'pdf',
    1 => 'gif',
    2 => 'png',
    3 => 'jpeg',
    4 => 'jpg',
  ),
  'anti_malware_scanners' =>
  array(
    'SuiteCRM\\Utility\\AntiMalware\\Providers\\ClamTCP' =>
    array(
      'name' => 'ClamAntiVirus TCP',
      'support_page' => 'https://www.clamav.net/',
      'enabled' => false,
      'path' => NULL,
      'options' =>
      array(
        'ip' => '127.0.0.1',
        'port' => 3310,
        'type' => 'local',
      ),
    ),
    'SuiteCRM\\Utility\\AntiMalware\\Providers\\Sophos' =>
    array(
      'name' => 'Sophos Anti Virus (Linux)',
      'support_page' => 'https://www.sophos.com/en-us/products/free-tools/sophos-antivirus-for-linux.aspx',
      'enabled' => false,
      'path' => '/opt/sophos-av/bin/savscan',
      'options' => '-ss',
    ),
  ),
  'aod' =>
  array(
    'enable_aod' => false,
  ),
  'aop' =>
  array(
    'distribution_method' => 'roundRobin',
    'case_closure_email_template_id' => '794c851e-80af-3f05-a133-64882ee87a2c',
    'joomla_account_creation_email_template_id' => '7a002352-a171-176c-9773-64882eff25b1',
    'case_creation_email_template_id' => '7aa7d329-4903-46e8-12ba-64882e4652b1',
    'contact_email_template_id' => '7d2c3f7c-0342-05c6-6c57-64882e3e1c1f',
    'user_email_template_id' => '7ddc611c-2e2f-b89a-a82e-64882eeacda0',
    'enable_aop' => false,
    'joomla_url' => '',
    'enable_portal' => false,
    'distribution_user_id' => '',
    'distribution_options' =>
    array(
      0 => 'all',
      1 => '',
      2 => '',
    ),
    'support_from_address' => '',
    'support_from_name' => '',
    'case_status_changes' => 'null',
  ),
  'aos' =>
  array(
    'version' => '5.3.3',
    'contracts' =>
    array(
      'renewalReminderPeriod' => '14',
    ),
    'lineItems' =>
    array(
      'totalTax' => false,
      'enableGroups' => false,
    ),
    'invoices' =>
    array(
      'initialNumber' => '1',
    ),
    'quotes' =>
    array(
      'initialNumber' => '1',
    ),
  ),
  'use_cache' => true,
  'cache_dir' => 'cache/',
  'calculate_response_time' => false,
  'calendar' =>
  array(
    'default_view' => 'week',
    'show_calls_by_default' => true,
    'show_tasks_by_default' => true,
    'show_completed_by_default' => true,
    'editview_width' => 990,
    'editview_height' => 485,
    'day_timestep' => 15,
    'week_timestep' => 30,
    'items_draggable' => true,
    'items_resizable' => true,
    'enable_repeat' => true,
    'max_repeat_count' => 1000,
  ),
  'chartEngine' => 'Jit',
  'common_ml_dir' => '',
  'create_default_user' => false,
  'cron' =>
  array(
    'max_cron_jobs' => 20,
    'max_cron_runtime' => 100,
    'min_cron_interval' => 0,
    'allowed_cron_users' =>
    array(
      0 => 'bmvmb2005',
      1 => 'root',
    ),
  ),
  'dashlet_auto_refresh_min' => '-1',
  'dashlet_display_row_options' =>
  array(
    0 => '1',
    1 => '3',
    2 => '5',
    3 => '10',
  ),
  'date_formats' =>
  array(
    'Y-m-d' => '2010-12-23',
    'm-d-Y' => '12-23-2010',
    'd-m-Y' => '23-12-2010',
    'Y/m/d' => '2010/12/23',
    'm/d/Y' => '12/23/2010',
    'd/m/Y' => '23/12/2010',
    'Y.m.d' => '2010.12.23',
    'd.m.Y' => '23.12.2010',
    'm.d.Y' => '12.23.2010',
  ),
  'datef' => 'm/d/Y',
  'dbconfig' =>
  array(
    'db_host_name' => 'localhost',
    'db_host_instance' => 'SQLEXPRESS',
    'db_user_name' => '',
    'db_password' => '',
    'db_name' => '',
    'db_type' => 'mysql',
    'db_port' => '',
    'db_manager' => 'MysqliManager',
    'collation' => 'utf8mb4_general_ci',
    'charset' => 'utf8mb4',
    'optimize' => true,
    'db_engine' => 'InnoDB',
  ),
  'dbconfigoption' =>
  array(
    'persistent' => true,
    'autofree' => false,
    'debug' => 0,
    'ssl' => false,
    'collation' => 'utf8mb4_general_ci',
    'charset' => 'utf8mb4',
  ),
  'default_action' => 'index',
  'default_charset' => 'UTF-8',
  'default_currency_iso4217' => 'VND',
  'default_currency_name' => 'VND',
  'default_currency_significant_digits' => 2,
  'default_currency_symbol' => '',
  'default_date_format' => 'd-m-Y',
  'default_decimal_seperator' => '.',
  'default_email_charset' => 'UTF-8',
  'default_email_client' => 'sugar',
  'default_email_editor' => 'html',
  'default_export_charset' => 'UTF-8',
  'default_language' => 'vi_VN',
  'default_locale_name_format' => 's f l',
  'default_max_tabs' => 10,
  'default_module' => 'Home',
  'default_module_favicon' => false,
  'default_navigation_paradigm' => 'gm',
  'default_number_grouping_seperator' => ',',
  'default_password' => '',
  'default_permissions' =>
  array(
    'dir_mode' => 1528,
    'file_mode' => 493,
    'user' => '',
    'group' => '',
  ),
  'default_subpanel_links' => false,
  'default_subpanel_tabs' => true,
  'default_swap_last_viewed' => false,
  'default_swap_shortcuts' => false,
  'default_theme' => 'SuiteP',
  'default_time_format' => 'H:i',
  'default_user_is_admin' => false,
  'default_user_name' => '',
  'demoData' => 'no',
  'developerMode' => false,
  'disableAjaxUI' => true,
  'disable_convert_lead' => true,
  'disable_export' => false,
  'disable_persistent_connections' => true,
  'disable_vcr' => true,
  'disabled_languages' => '',
  'disabled_themes' => 'SuiteP_old',
  'display_email_template_variable_chooser' => false,
  'display_inbound_email_buttons' => false,
  'dump_slow_queries' => true,
  'email_address_separator' => ',',
  'email_allow_send_as_user' => false,
  'email_confirm_opt_in_email_template_id' => '',
  'email_default_client' => 'sugar',
  'email_default_delete_attachments' => true,
  'email_default_editor' => 'html',
  'email_enable_auto_send_opt_in' => false,
  'email_enable_confirm_opt_in' => 'not-opt-in',
  'email_warning_notifications' => true,
  'email_xss' => 'YToxMzp7czo2OiJhcHBsZXQiO3M6NjoiYXBwbGV0IjtzOjQ6ImJhc2UiO3M6NDoiYmFzZSI7czo1OiJlbWJlZCI7czo1OiJlbWJlZCI7czo0OiJmb3JtIjtzOjQ6ImZvcm0iO3M6NToiZnJhbWUiO3M6NToiZnJhbWUiO3M6ODoiZnJhbWVzZXQiO3M6ODoiZnJhbWVzZXQiO3M6NjoiaWZyYW1lIjtzOjY6ImlmcmFtZSI7czo2OiJpbXBvcnQiO3M6ODoiXD9pbXBvcnQiO3M6NToibGF5ZXIiO3M6NToibGF5ZXIiO3M6NDoibGluayI7czo0OiJsaW5rIjtzOjY6Im9iamVjdCI7czo2OiJvYmplY3QiO3M6MzoieG1wIjtzOjM6InhtcCI7czo2OiJzY3JpcHQiO3M6Njoic2NyaXB0Ijt9',
  'enable_action_menu' => false,
  'enable_line_editing_detail' => false,
  'enable_line_editing_list' => false,
  'export_delimiter' => ',',
  'export_excel_compatible' => false,
  'filter_module_fields' =>
  array(
    'Users' =>
    array(
      0 => 'show_on_employees',
      1 => 'portal_only',
      2 => 'is_group',
      3 => 'system_generated_password',
      4 => 'external_auth_only',
      5 => 'sugar_login',
      6 => 'authenticate_id',
      7 => 'pwd_last_changed',
      8 => 'is_admin',
      9 => 'user_name',
      10 => 'user_hash',
      11 => 'password',
      12 => 'last_login',
      13 => 'oauth_tokens',
    ),
    'Employees' =>
    array(
      0 => 'show_on_employees',
      1 => 'portal_only',
      2 => 'is_group',
      3 => 'system_generated_password',
      4 => 'external_auth_only',
      5 => 'sugar_login',
      6 => 'authenticate_id',
      7 => 'pwd_last_changed',
      8 => 'is_admin',
      9 => 'user_name',
      10 => 'user_hash',
      11 => 'password',
      12 => 'last_login',
      13 => 'oauth_tokens',
    ),
  ),
  'google_auth_json' => '',
  'hide_subpanels' => true,
  'history_max_viewed' => 50,
  'host_name' => 'bm.vemaybay.website',
  'id_validation_pattern' => '/^[a-zA-Z0-9_-]*$/i',
  'imap_test' => false,
  'import_max_execution_time' => 3600,
  'import_max_records_per_file' => 100,
  'import_max_records_total_limit' => '',
  'inbound_email_case_subject_macro' => '',
  'installer_locked' => true,
  'jobs' =>
  array(
    'min_retry_interval' => 30,
    'max_retries' => 5,
    'timeout' => 86400,
  ),
  'js_custom_version' => 1,
  'js_lang_version' => 91,
  'languages' =>
  array(
    'vi_VN' => 'Tiếng Việt (VN)',
    'en_us' => 'English (US)',
  ),
  'large_scale_test' => false,
  'lead_conv_activity_opt' => 'donothing',
  'legacy_email_behaviour' => false,
  'list_max_entries_per_page' => '25',
  'list_max_entries_per_subpanel' => 10,
  'lock_default_user_name' => false,
  'lock_homepage' => true,
  'lock_subpanels' => true,
  'log_dir' => 'secure_sessions/log',
  'log_file' => 'suitecrm.log',
  'log_memory_usage' => false,
  'logger' =>
  array(
    'level' => 'error',
    'file' =>
    array(
      'ext' => '.log',
      'name' => 'suitecrm',
      'dateFormat' => '%c',
      'maxSize' => '100MB',
      'maxLogs' => 10,
      'suffix' => '%m_%d_%y',
    ),
  ),
  'max_dashlets_homepage' => '15',
  'name_formats' =>
  array(
    's l f' => 's l f',
    's f l' => 's f l',
    'f l' => 'f l',
    's l' => 's l',
    'l, s f' => 'l, s f',
    'l, f' => 'l, f',
    's l, f' => 's l, f',
    'l s f' => 'l s f',
  ),
  'oauth2_encryption_key' => 'QWxwCaH7ix0PN1fm9dAcLx9wN+bu7wY/+0CHl9eDxTg=',
  'passwordsetting' =>
  array(
    'SystemGeneratedPasswordON' => '',
    'generatepasswordtmpl' => '2e828bb0-902f-570b-a8e1-64882e18a28e',
    'lostpasswordtmpl' => '2f2f99c0-88ce-7d5c-fd1f-64882efff353',
    'factoremailtmpl' => '2fd2e433-1efb-da7f-6584-64882ed3e8e0',
    'forgotpasswordON' => false,
    'linkexpiration' => '1',
    'linkexpirationtime' => '30',
    'linkexpirationtype' => '1',
    'systexpiration' => '1',
    'systexpirationtime' => '7',
    'systexpirationtype' => '1',
    'systexpirationlogin' => '',
  ),
  'pdf' =>
  array(
    'defaultEngine' => 'TCPDFEngine',
  ),
  'portal_view' => 'single_user',
  'require_accounts' => true,
  'resource_management' =>
  array(
    'special_query_limit' => 50000,
    'special_query_modules' =>
    array(
      0 => 'AOR_Reports',
      1 => 'Export',
      2 => 'Import',
      3 => 'Administration',
      4 => 'Sync',
    ),
    'default_limit' => 20000,
  ),
  'rss_cache_time' => '10800',
  'save_query' => 'all',
  'search' =>
  array(
    'controller' => 'UnifiedSearch',
    'defaultEngine' => 'BasicSearchEngine',
    'pagination' =>
    array(
      'min' => 10,
      'max' => 50,
      'step' => 10,
    ),
    'ElasticSearch' =>
    array(
      'enabled' => false,
      'host' => 'localhost',
      'user' => '',
      'pass' => '',
      'index' => 'LY0Ry9GR1sKZ8k91cj1Inamphuong',
      'search_wildcard_char' => '%',
      'search_wildcard_infront' => true,
    ),
  ),
  'search_wildcard_char' => '%',
  'search_wildcard_infront' => false,
  'securitysuite_additive' => true,
  'securitysuite_filter_user_list' => false,
  'securitysuite_inbound_email' => false,
  'securitysuite_inherit_assigned' => true,
  'securitysuite_inherit_creator' => true,
  'securitysuite_inherit_parent' => false,
  'securitysuite_popup_select' => false,
  'securitysuite_strict_rights' => false,
  'securitysuite_user_popup' => false,
  'securitysuite_user_role_precedence' => true,
  'securitysuite_version' => '6.5.17',
  'session_dir' => 'secure_sessions',
  'session_gc' =>
  array(
    'enable' => true,
    'gc_probability' => 1,
    'gc_divisor' => 100,
  ),
  'showDetailData' => true,
  'showThemePicker' => true,
  'site_url' => 'http://bm.vemaybay.website',
  'slow_query_time_msec' => '1000',
  'stackTrace' => false,
  'stack_trace_errors' => false,
  'strict_id_validation' => false,
  'sugar_version' => '6.5.25',
  'sugarbeet' => false,
  'suitecrm_version' => '7.13.3',
  'system_email_templates' =>
  array(
    'confirm_opt_in_template_id' => 'd2157218-2ace-d4f2-1339-64882e860bc4',
  ),
  'time_formats' =>
  array(
    'H:i' => '23:00',
    'h:ia' => '11:00pm',
    'h:iA' => '11:00PM',
    'h:i a' => '11:00 pm',
    'h:i A' => '11:00 PM',
    'H.i' => '23.00',
    'h.ia' => '11.00pm',
    'h.iA' => '11.00PM',
    'h.i a' => '11.00 pm',
    'h.i A' => '11.00 PM',
  ),
  'timef' => 'H:i',
  'tmp_dir' => 'cache/xml/',
  'tracker_max_display_length' => 15,
  'translation_string_prefix' => false,
  'unique_key' => 'LY0Ry9GR1sKZ8k91cj1Inamphuong',
  'upload_badext' =>
  array(
    0 => 'php',
    1 => 'php3',
    2 => 'php4',
    3 => 'php5',
    4 => 'php6',
    5 => 'php7',
    6 => 'php8',
    7 => 'pl',
    8 => 'cgi',
    9 => 'py',
    10 => 'asp',
    11 => 'cfm',
    12 => 'js',
    13 => 'vbs',
    14 => 'html',
    15 => 'htm',
    16 => 'phtml',
    17 => 'phar',
  ),
  'upload_dir' => 'cache/upload/',
  'upload_maxsize' => '20000000',
  'use_common_ml_dir' => false,
  'use_php_code_json' => true,
  'use_real_names' => false,
  'vcal_time' => '0',
  'verify_client_ip' => false,
  'valid_image_ext' =>
  array(
    0 => 'gif',
    1 => 'png',
    2 => 'jpg',
    3 => 'jpeg',
    4 => 'svg',
    5 => 'bmp',
  ),
  'valid_imap_ports' =>
  array(
    0 => '110',
    1 => '143',
    2 => '993',
    3 => '995',
  ),
  'enable_legacy_search' =>
  array(
    0 => 'Accounts',
    1 => 'EC_Flight_Bookings',
    2 => 'EC_Receipt_Voucher',
    3 => 'EC_Payment_Voucher',
    4 => 'EC_ChuyenTienNoiBo',
    5 => 'Users',
    7 => 'EC_Bank_Account',
    8 => 'EC_Banks',
    9 => 'EC_LeaveAbsenceTypes',
    10 => 'EC_LeaveAbsences',
    11 => 'EC_WorkingOverTimes',
    13 => 'SecurityGroups',
    14 => 'EC_LyDoThangThua',
    15 => 'EC_Location',
    16 => 'EC_HoanVe',
    17 => 'EC_Vouchers',
    18 => 'EC_Request_Flight',
    19 => 'EC_Payment_Types',
    20 => 'EC_Customer',
    21 => 'Employees',
    22 => 'EC_ChiTietHoaDon',
    23 => 'EC_HoaDonBan',
    24 => 'EC_LoginAudit',
    25 => 'OAuth2Clients',
    26 => 'EC_ChiTietTaiKhoan',
    27 => 'Calls',
    28 => 'Contacts',
    29 => 'Campaigns',
    30 => 'EC_WorkHistory',
    31 => 'Schedulers',
    32 => 'EC_SMS_Logs',
    33 => 'ACLRoles',
    34 => 'InboundEmail',
    35 => 'OutboundEmailAccounts',
    36 => 'ExternalOAuthConnection',
    37 => 'Emails',
  ),
  'import_dir' => 'cache/import/',
  'disable_count_query' => true,
  'hide_subpanels_on_login' => true,
  'disable_ip_address_logging' => true,
  'enable_the_awesome' => true,
  'external_cache_disabled' => false,
  'external_cache_disabled_memcached' => false,
  'output_compression' => true,
  'config_lock' => true,
  'opcache_enabled' => true,
  'disable_user_personalization' => true,
  'external_tinymce' => false,
  'disable_merge_realtime' => true,
  'reminder_max_days' => -1,
  'reminder_email' => false,
  'disable_group_subpanels' => true,
  'quick_create' =>
  array(
    'enable' => false,
  ),
  'enable_feed' => false,
  'fast_search' => true,
  'external_cache_disabled_redis' => false,
  'disable_query_severity' => true,
  'show_log_with_php_messages' => true,
  'show_log_trace' => true,
  'hide_history_contacts_emails' =>
  array(
    'Cases' => true,
    'Accounts' => false,
    'Opportunities' => true,
  ),
);
