<?php


// THIS CONTENT IS GENERATED BY MBPackage.php
$manifest = array(
  0 =>
  array(
    'acceptable_sugar_versions' =>
    array(
      0 => '',
    ),
  ),
  1 =>
  array(
    'acceptable_sugar_flavors' =>
    array(
      0 => 'CE',
      1 => 'PRO',
      2 => 'ENT',
    ),
  ),
  'readme' => '',
  'key' => 'EC',
  'author' => 'Haihugn',
  'description' => 'Cam kết',
  'icon' => '',
  'is_uninstallable' => true,
  'name' => 'Commission',
  'published_date' => '2023-09-28 03:15:34',
  'type' => 'module',
  'version' => 1695870934,
  'remove_tables' => 'prompt',
);
