<?php
$dictionary['EC_Vouchers'] = array(
	'table' => 'ec_vouchers',
	'audited' => true,
	'inline_edit' => false,
	'duplicate_merge' => true,
	'fields' => array(
		// Voucher type (Group or Single)
		'type' => array(
			'name' => 'type',
			'vname' => 'LBL_TYPE',
			'type' => 'enum',
			'options' => 'voucher_type_list',
			'len' => 10,
			'default' => 'single',
			'audited' => 1,
			'massupdate' => 0,
			'reportable' => 0,
			'importable' => true,
			'required' => false,
			'studio' => 'visible',
			'dependency' => false,
		),

		'status' => array(
			'name' => 'status',
			'vname' => 'LBL_STATUS',
			'type' => 'enum',
			'options' => 'voucher_status_list',
			'len' => 10,
			'default' => 'pending',
			'audited' => 1,
			'massupdate' => 0,
			'reportable' => 0,
			'importable' => true,
			'required' => false,
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'studio' => 'visible',
			'dependency' => false,
		),

		// Thời gian bắt đầu
		'start_time' => array(
			'name' 	=> 'start_time',
			'vname' => 'LBL_START_TIME',
			'type' 	=> 'datetime',
			'required' => true,
		),

		// Thời gian kết thúc
		'end_time' => array(
			'name' => 'end_time',
			'vname' => 'LBL_END_TIME',
			'type' => 'datetime',
			'required' => true,
		),

		// // Ngày sử dụng
		// 'applied_date' => array(
		// 	'name' => 'applied_date',
		// 	'vname' => 'LBL_APPLIED_DATE',
		// 	'type' => 'datetimecombo',
		// 	'dbType' => 'datetime',
		// 	'required' => false,
		// 	'massupdate' => 0,
		// 	'importable' => 1,
		// 	'audited' => 0,
		// 	'reportable' => 0,
		// 	'duplicate_merge' => 'disabled',
		// 	'duplicate_merge_dom_value' => '0',
		// ),

		// Thông tin sự kiện phát hành voucher
		'campaign_name' => array(
			'name'       => 'campaign_name',
			'vname'      => 'LBL_CAMPAIGN_NAME',
			'type'       => 'varchar',
			'len'        => 255,
			'default'    => '',
			'importable' => true,
			'reportable' => false,
			'audited' => false,
		),
		'campaign_id' => array(
			'name'       => 'campaign_id',
			'vname'      => 'LBL_CAMPAIGN_ID',
			'type'       => 'campaign_id',
			'dbType'     => 'varchar',
			'len'        => 36,
			'required'   => true,
			'default'    => '',
			'importable' => true,
			'reportable' => false,
			'audited'    => false,
		),
		'campaign_name' => array(
			'name'       => 'campaign_name',
			'vname'      => 'LBL_CAMPAIGN_NAME',
			'type'       => 'varchar',
			'len'        => 255,
			'default'    => '',
			'importable' => true,
			'reportable' => false,
			'audited' => false,
		),

		// Thông tin khách hàng được tặng voucher (Dành cho voucher đơn)
		'contact_id' => array(
			'name'       => 'contact_id',
			'vname'      => 'LBL_CONTACT_ID',
			'type'       => 'varchar',
			'len'        => 36,
			'default'    => '',
			'importable' => true,
			'reportable' => false,
			'audited' => false,
		),
		'contact_name' => array(
			'name' => 'contact_name',
			'vname' => 'LBL_CONTACT',
			'type' => 'relate',
			'source' => 'non-db',
			'id_name' => 'contact_id',
			'ext2' => 'Contacts',
			'module' => 'Contacts',
			'rname' => 'name',
			'quicksearch' => 'enabled',
			'studio' => 'visible',
		),

		'reduce_amount' => array(
			'name' => 'reduce_amount',
			'vname' => 'LBL_REDUCE_AMOUNT',
			'type' => 'int',
			'len' => 11,
			'default' => 0,
			'required' => 0,
			'massupdate' => 0,
			'importable' => 1,
			'audited' => 0,
			'reportable' => 0,
			'disable_num_format' => true,
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
		),

		'reduce_percent' => array(
			'name' => 'reduce_percent',
			'vname' => 'LBL_REDUCE_PERCENT',
			'type' => 'int',
			'len' => 3,
			'default' => 0,
			'required' => 0,
			'massupdate' => 0,
			'importable' => 1,
			'audited' => 0,
			'reportable' => 0,
			'disable_num_format' => false,
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
		),

		'max_discount' => array(
			'name' => 'max_discount',
			'vname' => 'LBL_MAX_DISCOUNT',
			'type' => 'int',
			'len' => 11,
			'default' => 0,
			'required' => 0,
			'massupdate' => 0,
			'importable' => 1,
			'audited' => 0,
			'reportable' => 0,
			'disable_num_format' => '',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
		),

		// Releasing quantity
		'quantity' => array(
			'name' => 'quantity',
			'vname' => 'LBL_QUANTITY',
			'type' => 'int',
			'len' => 11,
			'default' => 1,
			'required' => 0,
			'massupdate' => 0,
			'importable' => 1,
			'audited' => 0,
			'reportable' => 0,
			'disable_num_format' => '',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
		),

		// Releasing quantity
		'quantity' => array(
			'name' => 'quantity',
			'vname' => 'LBL_QUANTITY',
			'type' => 'int',
			'len' => 11,
			'default' => 1,
			'required' => 0,
			'massupdate' => 0,
			'importable' => 1,
			'audited' => 0,
			'reportable' => 0,
			'disable_num_format' => '',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
		),

		// Conditions apply
		'condition_voucher' => array(
			'name' => 'condition_voucher',
			'vname' => 'LBL_CONDITION_VOUCHER',
			'type' => 'text',
			'default' => '',
			'required' => 0,
			'massupdate' => 0,
			'importable' => 1,
			'audited' => 0,
			'reportable' => 1,
			'comments' => 'Điều kiện áp dụng voucher',
		),

		// Website apply
		'website' => array(
			'name' => 'website',
			'vname' => 'LBL_WEBSITE',
			'type' => 'varchar',
			'len' => 40,
			'default' => '',
			'required' => 0,
			'massupdate' => 0,
			'importable' => 1,
			'audited' => 0,
			'reportable' => 0,
		),

		'bookings' => array(
            'name' => 'bookings',
            'type' => 'link',
            'vname' => 'LBL_BOOKING',
            'source' => 'non-db',
            'relationship' => 'bookings_vouchers',
            'link_type' => 'one',
            'duplicate_merge' => 'disabled',
        ),
		'booking_id' => array(
            'name' => 'booking_id',
            'rname' => 'id',
            'id_name' => 'booking_id',
            'vname' => 'LBL_BOOKING_ID',
            'type' => 'relate',
            'table' => 'bookings',
            'isnull' => 'true',
            'module' => 'EC_Flight_Bookings',
            'dbType' => 'id',
            'reportable' => false,
            'source' => 'non-db',
            'massupdate' => false,
            'duplicate_merge' => 'disabled',
            'hideacl' => true,
        ),
		'booking_name' => array(
            'name' => 'booking_name',
            'rname' => 'name',
            'id_name' => 'booking_id',
            'vname' => 'LBL_BOOKING_NAME',
            'join_name' => 'bookings',
            'type' => 'relate',
            'link' => 'bookings',
            'table' => 'bookings',
            'isnull' => 'true',
            'module' => 'EC_Flight_Bookings',
            'dbType' => 'varchar',
            'len' => '20',
            'source' => 'non-db',
            'unified_search' => true,
        ),

		// Dành cho voucher nhóm nhập mã, không hiện sẵn
		'is_hidden' => array(
            'name'       => 'is_hidden',
            'vname'      => 'LBL_IS_HIDDEN',
            'type'       => 'bool',
            'default'    => 0,
            'importable' => true,
            'reportable' => false,
        ),
	),
	'indices' => array(
		array('name' => 'idx_vouchers_code', 'type' => 'index', 'fields' => array('name')),
		array('name' => 'idx_vouchers_campaign_id', 'type' => 'index', 'fields' => array('campaign_id')),
		array('name' => 'idx_vouchers_contact_id', 'type' => 'index', 'fields' => array('contact_id')),
	),
	'relationships' => array(),
	'optimistic_locking' => true,
	'unified_search' => true,
);

if (!class_exists('VardefManager')) {
	require_once('include/SugarObjects/VardefManager.php');
}
VardefManager::createVardef('EC_Vouchers', 'EC_Vouchers', array('basic', 'assignable', 'security_groups'));
