<?php
$dictionary['EC_Vouchers'] = array(
	'table' => 'ec_vouchers',
	'audited' => true,
	'inline_edit' => false,
	'duplicate_merge' => true,
	'fields' => array(
		// Loại voucher (Đơn hoặc Nhóm)
		'type' => array(
			'name' => 'type',
			'vname' => 'LBL_TYPE',
			'type' => 'enum',
			'options' => 'voucher_type_list',
			'len' => 10,
			'default' => 'single',
			'audited' => 1,
			'massupdate' => 0,
			'reportable' => 0,
			'importable' => true,
			'required' => false,
			'studio' => 'visible',
			'dependency' => false,
		),

		// Tình trạng voucher
		'status' => array(
			'name' => 'status',
			'vname' => 'LBL_STATUS',
			'type' => 'enum',
			'options' => 'voucher_status_list',
			'len' => 16,
			'default' => 'new',
			'audited' => 1,
			'massupdate' => 0,
			'reportable' => 0,
			'importable' => true,
			'required' => false,
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'studio' => 'visible',
			'dependency' => false,
		),

		// Thời gian bắt đầu
		'start_time' => array(
			'name' 	=> 'start_time',
			'vname' => 'LBL_START_TIME',
			'type' 	=> 'datetime',
			'required' => true,
		),

		// Thời gian kết thúc
		'end_time' => array(
			'name' => 'end_time',
			'vname' => 'LBL_END_TIME',
			'type' => 'datetime',
			'required' => true,
		),

		// Ngày sử dụng
		'applied_date' => array(
			'name' => 'applied_date',
			'vname' => 'LBL_APPLIED_DATE',
			'type' => 'datetimecombo',
			'dbType' => 'datetime',
			'required' => false,
			'massupdate' => 0,
			'importable' => 1,
			'audited' => 0,
			'reportable' => 0,
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
		),

		// Thông tin sự kiện phát hành voucher
		'campaign_name' => array(
			'name'       => 'campaign_name',
			'vname'      => 'LBL_CAMPAIGN_NAME',
			'type'       => 'varchar',
			'len'        => 255,
			'default'    => '',
			'importable' => true,
			'reportable' => false,
			'audited' => false,
		),
		'campaign_id' => array(
			'name'       => 'campaign_id',
			'vname'      => 'LBL_CAMPAIGN_ID',
			'type'       => 'campaign_id',
			'dbType'     => 'varchar',
			'len'        => 36,
			'required'   => true,
			'default'    => '',
			'importable' => true,
			'reportable' => false,
			'audited'    => false,
		),

		// Thông tin khách hàng sử dụng voucher
		'account_name' => array(
			'name' => 'account_name',
			'vname' => 'LBL_ACCOUNT_NAME',
			'type' => 'varchar',
			'len' => 64,
			'required' => 0,
			'massupdate' => 0,
			'importable' => 1,
			'audited' => 0,
			'reportable' => 0,
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
		),
		'account_phone' => array(
			'name' => 'account_phone',
			'vname' => 'LBL_ACCOUNT_PHONE',
			'type' => 'varchar',
			'len' => 16,
			'required' => 0,
			'massupdate' => 0,
			'importable' => 1,
			'audited' => 0,
			'reportable' => 0,
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
		),
		'account_email' => array(
			'name' => 'account_email',
			'vname' => 'LBL_ACCOUNT_EMAIL',
			'type' => 'varchar',
			'len' => 30,
			'required' => 0,
			'massupdate' => 0,
			'importable' => 1,
			'audited' => 0,
			'reportable' => 0,
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
		),
		'account_address' => array(
			'name' => 'account_address',
			'vname' => 'LBL_ACCOUNT_ADDRESS',
			'type' => 'varchar',
			'len' => 255,
			'required' => 0,
			'massupdate' => 0,
			'importable' => 1,
			'audited' => 0,
			'reportable' => 0,
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
		),

		// Thông tin booking
		'booking_receive_id' => array(
			'name' => 'booking_receive_id',
			'vname' => '',
			'type' => 'id',
			'len' => 36,
			'importable' => 1,
			'audited' => 0,
			'reportable' => 0,
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => 0,
		),
		'booking' => array(
			'required' => false,
			'source' => 'non-db',
			'name' => 'booking',
			'vname' => 'LBL_BOOKING',
			'type' => 'relate',
			'id_name' => 'booking_receive_id',
			'ext2' => 'EC_Flight_Bookings',
			'module' => 'EC_Flight_Bookings',
			'rname' => 'name',
			'quicksearch' => 'enabled',
			'studio' => 'visible',
		),

		// Số tiền giảm
		'reduce_amount' => array(
			'name' => 'reduce_amount',
			'vname' => 'LBL_REDUCE_AMOUNT',
			'type' => 'int',
			'len' => 11,
			'required' => 0,
			'massupdate' => 0,
			'importable' => 1,
			'audited' => 0,
			'reportable' => 0,
			'disable_num_format' => '',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
		),

		// Số phần trăm giảm
		'reduce_percent' => array(
			'name' => 'reduce_percent',
			'vname' => 'LBL_REDUCE_PERCENT',
			'type' => 'int',
			'len' => 3,
			'required' => 0,
			'massupdate' => 0,
			'importable' => 1,
			'audited' => 0,
			'reportable' => 0,
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
		),

		// Giảm tối đa
		'max_discount' => array(
			'name' => 'max_discount',
			'vname' => 'LBL_MAX_DISCOUNT',
			'type' => 'int',
			'len' => 11,
			'default' => 0,
			'required' => 0,
			'massupdate' => 0,
			'importable' => 1,
			'audited' => 0,
			'reportable' => 0,
			'disable_num_format' => '',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
		),

		// Releasing quantity
		'quantity' => array(
			'name' => 'quantity',
			'vname' => 'LBL_QUANTITY',
			'type' => 'int',
			'len' => 11,
			'default' => 1,
			'required' => 0,
			'massupdate' => 0,
			'importable' => 1,
			'audited' => 0,
			'reportable' => 0,
			'disable_num_format' => '',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
		),

		// Điều kiện áp dụng
		'condition_voucher' => array(
			'name' => 'condition_voucher',
			'vname' => 'LBL_CONDITION_VOUCHER',
			'type' => 'text',
			'default' => '',
			'required' => 0,
			'massupdate' => 0,
			'importable' => 1,
			'audited' => 0,
			'reportable' => 1,
			'comments' => 'Điều kiện áp dụng voucher',
		),

		// Website apply
		'website' => array(
			'name' => 'website',
			'vname' => 'LBL_WEBSITE',
			'type' => 'varchar',
			'len' => 40,
			'default' => '',
			'required' => 0,
			'massupdate' => 0,
			'importable' => 1,
			'audited' => 0,
			'reportable' => 0,
		),
	),
	'indices' => array(
		array('name' => 'idx_vouchers_code', 'type' => 'index', 'fields' => array('name')),
		array('name' => 'idx_vouchers_campaign_id', 'type' => 'index', 'fields' => array('campaign_id')),
		array('name' => 'idx_vouchers_account_phone', 'type' => 'index', 'fields' => array('account_phone')),
		array('name' => 'idx_vouchers_booking_id', 'type' => 'index', 'fields' => array('booking_receive_id')),
		array('name' => 'idx_vouchers_applied_date', 'type' => 'index', 'fields' => array('applied_date')),
	),
	'relationships' => array(),
	'optimistic_locking' => true,
	'unified_search' => true,
);

if (!class_exists('VardefManager')) {
	require_once('include/SugarObjects/VardefManager.php');
}
VardefManager::createVardef('EC_Vouchers', 'EC_Vouchers', array('basic', 'assignable', 'security_groups'));
