<?php
$dictionary['EC_Vouchers'] = array(
	'table' => 'ec_vouchers',
	'audited' => true,
	'inline_edit' => false,
	'duplicate_merge' => true,
	'fields' => array(
		// Loại voucher (Đơn hoặc Nhóm)
		'type' => array(
			'name' => 'type',
			'vname' => 'LBL_TYPE',
			'type' => 'enum',
			'options' => 'voucher_type_list',
			'len' => 16,
			'default' => 'single',
			'audited' => 1,
			'massupdate' => 0,
			'reportable' => 0,
			'importable' => true,
			'required' => false,
			'studio' => 'visible',
			'dependency' => false,
		),

		// Tình trạng voucher
		'status' => array(
			'name' => 'status',
			'vname' => 'LBL_STATUS',
			'type' => 'enum',
			'options' => 'voucher_status_list',
			'len' => 16,
			'default' => 'new',
			'audited' => 1,
			'massupdate' => 0,
			'reportable' => 0,
			'importable' => true,
			'required' => false,
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'studio' => 'visible',
			'dependency' => false,
		),

		// Ngày sử dụng
		'applied_date' => array(
			'name' => 'applied_date',
			'vname' => 'LBL_APPLIED_DATE',
			'type' => 'datetimecombo',
			'dbType' => 'datetime',
			'required' => false,
			'massupdate' => 0,
			'importable' => 1,
			'audited' => 0,
			'reportable' => 0,
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
		),

		// 'active_date' => array(
		// 	'name' => 'active_date',
		// 	'vname' => 'LBL_ACTIVE_DATE',
		// 	'type' => 'datetimecombo',
		// 	'dbType' => 'datetime',
		// 	'required' => false,
		// 	'audited' => 0,
		// 	'reportable' => 0,
		// 	'massupdate' => 0,
		// 	'importable' => 1,
		// 	'duplicate_merge' => 'disabled',
		// 	'duplicate_merge_dom_value' => '0',
		// ),

		// Ngày bắt đầu
		'validate_from_date' => array(
			'name' => 'validate_from_date',
			'vname' => 'LBL_VALIDATE_FROM_DATE',
			'type' => 'date',
			'required' => 0,
			'massupdate' => 0,
			'importable' => 1,
			'audited' => 1,
			'reportable' => 0,
			'display_default' => 'now',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
		),

		// Ngày kết thúc
		'validate_to_date' => array(
			'name' => 'validate_to_date',
			'vname' => 'LBL_VALIDATE_TO_DATE',
			'type' => 'date',
			'required' => 0,
			'massupdate' => 0,
			'importable' => 1,
			'audited' => 1,
			'reportable' => 0,
			'display_default' => 'now',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
		),

		// 'dep_code' => array(
		// 	'required' => false,
		// 	'name' => 'dep_code',
		// 	'vname' => 'LBL_DEP_CODE',
		// 	'type' => 'varchar',
		// 	'massupdate' => 0,
		// 	'importable' => 'true',
		// 	'duplicate_merge' => 'disabled',
		// 	'duplicate_merge_dom_value' => '0',
		// 	'audited' => 0,
		// 	'reportable' => 0,
		// 	'len' => 5,
		// ),
		// 'arv_code' => array(
		// 	'required' => false,
		// 	'name' => 'arv_code',
		// 	'vname' => 'LBL_ARV_CODE',
		// 	'type' => 'varchar',
		// 	'massupdate' => 0,
		// 	'comments' => '',
		// 	'help' => '',
		// 	'importable' => 'true',
		// 	'duplicate_merge' => 'disabled',
		// 	'duplicate_merge_dom_value' => '0',
		// 	'audited' => 0,
		// 	'reportable' => 0,
		// 	'len' => 5,
		// ),

		// Thông tin sự kiện phát hành voucher
		'campaign_name' => array(
			'name'       => 'campaign_name',
			'vname'      => 'LBL_CAMPAIGN_NAME',
			'type'       => 'varchar',
			'len'        => 255,
			'default'    => '',
			'importable' => true,
			'reportable' => false,
			'audited' => false,
		),
		'campaign_id' => array(
			'name'       => 'campaign_id',
			'vname'      => 'LBL_CAMPAIGN_ID',
			'type'       => 'campaign_id',
			'dbType'     => 'varchar',
			'len'        => 36,
			'required'   => true,
			'default'    => '',
			'importable' => true,
			'reportable' => false,
			'audited'    => false,
		),

		// Thông tin khách hàng sử dụng voucher
		'account_name' => array(
			'name' => 'account_name',
			'vname' => 'LBL_ACCOUNT_NAME',
			'type' => 'varchar',
			'len' => 64,
			'required' => 0,
			'massupdate' => 0,
			'importable' => 1,
			'audited' => 0,
			'reportable' => 0,
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
		),
		'account_phone' => array(
			'name' => 'account_phone',
			'vname' => 'LBL_ACCOUNT_PHONE',
			'type' => 'varchar',
			'len' => 16,
			'required' => 0,
			'massupdate' => 0,
			'importable' => 1,
			'audited' => 0,
			'reportable' => 0,
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
		),
		'account_email' => array(
			'name' => 'account_email',
			'vname' => 'LBL_ACCOUNT_EMAIL',
			'type' => 'varchar',
			'len' => 30,
			'required' => 0,
			'massupdate' => 0,
			'importable' => 1,
			'audited' => 0,
			'reportable' => 0,
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
		),
		'account_address' => array(
			'name' => 'account_address',
			'vname' => 'LBL_ACCOUNT_ADDRESS',
			'type' => 'varchar',
			'len' => 255,
			'required' => 0,
			'massupdate' => 0,
			'importable' => 1,
			'audited' => 0,
			'reportable' => 0,
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
		),

		// Thông tin booking
		'booking_receive_id' => array(
			'name' => 'booking_receive_id',
			'vname' => '',
			'type' => 'id',
			'len' => 36,
			'importable' => 1,
			'audited' => 0,
			'reportable' => 0,
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => 0,
		),
		'booking' => array(
			'required' => false,
			'source' => 'non-db',
			'name' => 'booking',
			'vname' => 'LBL_BOOKING',
			'type' => 'relate',
			'id_name' => 'booking_receive_id',
			'ext2' => 'EC_Flight_Bookings',
			'module' => 'EC_Flight_Bookings',
			'rname' => 'name',
			'quicksearch' => 'enabled',
			'studio' => 'visible',
		),

		// Số tiền giảm
		'reduce_amount' => array(
			'name' => 'reduce_amount',
			'vname' => 'LBL_REDUCE_AMOUNT',
			'type' => 'int',
			'len' => 11,
			'required' => 0,
			'massupdate' => 0,
			'importable' => 1,
			'audited' => 0,
			'reportable' => 0,
			'disable_num_format' => '',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
		),

		// Số phần trăm giảm
		'reduce_percent' => array(
			'name' => 'reduce_percent',
			'vname' => 'LBL_REDUCE_PERCENT',
			'type' => 'int',
			'len' => 3,
			'required' => 0,
			'massupdate' => 0,
			'importable' => 1,
			'audited' => 0,
			'reportable' => 0,
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
		),

		// Giảm tối đa
		'max_discount' => array(
			'name' => 'reduce_amount',
			'vname' => 'LBL_REDUCE_AMOUNT',
			'type' => 'int',
			'len' => 11,
			'required' => 0,
			'massupdate' => 0,
			'importable' => 1,
			'audited' => 0,
			'reportable' => 0,
			'disable_num_format' => '',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
		),

		// Điều kiện áp dụng
		'condition_voucher' => array(
			'name' => 'condition_voucher',
			'vname' => 'LBL_CONDITION_VOUCHER',
			'type' => 'text',
			'default' => '',
			'required' => 0,
			'massupdate' => 0,
			'importable' => 1,
			'audited' => 0,
			'reportable' => 1,
			'comments' => 'Điều kiện áp dụng voucher',
		),

		// Sắp xếp
		'order_by_no' => array(
			'name' => 'order_by_no',
			'vname' => 'LBL_ORDER_BY_NO',
			'type' => 'int',
			'len' => 10,
			'required' => 0,
			'massupdate' => 0,
			'importable' => 1,
			'audited' => 0,
			'reportable' => 0,
			'disable_num_format' => '',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
		),

		// Website apply
		'website' => array(
			'name' => 'website',
			'vname' => 'LBL_WEBSITE',
			'type' => 'varchar',
			'len' => 50,
			'required' => 0,
			'massupdate' => 0,
			'importable' => 1,
			'audited' => 0,
			'reportable' => 0,
		),

		// 'time_limit' => array(
		// 	'name' => 'time_limit',
		// 	'vname' => 'LBL_TIME_LIMIT',
		// 	'type' => 'datetimecombo',
		// 	'dbType' => 'datetime',
		// 	'importable' => 1,
		// 	'audited' => 0,
		// 	'reportable' => 0,
		// ),
	),
	'indices' => array(),
	'relationships' => array(),
	'optimistic_locking' => true,
	'unified_search' => true,
);

if (!class_exists('VardefManager')) {
	require_once('include/SugarObjects/VardefManager.php');
}
VardefManager::createVardef('EC_Vouchers', 'EC_Vouchers', array('basic', 'assignable', 'security_groups'));
