<?php

$dictionary['EC_Receipt_Voucher'] = array(
    'table' => 'ec_receipt_voucher',
    'audited' => true,
    'inline_edit' => true,
    'duplicate_merge' => true,
    'fields' => 
    array(
        'receipt_type' =>
        array(
            'required' => true,
            'name' => 'receipt_type',
            'vname' => 'LBL_RECEIPT_TYPE',
            'type' => 'enum',
            'massupdate' => 0,
            'default' => 'cash',
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 1,
            'reportable' => 0,
            'len' => 100,
            'options' => 'receipt_type_list',
            'studio' => 'visible',
            'dependency' => false,
        ),
        'tknganhang_id' =>
        array(
            'required' => false,
            'name' => 'tknganhang_id',
            'vname' => '',
            'type' => 'id',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => 0,
            'audited' => 1,
            'reportable' => 0,
            'len' => 36,
        ),
        'tknganhang' =>
        array(
            'required' => false,
            'source' => 'non-db',
            'name' => 'tknganhang',
            'vname' => 'LBL_TKNGANHANG',
            'type' => 'relate',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 1,
            'reportable' => 0,
            'len' => '255',
            'id_name' => 'tknganhang_id',
            'ext2' => 'EC_Bank_Account',
            'module' => 'EC_Bank_Account',
            'rname' => 'name',
            'quicksearch' => 'enabled',
            'studio' => 'visible',
        ),
        'tk_ketoan' =>
        array(
            'required' => false,
            'name' => 'tk_ketoan',
            'vname' => 'LBL_TK_KETOAN',
            'type' => 'varchar',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 1,
            'reportable' => 0,
            'len' => '10',
        ),
        'rv_notes' =>
        array(
            'required' => false,
            'name' => 'rv_notes',
            'vname' => 'LBL_RV_NOTES',
            'type' => 'text',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 1,
            'reportable' => 0,
            'studio' => 'visible',
        ),
        'rv_number' =>
        array(
            'required' => false,
            'name' => 'rv_number',
            'vname' => 'LBL_RV_NUMBER',
            'type' => 'varchar',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 1,
            'reportable' => 0,
            'len' => '100',
        ),
        'amount' =>
        array(
            'required' => true,
            'name' => 'amount',
            'vname' => 'LBL_AMOUNT',
            'type' => 'currency',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => ' ',
            'audited' => 1,
            'reportable' => 0,
            'len' => 26,
        ),
        'account_id_c' =>
        array(
            'required' => false,
            'name' => 'account_id_c',
            'vname' => '',
            'type' => 'id',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => 0,
            'audited' => 1,
            'reportable' => 0,
            'len' => 36,
        ),
        'customer' =>
        array(
            'required' => false,
            'source' => 'non-db',
            'name' => 'customer',
            'vname' => 'LBL_CUSTOMER',
            'type' => 'relate',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 1,
            'reportable' => 0,
            'len' => '255',
            'id_name' => 'account_id_c',
            'ext2' => 'Accounts',
            'module' => 'Accounts',
            'rname' => 'name',
            'quicksearch' => 'enabled',
            'studio' => 'visible',
        ),
        'guest_name' =>
        array(
            'required' => false,
            'name' => 'guest_name',
            'vname' => 'LBL_GUEST_NAME',
            'type' => 'varchar',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 1,
            'reportable' => 0,
            'len' => '255',
        ),
        'guest_phone' =>
        array(
            'required' => false,
            'name' => 'guest_phone',
            'vname' => 'LBL_GUEST_PHONE',
            'type' => 'varchar',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 1,
            'reportable' => 0,
            'len' => '25',
        ),
        'amount_type' =>
        array(
            'required' => false,
            'name' => 'amount_type',
            'vname' => 'LBL_AMOUNT_TYPE',
            'type' => 'enum',
            'massupdate' => 0,
            'default' => 'VND',
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 1,
            'reportable' => 0,
            'len' => 100,
            'options' => 'loaitien_list',
            'studio' => 'visible',
            'dependency' => false,
        ),
        'guest_address' =>
        array(
            'required' => false,
            'name' => 'guest_address',
            'vname' => 'LBL_GUEST_ADDRESS',
            'type' => 'text',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 1,
            'reportable' => 0,
            'studio' => 'visible',
        ),
        'loai_thu' =>
        array(
            'required' => '0',
            'name' => 'loai_thu',
            'vname' => 'LBL_LOAI_THU',
            'type' => 'enum',
            'massupdate' => '0',
            'default' => '1',
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '',
            'audited' => 1,
            'reportable' => 0,
            'len' => 100,
            'options' => 'loai_thu_list',
            'studio' => 'visible',
            'dependency' => false,
        ),
        'booking_id' =>
        array(
            'required' => false,
            'name' => 'booking_id',
            'vname' => '',
            'type' => 'id',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => 0,
            'audited' => 1,
            'reportable' => 0,
            'len' => 36,
        ),
        'booking_name' =>
        array(
            'required' => false,
            'source' => 'non-db',
            'name' => 'booking_name',
            'vname' => 'LBL_BOOKING_NAME',
            'type' => 'relate',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 1,
            'reportable' => 0,
            'len' => '255',
            'id_name' => 'booking_id',
            'ext2' => 'EC_Flight_Bookings',
            'module' => 'EC_Flight_Bookings',
            'rname' => 'name',
            'quicksearch' => 'enabled',
            'studio' => 'visible',
        ),
        'rv_status' =>
        array(
            'required' => false,
            'name' => 'rv_status',
            'vname' => 'LBL_RV_STATUS',
            'type' => 'enum',
            'massupdate' => 0,
            'default' => '0',
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 1,
            'reportable' => 0,
            'len' => 100,
            'options' => 'receipt_voucher_status_list',
            'studio' => 'visible',
            'dependency' => false,
        ),
        'ngaychungtu' =>
        array(
            'required' => '1',
            'name' => 'ngaychungtu',
            'vname' => 'LBL_NGAYCHUNGTU',
            'type' => 'date',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => ' ',
            'audited' => 1,
            'reportable' => 0,
            'display_default' => 'now',
        ),
        'amount_converted' =>
        array(
            'required' => false,
            'name' => 'amount_converted',
            'vname' => 'LBL_AMOUNT_CONVERTED',
            'type' => 'currency',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => ' ',
            'audited' => 1,
            'reportable' => 0,
            'len' => 26,
        ),
        'exchange_rate' =>
        array(
            'required' => '0',
            'name' => 'exchange_rate',
            'vname' => 'LBL_EXCHANGE_RATE',
            'type' => 'int',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 1,
            'reportable' => 0,
            'len' => '11',
            'disable_num_format' => '',
        ),
        'is_margin' =>
        array(
            'required' => false,
            'name' => 'is_margin',
            'vname' => 'LBL_IS_MARGIN',
            'type' => 'bool',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '',
            'audited' => 1,
            'reportable' => 0,
            'len' => '1',
            'default' => '0',
        ),
        'ngayhachtoan' =>
        array(
            'required' => '1',
            'name' => 'ngayhachtoan',
            'vname' => 'LBL_NGAYHACHTOAN',
            'type' => 'datetimecombo',
            'dbType' => 'datetime',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '',
            'audited' => 1,
            'reportable' => 0,
        ),
        'bought_amount' =>
        array(
            'required' => false,
            'name' => 'bought_amount',
            'vname' => 'LBL_BOUGHT_AMOUNT',
            'type' => 'currency',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => ' ',
            'audited' => 1,
            'reportable' => 0,
            'len' => 26,
        ),
        'aircode' =>
        array(
            'required' => false,
            'name' => 'aircode',
            'vname' => 'LBL_AIRCODE',
            'type' => 'enum',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 1,
            'reportable' => 0,
            'len' => 3,
            'options' => 'aircode_list',
            'studio' => 'visible',
            'dependency' => false,
        ),
        'supplier_id' =>
        array(
            'required' => false,
            'name' => 'supplier_id',
            'vname' => '',
            'type' => 'id',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => 0,
            'audited' => 1,
            'reportable' => 0,
            'len' => 36,
        ),
        'supplier' =>
        array(
            'required' => false,
            'source' => 'non-db',
            'name' => 'supplier',
            'vname' => 'LBL_SUPPLIER',
            'type' => 'relate',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 1,
            'reportable' => 0,
            'len' => '255',
            'id_name' => 'supplier_id',
            'ext2' => 'Accounts',
            'module' => 'Accounts',
            'rname' => 'name',
            'quicksearch' => 'enabled',
            'studio' => 'visible',
        ),
        'supplier2_id' =>
        array(
            'required' => false,
            'name' => 'supplier2_id',
            'vname' => '',
            'type' => 'id',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => 0,
            'audited' => 1,
            'reportable' => 0,
            'len' => 36,
        ),
        'supplier2' =>
        array(
            'required' => false,
            'source' => 'non-db',
            'name' => 'supplier2',
            'vname' => 'LBL_SUPPLIER2',
            'type' => 'relate',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 1,
            'reportable' => 0,
            'len' => '255',
            'id_name' => 'supplier2_id',
            'ext2' => 'Accounts',
            'module' => 'Accounts',
            'rname' => 'name',
            'quicksearch' => 'enabled',
            'studio' => 'visible',
        ),
        'supplier3_id' =>
        array(
            'required' => false,
            'name' => 'supplier3_id',
            'vname' => '',
            'type' => 'id',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => 0,
            'audited' => 1,
            'reportable' => 0,
            'len' => 36,
        ),
        'supplier3' =>
        array(
            'required' => false,
            'source' => 'non-db',
            'name' => 'supplier3',
            'vname' => 'LBL_SUPPLIER3',
            'type' => 'relate',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 1,
            'reportable' => 0,
            'len' => '255',
            'id_name' => 'supplier3_id',
            'ext2' => 'Accounts',
            'module' => 'Accounts',
            'rname' => 'name',
            'quicksearch' => 'enabled',
            'studio' => 'visible',
        ),
        'bought_amount2' =>
        array(
            'required' => false,
            'name' => 'bought_amount2',
            'vname' => 'LBL_BOUGHT_AMOUNT2',
            'type' => 'currency',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => ' ',
            'audited' => 1,
            'reportable' => 0,
            'len' => 26,
        ),
        'bought_amount3' =>
        array(
            'required' => false,
            'name' => 'bought_amount3',
            'vname' => 'LBL_BOUGHT_AMOUNT3',
            'type' => 'currency',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => ' ',
            'audited' => 1,
            'reportable' => 0,
            'len' => 26,
        ),
        'agent_id' =>
        array(
            'required' => false,
            'name' => 'agent_id',
            'vname' => '',
            'type' => 'id',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => 0,
            'audited' => 1,
            'reportable' => 0,
            'len' => 36,
        ),
        'agent' =>
        array(
            'required' => false,
            'source' => 'non-db',
            'name' => 'agent',
            'vname' => 'LBL_AGENT',
            'type' => 'relate',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 1,
            'reportable' => 0,
            'len' => '255',
            'id_name' => 'agent_id',
            'ext2' => 'Accounts',
            'module' => 'Accounts',
            'rname' => 'name',
            'quicksearch' => 'enabled',
            'studio' => 'visible',
        ),
        'location' =>
        array(
            'required' => false,
            'name' => 'location',
            'vname' => 'LBL_LOCATION',
            'type' => 'enum',
            'massupdate' => 0,
            'default' => '',
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 1,
            'reportable' => 0,
            'len' => 100,
            'options' => 'location_list',
            'studio' => 'visible',
            'dependency' => false,
        ),
        'com_location_id' =>
        array(
            'required' => false,
            'name' => 'com_location_id',
            'vname' => '',
            'type' => 'id',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => 0,
            'audited' => 1,
            'reportable' => 0,
            'len' => 36,
        ),
        'com_location' =>
        array(
            'required' => false,
            'source' => 'non-db',
            'name' => 'com_location',
            'vname' => 'LBL_COM_LOCATION',
            'type' => 'relate',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 1,
            'reportable' => 0,
            'len' => '255',
            'id_name' => 'com_location_id',
            'ext2' => 'EC_Location',
            'module' => 'EC_Location',
            'rname' => 'name',
            'quicksearch' => 'enabled',
            'studio' => 'visible',
        ),
        'sell_amount' =>
        array(
            'required' => false,
            'name' => 'sell_amount',
            'vname' => 'LBL_SELL_AMOUNT',
            'type' => 'currency',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => ' ',
            'audited' => 1,
            'reportable' => 0,
            'len' => 26,
        ),
        'sell_amount2' =>
        array(
            'required' => false,
            'name' => 'sell_amount2',
            'vname' => 'LBL_SELL_AMOUNT2',
            'type' => 'currency',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => ' ',
            'audited' => 1,
            'reportable' => 0,
            'len' => 26,
        ),
        'sell_amount3' =>
        array(
            'required' => false,
            'name' => 'sell_amount3',
            'vname' => 'LBL_SELL_AMOUNT3',
            'type' => 'currency',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => ' ',
            'audited' => 1,
            'reportable' => 0,
            'len' => 26,
        ),
        'employee_id' =>
        array(
            'required' => false,
            'name' => 'employee_id',
            'vname' => '',
            'type' => 'id',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => 0,
            'audited' => 1,
            'reportable' => 0,
            'len' => 36,
        ),
        'employee_name' =>
        array(
            'required' => false,
            'source' => 'non-db',
            'name' => 'employee_name',
            'vname' => 'LBL_EMPLOYEE_NAME',
            'type' => 'relate',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 1,
            'reportable' => 0,
            'len' => '255',
            'id_name' => 'employee_id',
            'ext2' => 'Users',
            'module' => 'Users',
            'rname' => 'name',
            'quicksearch' => 'enabled',
            'studio' => 'visible',
        ),
        // công nợ
        'is_debt' =>
        array(
            'required' => false,
            'name' => 'is_debt',
            'vname' => 'LBL_IS_DEBT',
            'type' => 'bool',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '',
            'audited' => 1,
            'reportable' => 0,
            'len' => '1',
            'default' => '0',
        ),
        // giá mua chưa VAT 1
        'bought_amount_no_vat' =>
        array(
            'required' => false,
            'name' => 'bought_amount_no_vat',
            'vname' => 'LBL_BOUGHT_AMOUNT_NO_VAT',
            'type' => 'currency',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => ' ',
            'audited' => 1,
            'reportable' => 0,
            'len' => 26,
        ),
        // giá mua chưa VAT 2
        'bought_amount_no_vat2' =>
        array(
            'required' => false,
            'name' => 'bought_amount_no_vat2',
            'vname' => 'LBL_BOUGHT_AMOUNT_NO_VAT2',
            'type' => 'currency',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => ' ',
            'audited' => 1,
            'reportable' => 0,
            'len' => 26,
        ),
        // giá mua chưa VAT 3
        'bought_amount_no_vat3' =>
        array(
            'required' => false,
            'name' => 'bought_amount_no_vat3',
            'vname' => 'LBL_BOUGHT_AMOUNT_NO_VAT3',
            'type' => 'currency',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => ' ',
            'audited' => 1,
            'reportable' => 0,
            'len' => 26,
        ),
        // vat giá mua
        'vat_bought_amount' =>
        array(
            'required' => false,
            'name' => 'vat_bought_amount',
            'vname' => 'LBL_VAT_BOUGHT_AMOUNT',
            'type' => 'currency',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => ' ',
            'audited' => 1,
            'reportable' => 0,
            'len' => 26,
        ),
        // vat giá mua 2
        'vat_bought_amount2' =>
        array(
            'required' => false,
            'name' => 'vat_bought_amount2',
            'vname' => 'LBL_VAT_BOUGHT_AMOUNT2',
            'type' => 'currency',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => ' ',
            'audited' => 1,
            'reportable' => 0,
            'len' => 26,
        ),
        // vat giá mua 3
        'vat_bought_amount3' =>
        array(
            'required' => false,
            'name' => 'vat_bought_amount3',
            'vname' => 'LBL_VAT_BOUGHT_AMOUNT3',
            'type' => 'currency',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => ' ',
            'audited' => 1,
            'reportable' => 0,
            'len' => 26,
        ),
        // số vé
        'ticket_number' =>
        array(
            'required' => false,
            'name' => 'ticket_number',
            'vname' => 'LBL_TICKET_NUMBER',
            'type' => 'varchar',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 1,
            'reportable' => 0,
            'len' => 100,
        ),
        // số vé 2
        'ticket_number2' =>
        array(
            'required' => false,
            'name' => 'ticket_number2',
            'vname' => 'LBL_TICKET_NUMBER2',
            'type' => 'varchar',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 1,
            'reportable' => 0,
            'len' => 100,
        ),
        // số vé 3
        'ticket_number3' =>
        array(
            'required' => false,
            'name' => 'ticket_number3',
            'vname' => 'LBL_TICKET_NUMBER3',
            'type' => 'varchar',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 1,
            'reportable' => 0,
            'len' => 100,
        ),
        // 'is_sent_tele' =>
        // array(
        //     'required' => false,
        //     'name' => 'is_sent_tele',
        //     'vname' => 'LBL_IS_SENT_TELE',
        //     'type' => 'bool',
        //     'massupdate' => 0,
        //     'comments' => '',
        //     'help' => '',
        //     'importable' => 'true',
        //     'duplicate_merge' => 'disabled',
        //     'duplicate_merge_dom_value' => '',
        //     'audited' => 0,
        //     'reportable' => 0,
        //     'len' => '1',
        //     'default' => '0',
        // ),

        // Custom user - giao thực phẩm (sữa)
        'delivery_man_id' => array(
            'name'       => 'delivery_man_id',
            'vname'      => '',
            'type'       => 'id',
            'len'        => 36,
            'default'    => '',
            'importable' => true,
            'reportable' => false,
            
        ),
        'delivery_man' => array(
            'name'       => 'delivery_man',
            'vname'      => 'LBL_DELIVERY_MAN',
            'type'       => 'relate',
            'source'     => 'non-db',
            'importable' => true,
            'reportable' => false,
            'id_name'   => 'delivery_man_id',
            'ext2'      => 'Users',
            'module'    => 'Users',
            'rname'     => 'name',
            'studio'    => 'visible',
            'quicksearch' => 'enabled',
            'audited' => 1,
        ),

    ),
    'indices' =>
    array(
        0 => array('name' => 'idx_rv_name', 'type' => 'index', 'fields' => array('name')),
        1 => array('name' => 'idx_rv_del', 'type' => 'index', 'fields' => array('deleted')),
        2 => array('name' => 'idx_rv_assign', 'type' => 'index', 'fields' => array('assigned_user_id')),
        3 => array('name' => 'idx_rv_booking', 'type' => 'index', 'fields' => array('booking_id')),
        4 => array('name' => 'idx_rv_tknganhang', 'type' => 'index', 'fields' => array('tknganhang_id')),
        5 => array('name' => 'idx_rv_customer', 'type' => 'index', 'fields' => array('account_id_c')),
        6 => array('name' => 'idx_rv_rtype', 'type' => 'index', 'fields' => array('receipt_type')),
        7 => array('name' => 'idx_rv_status', 'type' => 'index', 'fields' => array('rv_status')),
        8 => array('name' => 'idx_rv_loaithu', 'type' => 'index', 'fields' => array('loai_thu')),
        9 => array('name' => 'idx_rv_airc', 'type' => 'index', 'fields' => array('aircode')),
        10 => array('name' => 'idx_rv_su2', 'type' => 'index', 'fields' => array('supplier2_id')),
        11 => array('name' => 'idx_rv_su3', 'type' => 'index', 'fields' => array('supplier3_id')),
        12 => array('name' => 'idx_rv_agent', 'type' => 'index', 'fields' => array('agent_id')),
        13 => array('name' => 'idx_rv_location', 'type' => 'index', 'fields' => array('location')),
        14 => array('name' => 'idx_rv_comlocation', 'type' => 'index', 'fields' => array('com_location_id')),
    ),
    'relationships' => array(
        'receiptvoucher_booking' =>
        array(
            'lhs_module' => 'EC_Flight_Bookings',
            'lhs_table' => 'ec_flight_bookings',
            'lhs_key' => 'id',
            'rhs_module' => 'EC_Receipt_Voucher',
            'rhs_table' => 'ec_receipt_voucher',
            'rhs_key' => 'booking_id',
            'relationship_type' => 'one-to-many',
        ),
        'receiptvoucher_tknganhang' =>
        array(
            'lhs_module' => 'EC_Bank_Account',
            'lhs_table' => 'ec_bank_account',
            'lhs_key' => 'id',
            'rhs_module' => 'EC_Receipt_Voucher',
            'rhs_table' => 'ec_receipt_voucher',
            'rhs_key' => 'tknganhang_id',
            'relationship_type' => 'one-to-many',
        ),
        'receiptvoucher_customer' =>
        array(
            'lhs_module' => 'Accounts',
            'lhs_table' => 'accounts',
            'lhs_key' => 'id',
            'rhs_module' => 'EC_Receipt_Voucher',
            'rhs_table' => 'ec_receipt_voucher',
            'rhs_key' => 'account_id_c',
            'relationship_type' => 'one-to-many',
        ),
    ),
    'optimistic_locking' => true,
    'unified_search' => true,
);
if (!class_exists('VardefManager')) {
        require_once('include/SugarObjects/VardefManager.php');
}
VardefManager::createVardef('EC_Receipt_Voucher', 'EC_Receipt_Voucher', array('basic','assignable','security_groups'));
