<?php

$dictionary['EC_Employee_Salary'] = array(
    'table' => 'ec_employee_salary',
    'audited' => true,
    'inline_edit' => true,
    'duplicate_merge' => true,
    'fields' => array(
        'currency_id' =>
        array(
            'required' => false,
            'name' => 'currency_id',
            'vname' => 'LBL_CURRENCY',
            'type' => 'id',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => 0,
            'audited' => 0,
            'reportable' => 0,
            'len' => 36,
            'studio' => 'visible',
            'function' =>
            array(
                'name' => 'getCurrencyDropDown',
                'returns' => 'html',
            ),
        ),
        'month' =>
        array(
            'required' => false,
            'name' => 'month',
            'vname' => 'LBL_MONTH',
            'type' => 'int',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '',
            'audited' => 0,
            'reportable' => 0,
            'len' => '2',
            'disable_num_format' => '1',
            'validation' =>
            array(
                'type' => 'range',
                'min' => '1',
                'max' => '12',
            ),
        ),
        'year' =>
        array(
            'required' => false,
            'name' => 'year',
            'vname' => 'LBL_YEAR',
            'type' => 'int',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '',
            'audited' => 0,
            'reportable' => 0,
            'len' => '11',
            'disable_num_format' => '1',
        ),
        'basic_salary' =>
        array(
            'required' => false,
            'name' => 'basic_salary',
            'vname' => 'LBL_BASIC_SALARY',
            'type' => 'currency',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '',
            'audited' => 0,
            'reportable' => 0,
            'len' => 26,
        ),
        'efficient_wage' =>
        array(
            'required' => false,
            'name' => 'efficient_wage',
            'vname' => 'LBL_EFFICIENT_WAGE',
            'type' => 'currency',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '',
            'audited' => 0,
            'reportable' => 0,
            'len' => 26,
        ),
        'gas_allowance' =>
        array(
            'required' => false,
            'name' => 'gas_allowance',
            'vname' => 'LBL_GAS_ALLOWANCE',
            'type' => 'currency',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '',
            'audited' => 0,
            'reportable' => 0,
            'len' => 26,
        ),
        'lunch_allowance' =>
        array(
            'required' => false,
            'name' => 'lunch_allowance',
            'vname' => 'LBL_LUNCH_ALLOWANCE',
            'type' => 'currency',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '',
            'audited' => 0,
            'reportable' => 0,
            'len' => 26,
        ),
        'tele_allowance' =>
        array(
            'required' => false,
            'name' => 'tele_allowance',
            'vname' => 'LBL_TELE_ALLOWANCE',
            'type' => 'currency',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '',
            'audited' => 0,
            'reportable' => 0,
            'len' => 26,
        ),
        'responsible_allowance' =>
        array(
            'required' => false,
            'name' => 'responsible_allowance',
            'vname' => 'LBL_RESPONSIBLE_ALLOWANCE',
            'type' => 'currency',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '',
            'audited' => 0,
            'reportable' => 0,
            'len' => 26,
        ),
        'seniority_allowance' =>
        array(
            'required' => false,
            'name' => 'seniority_allowance',
            'vname' => 'LBL_SENIORITY_ALLOWANCE',
            'type' => 'currency',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '',
            'audited' => 0,
            'reportable' => 0,
            'len' => 26,
        ),
        'other_allowance1' =>
        array(
            'required' => false,
            'name' => 'other_allowance1',
            'vname' => 'LBL_OTHER_ALLOWANCE1',
            'type' => 'currency',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '',
            'audited' => 0,
            'reportable' => 0,
            'len' => 26,
        ),
        'other_allowance2' =>
        array(
            'required' => false,
            'name' => 'other_allowance2',
            'vname' => 'LBL_OTHER_ALLOWANCE2',
            'type' => 'currency',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '',
            'audited' => 0,
            'reportable' => 0,
            'len' => 26,
        ),
        'social_insurance' =>
        array(
            'required' => false,
            'name' => 'social_insurance',
            'vname' => 'LBL_SOCIAL_INSURANCE',
            'type' => 'currency',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '',
            'audited' => 0,
            'reportable' => 0,
            'len' => 26,
        ),
        'minus' =>
        array(
            'required' => false,
            'name' => 'minus',
            'vname' => 'LBL_MINUS',
            'type' => 'currency',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '',
            'audited' => 0,
            'reportable' => 0,
            'len' => 26,
        ),
        'effort' =>
        array(
            'required' => false,
            'name' => 'effort',
            'vname' => 'LBL_EFFORT',
            'type' => 'currency',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '',
            'audited' => 0,
            'reportable' => 0,
            'len' => 26,
        ),
        'sales' =>
        array(
            'required' => false,
            'name' => 'sales',
            'vname' => 'LBL_SALES',
            'type' => 'currency',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '',
            'audited' => 0,
            'reportable' => 0,
            'len' => 26,
        ),
        // cú đêm
        'overnight' =>
        array(
            'required' => false,
            'name' => 'overnight',
            'vname' => 'LBL_OVERNIGHT',
            'type' => 'currency',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '',
            'audited' => 0,
            'reportable' => 0,
            'len' => 26,
        ),
        // ds của bk cú đêm đc tính 20k
        'profit_overnight' =>
        array(
            'required' => false,
            'name' => 'profit_overnight',
            'vname' => 'LBL_PROFIT_OVERNIGHT',
            'type' => 'currency',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '',
            'audited' => 0,
            'reportable' => 0,
            'len' => 26,
        ),
        // giao vé
        'delivery' =>
        array(
            'required' => false,
            'name' => 'delivery',
            'vname' => 'LBL_DELIVERY',
            'type' => 'currency',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '',
            'audited' => 0,
            'reportable' => 0,
            'len' => 26,
        ),
        // lương thực nhận
        'actual_salary' =>
        array(
            'required' => false,
            'name' => 'actual_salary',
            'vname' => 'LBL_ACTUAL_SALARY',
            'type' => 'currency',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '',
            'audited' => 0,
            'reportable' => 0,
            'len' => 26,
        ),
        'is_approved' =>
        array(
            'required' => false,
            'name' => 'is_approved',
            'vname' => 'LBL_IS_APPROVED',
            'type' => 'bool',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '',
            'audited' => 1,
            'reportable' => 0,
            'len' => '1',
            'default' => '0',
        ),
        'approved_by' =>
        array(
            'required' => false,
            'name' => 'approved_by',
            'vname' => '',
            'type' => 'id',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => 0,
            'audited' => 0,
            'reportable' => 0,
            'len' => 36,
        ),
        'approved_date' =>
        array(
            'required' => false,
            'name' => 'approved_date',
            'vname' => 'LBL_APPROVED_DATE',
            'type' => 'datetime',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '',
            'audited' => 1,
            'reportable' => 0,
        ),
        'extra_amount' =>
        array(
            'required' => false,
            'name' => 'extra_amount',
            'vname' => 'LBL_EXTRA_AMOUNT',
            'type' => 'currency',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '',
            'audited' => 0,
            'reportable' => 0,
            'len' => 26,
        ),
        'working_days' => array(
            'required' => false,
            'name' => 'working_days',
            'vname' => 'LBL_WORKING_DAYS',
            'type' => 'float',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 0,
            'reportable' => 0,
            'len' => '11',
            'disable_num_format' => 0,
            'precision' => '2',
        ),
        'ot_days' => array(
            'required' => false,
            'name' => 'ot_days',
            'vname' => 'LBL_OT_DAYS',
            'type' => 'float',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 0,
            'reportable' => 0,
            'len' => '11',
            'disable_num_format' => 0,
            'precision' => '2',
        ),
        'no_paid_days' => array(
            'required' => false,
            'name' => 'no_paid_days',
            'vname' => 'LBL_NO_PAID_DAYS',
            'type' => 'float',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 0,
            'reportable' => 0,
            'len' => '11',
            'disable_num_format' => 0,
            'precision' => '1',
        ),
        // làm việc online
        'is_online' => array(
            'required' => false,
            'name' => 'is_online',
            'vname' => 'LBL_IS_ONLINE',
            'type' => 'bool',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 0,
            'reportable' => 0,
        ),
        // cột dự phòng
        'backup_fund' =>
        array(
            'required' => false,
            'name' => 'backup_fund',
            'vname' => 'LBL_BACKUP_FUND',
            'type' => 'currency',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '',
            'audited' => 0,
            'reportable' => 0,
            'len' => 26,
        ),
        'minus_income' =>
        array(
            'required' => false,
            'name' => 'minus_income',
            'vname' => 'LBL_MINUS_INCOME',
            'type' => 'currency',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '',
            'audited' => 0,
            'reportable' => 0,
            'len' => 26,
        ),
        'minus_amount' =>
        array(
            'required' => false,
            'name' => 'minus_amount',
            'vname' => 'LBL_MINUS_AMOUNT',
            'type' => 'currency',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '',
            'audited' => 0,
            'reportable' => 0,
            'len' => 26,
        ),
        // duyệt không trừ
        'not_minus_income' => array(
            'required' => false,
            'name' => 'not_minus_income',
            'vname' => 'LBL_NOT_MINUS_INCOME',
            'type' => 'bool',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 0,
            'reportable' => 0,
        ),
    ),
    'relationships' => array (
),
    'optimistic_locking' => true,
    'unified_search' => true,
);
if (!class_exists('VardefManager')) {
        require_once('include/SugarObjects/VardefManager.php');
}
VardefManager::createVardef('EC_Employee_Salary', 'EC_Employee_Salary', array('basic','assignable','security_groups'));
