<?php

$dictionary['EC_Report_Weekly'] = array(
    'table' => 'ec_report_weekly',
    'audited' => true,
    'inline_edit' => true,
    'duplicate_merge' => true,
    'fields' => array(
        'user_id' =>
        array(
            'required' => true,
            'name' => 'user_id',
            'vname' => 'LBL_USER_ID',
            'type' => 'varchar',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '',
            'audited' => 0,
            'reportable' => 0,
            'len' => '255',
        ),
        'last_name' =>
        array(
            'required' => false,
            'name' => 'last_name',
            'vname' => 'LBL_LAST_NAME',
            'type' => 'varchar',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '',
            'audited' => 0,
            'reportable' => 0,
            'len' => '255',
        ),
        'user_name' =>
        array(
            'required' => false,
            'name' => 'user_name',
            'vname' => 'LBL_USER_NAME',
            'type' => 'varchar',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '',
            'audited' => 0,
            'reportable' => 0,
            'len' => '255',
        ),
        'bk_created' => array(
            'name'       => 'bk_created',
            'vname'      => 'LBL_BK_CREATED',
            'type'       => 'int',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'default'    => 0,
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '',
            'importable' => true,
            'reportable' => false,
            'audited'    => 0,
            'len' => 26,
        ),
        'bk_called' => array(
            'name'       => 'bk_called',
            'vname'      => 'LBL_BK_CALLED',
            'type'       => 'int',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'default'    => 0,
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '',
            'importable' => true,
            'reportable' => false,
            'audited'    => 0,
            'len' => 26,
        ),
        'bk_paying' => array(
            'name'       => 'bk_paying',
            'vname'      => 'LBL_BK_PAYING',
            'type'       => 'int',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'default'    => 0,
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '',
            'importable' => true,
            'reportable' => false,
            'audited'    => 0,
            'len' => 26,
        ),
        'bk_confirmed' => array(
            'name'       => 'bk_confirmed',
            'vname'      => 'LBL_BK_CONFIRMED',
            'type'       => 'int',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'default'    => 0,
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '',
            'importable' => true,
            'reportable' => false,
            'audited'    => 0,
            'len' => 26,
        ),
        'bk_printed' => array(
            'name'       => 'bk_printed',
            'vname'      => 'LBL_BK_PRINTED',
            'type'       => 'int',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'default'    => 0,
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '',
            'importable' => true,
            'reportable' => false,
            'audited'    => 0,
            'len' => 26,
        ),
        'bk_completed' => array(
            'name'       => 'bk_completed',
            'vname'      => 'LBL_BK_COMPLETED',
            'type'       => 'int',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'default'    => 0,
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '',
            'importable' => true,
            'reportable' => false,
            'audited'    => 0,
            'len' => 26,
        ),
        'bk_cancelled' => array(
            'name'       => 'bk_cancelled',
            'vname'      => 'LBL_BK_COMPLETED',
            'type'       => 'int',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'default'    => 0,
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '',
            'importable' => true,
            'reportable' => false,
            'audited'    => 0,
            'len' => 26,
        ),
        'total_qty' => array(
            'name'       => 'total_qty',
            'vname'      => 'LBL_TOTAL_QTY',
            'type'       => 'int',
            'default'    => 0,
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '',
            'importable' => true,
            'reportable' => false,
            'audited' => 1,
            'len' => 26,
        ),
        'total_ticket' => array(
            'name'       => 'total_ticket',
            'vname'      => 'LBL_TOTAL_TICKET',
            'type'       => 'int',
            'default'    => 0,
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '',
            'importable' => true,
            'reportable' => false,
            'audited' => 1,
            'len' => 26,
        ),
        'total_sales' =>
        array(
            'required' => '1',
            'name' => 'total_sales',
            'vname' => 'LBL_TOTAL_SALES',
            'type' => 'currency',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '',
            'audited' => 0,
            'reportable' => 0,
            'len' => 26,
        ),
        'advertisement_cost' =>
        array(
            'required' => '1',
            'name' => 'advertisement_cost',
            'vname' => 'LBL_ADVERTISEMENT_COST',
            'type' => 'currency',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '',
            'audited' => 0,
            'reportable' => 0,
            'len' => 26,
        ),
        'from_date' =>
        array(
            'required' => false,
            'name' => 'from_date',
            'vname' => 'LBL_FROM_DATE',
            'type' => 'date',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '',
            'audited' => 0,
            'reportable' => 0,
        ),
        'to_date' =>
        array(
            'required' => false,
            'name' => 'to_date',
            'vname' => 'LBL_TO_DATE',
            'type' => 'date',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '',
            'audited' => 0,
            'reportable' => 0,
        ),
        'report_date' =>
        array(
            'required' => false,
            'name' => 'report_date',
            'vname' => 'LBL_REPORT_DATE',
            'type' => 'date',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '',
            'audited' => 0,
            'reportable' => 0,
        ),
    ),
    'relationships' => array(),
    'optimistic_locking' => true,
    'unified_search' => true,
);
if (!class_exists('VardefManager')) {
    require_once('include/SugarObjects/VardefManager.php');
}
VardefManager::createVardef('EC_Report_Weekly', 'EC_Report_Weekly', array('basic', 'assignable', 'security_groups'));
