<?php

$dictionary['EC_Outbound_Phone'] = array(
    'table' => 'ec_outbound_phone',
    'audited' => true,
    'inline_edit' => true,
    'duplicate_merge' => true,
    'fields' => array(
        'format_phone' => array(
            'required'  => false,
            'name'      => 'format_phone',
            'vname'     => 'LBL_FORMAT_PHONE',
            'type'      => 'varchar',
            'len'       => 50,
            'comment'   => '',
            'importable' => 'required',
            'audited'   => true,
            'massupdate' => false,
        ),
        'network_provider' => array(
            'required'  => true,
            'name'      => 'network_provider',
            'vname'     => 'LBL_NETWORK_PROVIDER',
            'type'      => 'enum',
            'len'       => 20,
            'options'   => 'network_provider_list',
            'comment'   => 'Nhà mạng (Vinaphone, Mobiphone, Viettel,...)',
            'importable' => 'required',
            'default'   => '',
            'audited'   => true,
        ),
        'status' => array(
            'required'  => false,
            'name'      => 'status',
            'vname'     => 'LBL_STATUS',
            'type'      => 'enum',
            'len'       => 20,
            'options'   => 'outbound_phone_status_list',
            'comment'   => '',
            'importable' => 'required',
            'default'   => '',
            'audited'   => true,
        ),
        'proxy' => array(
            'required'  => false,
            'name'      => 'proxy',
            'vname'     => 'LBL_PROXY',
            'type'      => 'varchar',
            'len'       => 50,
            'comment'   => 'IP:Port SIP Trunk. Cú pháp: 125.235.38.182:55555',
            'importable' => 'required',
            'audited'   => true,
        ),
        'brand_name' => array(
            'required'  => false,
            'name'      => 'brand_name',
            'vname'     => 'LBL_BRAND_NAME',
            'type'      => 'varchar',
            'len'       => 50,
            'comment'   => 'Brandname hiển thị',
            'importable' => 'required',
            'audited'   => true,
            'massupdate' => true,
        ),
        'website' => array(
            'required'  => false,
            'name'      => 'website',
            'vname'     => 'LBL_WEBSITE',
            'type'      => 'varchar',
            'len'       => 50,
            'comment'   => '',
            'importable' => 'required',
            'audited'   => true,
            'default' => 'timchuyenbay.com',
            'massupdate' => true,
        ),
        'label' => array(
            'required'  => false,
            'name'      => 'label',
            'vname'     => 'LBL_LABEL',
            'type'      => 'varchar',
            'len'       => 50,
            'comment'   => 'Nhãn hiển thị',
            'audited'   => true,
            'default' => '',
            'massupdate' => true,
        ),
        'only_inbound' => array(
            'required'  => false,
            'name'      => 'only_inbound',
            'vname'     => 'LBL_ONLY_INBOUND',
            'type'      => 'bool',
            'massupdate' => false,
            'comments' => 'Chỉ dùng để khách gọi vào. Không sử dụng để random số gọi ra',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '',
            'audited' => 1,
            'reportable' => 0,
            'len' => '1',
            'default' => '0',
            'massupdate' => true,
        ),
        'round_robin' => array(
            'required'  => false,
            'name'      => 'round_robin',
            'vname'     => 'LBL_ROUND_ROBIN',
            'type'      => 'bool',
            'massupdate' => false,
            'comments' => 'Đánh dấu số dùng để gọi ra. PBX sẽ get thống tin list số round_robin và dùng nó để gọi ra nếu agent KHÔNG chủ động chọn số gọi ra',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '',
            'audited' => 1,
            'reportable' => 0,
            'len' => '1',
            'default' => '0',
        ),
    ),
    'relationships' => array(),
    'optimistic_locking' => true,
    'unified_search' => true,
);
if (!class_exists('VardefManager')) {
    require_once('include/SugarObjects/VardefManager.php');
}
VardefManager::createVardef('EC_Outbound_Phone', 'EC_Outbound_Phone', array('basic', 'assignable', 'security_groups'));
