<?php
$dictionary['EC_NhomTaiKhoan'] = array(
    'table' => 'ec_nhomtaikhoan',
    'audited' => true,
    'inline_edit' => true,
    'duplicate_merge' => true,
    'fields' => array(
        'tinhchat' => array(
            'required' => '1',
            'name' => 'tinhchat',
            'vname' => 'LBL_TINHCHAT',
            'type' => 'enum',
            'massupdate' => 0,
            'default' => 'DuNo',
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => ' ',
            'audited' => 1,
            'reportable' => 0,
            'len' => 100,
            'options' => 'tinhchat_list',
            'studio' => 'visible',
            'dependency' => false,
        ),

        'manhom' => array(
            'required' => true,
            'name' => 'manhom',
            'vname' => 'LBL_MANHOM',
            'type' => 'varchar',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => ' ',
            'audited' => 1,
            'reportable' => 0,
            'len' => '10',
        ),

        'loaidoituong' => array(
            'required' => false,
            'name' => 'loaidoituong',
            'vname' => 'LBL_LOAIDOITUONG',
            'type' => 'enum',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => ' ',
            'audited' => 1,
            'reportable' => 0,
            'len' => 100,
            'options' => 'loaidoituong_list',
            'studio' => 'visible',
            'dependency' => false,
        ),

        'chitiettheo' => array(
            'required' => false,
            'name' => 'chitiettheo',
            'vname' => 'LBL_CHITIETTHEO',
            'type' => 'bool',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => ' ',
            'audited' => 1,
            'reportable' => 0,
            'len' => '255',
        ),

        'ds_chitiettheo' => array(
            'required' => false,
            'name' => 'ds_chitiettheo',
            'vname' => 'LBL_DS_CHITIETTHEO',
            'type' => 'enum',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => ' ',
            'audited' => 1,
            'reportable' => 0,
            'len' => 100,
            'options' => 'ds_chitiettheo_list',
            'studio' => 'visible',
            'dependency' => false,
        ),
    ),
    'relationships' => array(),
    'optimistic_locking' => true,
    'unified_search' => true,
);

if (!class_exists('VardefManager')) {
    require_once('include/SugarObjects/VardefManager.php');
}
VardefManager::createVardef('EC_NhomTaiKhoan', 'EC_NhomTaiKhoan', array('basic', 'assignable', 'security_groups'));
