<?php


$dictionary['EC_Request_Flight'] = array(
    'table' => 'ec_request_flight',
    'audited' => true,
    'inline_edit' => true,
    'duplicate_merge' => true,
    'fields' => array(
        'request_type' =>
        array(
          'required' => '1',
          'name' => 'request_type',
          'vname' => 'LBL_REQUEST_TYPE',
          'type' => 'enum',
          'massupdate' => 0,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => ' ',
          'audited' => 1,
          'reportable' => 0,
          'len' => 100,
          'options' => 'request_type_list',
          'studio' => 'visible',
          'dependency' => false,
        ),
        'booking_id' =>
        array(
          'required' => false,
          'name' => 'booking_id',
          'vname' => '',
          'type' => 'id',
          'massupdate' => 0,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => 0,
          'audited' => 0,
          'reportable' => 0,
          'len' => 36,
        ),
        'booking' =>
        array(
          'required' => false,
          'source' => 'non-db',
          'name' => 'booking',
          'vname' => 'LBL_BOOKING',
          'type' => 'relate',
          'massupdate' => 0,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => ' ',
          'audited' => 1,
          'reportable' => 0,
          'len' => '255',
          'id_name' => 'booking_id',
          'ext2' => 'EC_Flight_Bookings',
          'module' => 'EC_Flight_Bookings',
          'rname' => 'name',
          'quicksearch' => 'enabled',
          'studio' => 'visible',
        ),
        'contact_name' =>
        array(
          'required' => '1',
          'name' => 'contact_name',
          'vname' => 'LBL_CONTACT_NAME',
          'type' => 'varchar',
          'massupdate' => 0,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => ' ',
          'audited' => 1,
          'reportable' => 0,
          'len' => '150',
        ),
        'email' =>
        array(
          'required' => false,
          'name' => 'email',
          'vname' => 'LBL_EMAIL',
          'type' => 'varchar',
          'massupdate' => 0,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => ' ',
          'audited' => 1,
          'reportable' => 0,
          'len' => '100',
        ),
        'phone' =>
        array(
          'required' => '1',
          'name' => 'phone',
          'vname' => 'LBL_PHONE',
          'type' => 'phone',
          'massupdate' => 0,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => ' ',
          'audited' => 1,
          'reportable' => 0,
          'len' => '25',
          'dbType' => 'varchar',
        ),
        'request_detail' =>
        array(
          'required' => '1',
          'name' => 'request_detail',
          'vname' => 'LBL_REQUEST_DETAIL',
          'type' => 'text',
          'massupdate' => 0,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => ' ',
          'audited' => 1,
          'reportable' => 0,
          'studio' => 'visible',
        ),
        'request_status' =>
        array(
          'required' => '1',
          'name' => 'request_status',
          'vname' => 'LBL_REQUEST_STATUS',
          'type' => 'enum',
          'massupdate' => 0,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => ' ',
          'audited' => 1,
          'reportable' => 0,
          'len' => 100,
          'options' => 'request_status_list',
          'studio' => 'visible',
          'dependency' => false,
        ),
        'city' =>
        array(
          'required' => false,
          'name' => 'city',
          'vname' => 'LBL_CITY',
          'type' => 'varchar',
          'massupdate' => 0,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => ' ',
          'audited' => 1,
          'reportable' => 0,
          'len' => '100',
        ),
        'country' =>
        array(
          'required' => false,
          'name' => 'country',
          'vname' => 'LBL_COUNTRY',
          'type' => 'varchar',
          'massupdate' => 0,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => ' ',
          'audited' => 1,
          'reportable' => 0,
          'len' => '100',
        ),
        'cancel_reason' =>
        array(
          'required' => 0,
          'name' => 'cancel_reason',
          'vname' => 'LBL_CANCEL_REASON',
          'type' => 'text',
          'massupdate' => 0,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => ' ',
          'audited' => 1,
          'reportable' => 0,
          'studio' => 'visible',
        ),
      ),
    'relationships' => array (
),
    'optimistic_locking' => true,
    'unified_search' => true,
);
if (!class_exists('VardefManager')) {
        require_once('include/SugarObjects/VardefManager.php');
}
VardefManager::createVardef('EC_Request_Flight', 'EC_Request_Flight', array('basic','assignable','security_groups'));
