<?php
$dictionary['AOK_KnowledgeBase'] = array(
    'table' => 'aok_knowledgebase',
    'audited' => true,
    'duplicate_merge' => true,
    'fields' => array(
        'name' =>
        array(
            'name' => 'name',
            'vname' => 'LBL_NAME',
            'type' => 'name',
            'link' => true,
            'dbType' => 'varchar',
            'len' => '255',
            'unified_search' => false,
            'full_text_search' =>
            array(
                'boost' => 3,
            ),
            'required' => true,
            'importable' => 'required',
            'duplicate_merge' => 'disabled',
            'merge_filter' => 'disabled',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'size' => '20',
        ),
        'status' =>
        array(
            'required' => false,
            'name' => 'status',
            'vname' => 'LBL_STATUS',
            'type' => 'enum',
            'massupdate' => 0,
            'default' => 'Draft',
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => 100,
            'size' => '20',
            'options' => 'aok_status_list',
            'studio' => 'visible',
            'dependency' => false,
        ),
        'revision' =>
        array(
            'required' => false,
            'name' => 'revision',
            'vname' => 'LBL_REVISION',
            'type' => 'varchar',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => '255',
            'size' => '20',
        ),
        'description' =>
        array(
            'name' => 'description',
            'vname' => 'LBL_DESCRIPTION',
            'type' => 'text',
            'comment' => 'Full text of the note',
            'rows' => '6',
            'cols' => '80',
            'required' => false,
            'massupdate' => 0,
            'no_default' => false,
            'comments' => 'Full text of the note',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'size' => '20',
            'studio' => 'visible',
        ),
        'additional_info' =>
        array(
            'name' => 'additional_info',
            'vname' => 'LBL_ADDITIONAL_INFO',
            'type' => 'text',
            'comment' => 'Full text of the note',
            'rows' => '6',
            'cols' => '80',
            'required' => false,
            'massupdate' => 0,
            'no_default' => false,
            'comments' => 'Full text of the note',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'size' => '20',
            'studio' => 'visible',
        ),
        'user_id_c' =>
        array(
            'required' => false,
            'name' => 'user_id_c',
            'vname' => 'LBL_AUTHOR_USER_ID',
            'type' => 'id',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => 0,
            'audited' => false,
            'reportable' => false,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => 36,
            'size' => '20',
        ),
        'author' =>
        array(
            'required' => true,
            'source' => 'non-db',
            'name' => 'author',
            'vname' => 'LBL_AUTHOR',
            'type' => 'relate',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => '255',
            'size' => '20',
            'id_name' => 'user_id_c',
            'ext2' => 'Users',
            'module' => 'Users',
            'rname' => 'name',
            'quicksearch' => 'enabled',
            'studio' => 'visible',
        ),
        'user_id1_c' =>
        array(
            'required' => false,
            'name' => 'user_id1_c',
            'vname' => 'LBL_APPROVER_USER_ID',
            'type' => 'id',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => 0,
            'audited' => false,
            'reportable' => false,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => 36,
            'size' => '20',
        ),
        'approver' =>
        array(
            'required' => false,
            'source' => 'non-db',
            'name' => 'approver',
            'vname' => 'LBL_APPROVER',
            'type' => 'relate',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => '255',
            'size' => '20',
            'id_name' => 'user_id1_c',
            'ext2' => 'Users',
            'module' => 'Users',
            'rname' => 'name',
            'quicksearch' => 'enabled',
            'studio' => 'visible',
        ),
        'aok_knowledgebase_categories' => array(
            'name' => 'aok_knowledgebase_categories',
            'type' => 'link',
            'relationship' => 'aok_knowledgebase_categories',
            'source' => 'non-db',
            'module' => 'AOK_Knowledge_Base_Categories',
            'bean_name' => false,
            'vname' => 'LBL_AOK_KB_CATEGORIES_TITLE',
        ),

        // custom
        'photo' => array(
            'name' => 'photo',
            'vname' => 'LBL_PHOTO',
            'type' => 'image',
            'massupdate' => false,
            'comments' => '',
            'help' => '',
            'importable' => false,
            'border' => true,
            'reportable' => true,
            'len' => 255,
            'dbType' => 'varchar',
            'width' => '500',
            'height' => 'auto',
            'studio' => array('listview' => true),
        ),
        'photo_sub' => array(
            'name' => 'photo_sub',
            'vname' => 'LBL_PHOTO_SUB',
            'type' => 'image',
            'massupdate' => false,
            'comments' => '',
            'help' => '',
            'importable' => false,
            'border' => true,
            'reportable' => true,
            'len' => 255,
            'dbType' => 'varchar',
            'width' => '500',
            'height' => 'auto',
            'studio' => array('listview' => true),
        ),

    ),
    'relationships' => array(),
    'optimistic_locking' => true,
    'unified_search' => true,
);

if (!class_exists('VardefManager')) {
    require_once('include/SugarObjects/VardefManager.php');
}
VardefManager::createVardef('AOK_KnowledgeBase', 'AOK_KnowledgeBase', array('basic', 'assignable', 'security_groups'));
