<?php

$dictionary['EC_Flight_Bookings'] = array(
    'table' => 'ec_flight_bookings',
    'audited' => true,
    'inline_edit' => true,
    'duplicate_merge' => true,
    'fields' => array(
        'payment_type' => array(
            'name'       => 'payment_type',
            'vname'      => 'LBL_PAYMENT_TYPE',
            'type'       => 'enum',
            'dbtype'     => 'char',
            'options'    => 'booking_payment_type_list',
            'len'        => 1,
            'default'    => '3', // Chuyển khoản
            'massupdate' => false,
            'importable' => true,
            'reportable' => true,
            'dependency' => false,
            'audited' => 1,
            'studio'     => 'visible',
        ),

        'ticket_type' => array(
            'name'       => 'ticket_type',
            'vname'      => 'LBL_TICKET_TYPE',
            'type'       => 'enum',
            'dbtype'     => 'char',
            'options'    => 'booking_ticket_type_list',
            'len'        => 1,
            'default'    => '1',
            'massupdate' => false,
            'importable' => true,
            'reportable' => false,
            'dependency' => false,
            'audited' => 1,
        ),

        // Add by DucPham from table ec_flight_bookings_cstm - 24/04/2023
        'is_recheck_success' => array(
            'name'       => 'is_recheck_success',
            'vname'      => 'LBL_IS_RECHECK_SUCCESS',
            'type'       => 'bool',
            'default'    => 0,
            'importable' => true,
            'reportable' => false,
        ),

        'recheck_status' => array(
            'name'       => 'recheck_status',
            'vname'      => 'LBL_RECHECK_STATUS',
            'type'       => 'enum',
            'dbtype'     => 'char',
            'options'    => 'booking_recheck_status_list',
            'len'        => 1,
            'default'    => '0',
            'importable' => true,
            'reportable' => false,
            'dependency' => false,
            'studio'     => 'visible',
            'audited' => 1,

        ),

        'booking_status' => array(
            'name'       => 'booking_status',
            'vname'      => 'LBL_BOOKING_STATUS',
            'type'       => 'enum',
            'dbtype'     => 'char',
            'options'    => 'booking_status_list',
            'len'        => 1,
            'default'    => '1', // Mới tạo
            'required'   => true,
            'importable' => true,
            'reportable' => false,
            'dependency' => false,
            'studio'     => 'visible',
            'audited'    => 1,
        ),

        'contact_name' => array(
            'name'       => 'contact_name',
            'vname'      => 'LBL_CONTACT_NAME',
            'type'       => 'varchar',
            'len'        => 128,
            'required'   => true,
            'default'    => '',
            'importable' => true,
            'reportable' => false,
            'audited' => 1,
        ),

        'email' => array(
            'name'       => 'email',
            'vname'      => 'LBL_EMAIL',
            'type'       => 'varchar',
            'len'        => 50,
            'default'    => '',
            'importable' => true,
            'audited' => 1,
            'reportable' => false,
        ),

        // custom
        'email_reservation' => array(
            'name'       => 'email_reservation',
            'vname'      => 'LBL_EMAIL_RESERVATION',
            'type'       => 'varchar',
            'len'        => 50,
            'default'    => '',
            'importable' => true,
            'audited'    => 1,
            'reportable' => false,
        ),

        'phone' => array(
            'name'       => 'phone',
            'vname'      => 'LBL_PHONE',
            'type'       => 'phone',
            'dbType'     => 'varchar',
            'len'        => 30,
            'required'   => true,
            'default'    => '',
            'importable' => true,
            'reportable' => false,
            'audited' => 1,
        ),

        'address' => array(
            'name'       => 'address',
            'vname'      => 'LBL_ADDRESS',
            'type'       => 'varchar',
            'len'        => 255,
            'default'    => '',
            'importable' => true,
            'reportable' => false,
            'audited' => 1,
        ),

        'is_invoice_export' => array(
            'name'       => 'is_invoice_export',
            'vname'      => 'LBL_IS_INVOICE_EXPORT',
            'type'       => 'bool',
            'len'        => 1,
            'default'    => 0,
            'importable' => true,
            'reportable' => false,
        ),

        'is_invoice_input_export' => array(
            'name'       => 'is_invoice_input_export',
            'vname'      => 'LBL_IS_INVOICE_INPUT_EXPORT',
            'type'       => 'bool',
            'len'        => 1,
            'default'    => 0,
            'importable' => true,
            'reportable' => false,
        ),

        // Add by DucPham from table ec_flight_bookings_cstm - 24/04/2023
        'invoice_require' => array(
            'name'       => 'invoice_require',
            'vname'      => 'LBL_INVOICE_REQUIRE',
            'type'       => 'bool',
            'len'        => 1,
            'default'    => 0,
            'importable' => true,
            'audited' => 1,
            'reportable' => false,
        ),

        'is_hold' => array(
            'name'       => 'is_hold',
            'vname'      => 'LBL_IS_HOLD',
            'type'       => 'bool',
            'len'        => 1,
            'default'    => 0,
            'importable' => true,
            'reportable' => false,
        ),

        'is_ticket_exported' => array(
            'name'       => 'is_ticket_exported',
            'vname'      => 'LBL_IS_TICKET_EXPORTED',
            'type'       => 'bool',
            'len'        => 1,
            'default'    => 0,
            'importable' => true,
            'reportable' => false,
            'audited' => 1,
        ),

        // Add by DucPham from table ec_flight_bookings_cstm - 24/04/2023
        'is_ticket_inbound_exported' => array(
            'name'       => 'is_ticket_inbound_exported',
            'vname'      => 'LBL_IS_TICKET_INBOUND_EXPORTED',
            'type'       => 'bool',
            'len'        => 1,
            'default'    => 0,
            'importable' => true,
            'reportable' => false,
            'audited' => 1,
        ),

        'is_paid' => array(
            'name'       => 'is_paid',
            'vname'      => 'LBL_IS_PAID',
            'type'       => 'bool',
            'len'        => 1,
            'default'    => 0,
            'importable' => true,
            'reportable' => false,
            'audited' => 1,
        ),

        'holding_status' => array(
            'name'       => 'holding_status',
            'vname'      => 'LBL_HOLDING_STATUS',
            'type'       => 'enum',
            'dbType'     => 'char',
            'options'    => 'bk_holding_status_list',
            'len'        => 1,
            'default'    => '',
            'importable' => true,
            'reportable' => false,
            'dependency' => false,
            'studio'     => 'visible',
            'audited' => 1,
        ),

        'flight_type' => array(
            'name'       => 'flight_type',
            'vname'      => 'LBL_FLIGHT_TYPE',
            'type'       => 'enum',
            'dbType'     => 'char',
            'options'    => 'bk_flight_type_list',
            'len'        => 1,
            'default'    => '',
            'importable' => true,
            'reportable' => false,
            'dependency' => false,
            'studio'     => 'visible',
            'audited' => 1,
        ),

        'subtotal_amount' => array(
            'name'       => 'subtotal_amount',
            'vname'      => 'LBL_SUBTOTAL_AMOUNT',
            'type'       => 'currency',
            'len'        => 26,
            'default'    => 0,
            'importable' => true,
            'reportable' => false,
            'audited' => 1,
        ),

        'luggage_fee' => array(
            'name'       => 'luggage_fee',
            'vname'      => 'LBL_LUGGAGE_FEE',
            'type'       => 'currency',
            'len'        => 26,
            'default'    => 0,
            'importable' => true,
            'reportable' => false,
            'audited' => 1,
        ),

        'discount_percent' => array(
            'name'       => 'discount_percent',
            'vname'      => 'LBL_DISCOUNT_PERCENT',
            'type'       => 'int',
            'len'        => 3,
            'default'    => 0,
            'importable' => true,
            'reportable' => false,
            'audited' => 1,
            'disable_num_format' => '',
        ),

        'discount_amount' => array(
            'name'       => 'discount_amount',
            'vname'      => 'LBL_DISCOUNT_AMOUNT',
            'type'       => 'currency',
            'len'        => 26,
            'default'    => 0,
            'importable' => true,
            'audited' => 1,
            'reportable' => false,
        ),

        'total_amount' => array(
            'name'       => 'total_amount',
            'vname'      => 'LBL_TOTAL_AMOUNT',
            'type'       => 'currency',
            'len'        => 26,
            'default'    => 0,
            'importable' => true,
            'reportable' => false,
            'audited' => 1,
        ),

        // Add by DucPham from table ec_flight_bookings_cstm - 24/04/2023
        'total_bought_price' => array(
            'name'       => 'total_bought_price',
            'vname'      => 'LBL_TOTAL_BOUGHT_PRICE',
            'type'       => 'currency',
            'len'        => 26,
            'default'    => 0,
            'importable' => true,
            'reportable' => false,
            'audited' => 1,
        ),

        'total_bought_amount' => array(
            'name'       => 'total_bought_amount',
            'vname'      => 'LBL_TOTAL_BOUGHT_AMOUNT',
            'type'       => 'currency',
            'len'        => 26,
            'default'    => 0,
            'importable' => true,
            'reportable' => false,
            'audited' => 1,
        ),

        'other_fee' => array(
            'name'       => 'other_fee',
            'vname'      => 'LBL_OTHER_FEE',
            'type'       => 'currency',
            'len'        => 26,
            'default'    => 0,
            'importable' => true,
            'reportable' => false,
            'audited' => 1,
        ),

        'city' => array(
            'name'       => 'city',
            'vname'      => 'LBL_CITY',
            'type'       => 'varchar',
            'len'        => 80,
            'default'    => '',
            'importable' => true,
            'reportable' => false,
            'audited' => 1,
        ),

        'country' => array(
            'name'       => 'country',
            'vname'      => 'LBL_COUNTRY',
            'type'       => 'varchar',
            'len'        => 50,
            'default'    => '',
            'importable' => true,
            'reportable' => false,
            'audited' => 1,
        ),

        'airline' => array(
            'name'       => 'airline',
            'vname'      => 'LBL_AIRLINE',
            'type'       => 'varchar',
            'len'        => 12,
            'default'    => '',
            'importable' => true,
            'reportable' => false,
            'audited' => 1,
        ),

        'airline_inbound' => array(
            'name'       => 'airline_inbound',
            'vname'      => 'LBL_AIRLINE_INBOUND',
            'type'       => 'varchar',
            'len'        => 12,
            'default'    => '',
            'importable' => true,
            'reportable' => false,
            'audited' => 1,
        ),

        'company_name' => array(
            'name'       => 'company_name',
            'vname'      => 'LBL_COMPANY_NAME',
            'type'       => 'varchar',
            'len'        => 255,
            'default'    => '',
            'importable' => true,
            'reportable' => false,
            'audited' => 1,
        ),

        'tax_code' => array(
            'name'       => 'tax_code',
            'vname'      => 'LBL_TAX_CODE',
            'type'       => 'varchar',
            'len'        => 20,
            'default'    => '',
            'importable' => true,
            'reportable' => false,
            'audited' => 1,
        ),

        'company_address' => array(
            'name'       => 'company_address',
            'vname'      => 'LBL_COMPANY_ADDRESS',
            'type'       => 'varchar',
            'length'     => 300,
            'default'    => '',
            'importable' => true,
            'reportable' => false,
            'studio'     => 'visible',
            'audited' => 1,
        ),

        'shipping_address' => array(
            'name'       => 'shipping_address',
            'vname'      => 'LBL_SHIPPING_ADDRESS',
            'type'       => 'varchar',
            'length'     => 500,
            'default'    => '',
            'importable' => true,
            'reportable' => false,
            'studio'     => 'visible',
            'audited' => 1,
        ),

        'is_mail_confirm' => array(
            'name'       => 'is_mail_confirm',
            'vname'      => 'LBL_IS_MAIL_CONFIRM',
            'type'       => 'bool',
            'default'    => 0,
            'importable' => true,
            'reportable' => false,
            'audited' => 1,
        ),

        'sendmail_confirm_date' => array(
            'name'       => 'sendmail_confirm_date',
            'vname'      => 'LBL_SENDMAIL_CONFIRM_DATE',
            'type'       => 'datetime',
            'importable' => true,
            'reportable' => false,
            'audited' => 1,
        ),

        'is_mail_eticket' => array(
            'name'       => 'is_mail_eticket',
            'vname'      => 'LBL_IS_MAIL_ETICKET',
            'type'       => 'bool',
            'default'    => 0,
            'importable' => true,
            'reportable' => false,
            'audited' => 1,
        ),

        'nganluong_code' => array(
            'name'       => 'nganluong_code',
            'vname'      => 'LBL_NGANLUONG_CODE',
            'type'       => 'varchar',
            'len'        => 30,
            'default'    => '',
            'importable' => true,
            'reportable' => false,
            'audited' => 1,
        ),

        'nganluong_datepaid' => array(
            'name'       => 'nganluong_datepaid',
            'vname'      => 'LBL_NGANLUONG_DATEPAID',
            'type'       => 'datetime',
            'importable' => true,
            'reportable' => false,
        ),

        'nganluong_info' => array(
            'required' => false,
            'name' => 'nganluong_info',
            'vname' => 'LBL_NGANLUONG_INFO',
            'type' => 'mediumtext',
            'massupdate' => 0,
            'comments' => 'thong tin booking thanh toan online',
            'importable' => true,
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '',
            // 'audited' => 1,
            'reportable' => false,
            'studio' => 'visible',
            'default' => ''
        ),

        'date_ticket_issue' => array(
            'name'       => 'date_ticket_issue',
            'vname'      => 'LBL_DATE_TICKET_ISSUE',
            'type'       => 'date',
            'importable' => true,
            'reportable' => false,
            'audited'    => 1,
            'enable_range_search' => true,
            'options' => 'date_range_search_dom',
        ),

        // Add by DucPham from table ec_flight_bookings_cstm - 24/04/2023
        'date_ticket_inbound_issue' => array(
            'name'       => 'date_ticket_inbound_issue',
            'vname'      => 'LBL_DATE_TICKET_INBOUND_ISSUE',
            'type'       => 'date',
            'importable' => true,
            'reportable' => false,
            'audited' => 1,
        ),

        'account_id' => array(
            'name'       => 'account_id',
            'vname'      => '',
            'type'       => 'id',
            'len'        => 36,
            'default'    => '',
            'importable' => true,
            'reportable' => false,
        ),
        'account_name' => array(
            'name'      => 'account_name',
            'vname'     => 'LBL_ACCOUNT_NAME',
            'type'      => 'relate',
            'source'    => 'non-db',
            'importable' => true,
            'reportable' => false,
            'id_name'    => 'account_id',
            'ext2'       => 'Accounts',
            'module'     => 'Accounts',
            'rname'      => 'name',
            'studio'     => 'visible',
            'quicksearch' => 'enabled',
        ),

        'thuephi_quocte' => array(
            'name'       => 'thuephi_quocte',
            'vname'      => 'LBL_THUEPHI_QUOCTE',
            'type'       => 'currency',
            'len'        => 26,
            'default'    => 0,
            'importable' => true,
            'reportable' => false,
        ),

        'is_agent' => array(
            'name'       => 'is_agent',
            'vname'      => 'LBL_IS_AGENT',
            'type'       => 'bool',
            'default'    => 0,
            'importable' => true,
            'reportable' => false,
        ),

        'sms_inbound' => array(
            'name'       => 'sms_inbound',
            'vname'      => 'LBL_SMS_INBOUND',
            'type'       => 'text',
            'default'    => '',
            'importable' => true,
            'reportable' => false,
            'studio'     => 'visible',
            'audited' => 1,
        ),

        'sms_outbound' => array(
            'name'       => 'sms_outbound',
            'vname'      => 'LBL_SMS_OUTBOUND',
            'type'       => 'text',
            'default'    => '',
            'importable' => true,
            'reportable' => false,
            'studio'     => 'visible',
            'audited' => 1,
        ),

        'total_qty' => array(
            'name'       => 'total_qty',
            'vname'      => 'LBL_TOTAL_QTY',
            'type'       => 'int',
            'default'    => 0,
            'importable' => true,
            'reportable' => false,
            'audited' => 1,
        ),

        'is_promo' => array(
            'name'       => 'is_promo',
            'vname'      => 'LBL_IS_PROMO',
            'type'       => 'bool',
            'default'    => 0,
            'importable' => true,
            'reportable' => false,
        ),

        'lydothangthua_id' => array(
            'name'       => 'lydothangthua_id',
            'vname'      => '',
            'type'       => 'id',
            'len'        => 36,
            'default'    => '',
            'importable' => true,
            'reportable' => false,
        ),
        'lydothangthua' => array(
            'name'       => 'lydothangthua',
            'vname'      => 'LBL_LYDOTHANGTHUA',
            'type'       => 'relate',
            'source'     => 'non-db',
            'importable' => true,
            'reportable' => false,
            'id_name'    => 'lydothangthua_id',
            'ext2'       => 'EC_LyDoThangThua',
            'module'     => 'EC_LyDoThangThua',
            'rname'      => 'name',
            'studio'     => 'visible',
            'quicksearch' => 'enabled',
            'audited' => 1,
        ),

        'ghichuthangthua' => array(
            'name'       => 'ghichuthangthua',
            'vname'      => 'LBL_GHICHUTHANGTHUA',
            'type'       => 'text',
            'default'    => '',
            'importable' => true,
            'reportable' => false,
            'studio'     => 'visible',
            'audited' => 1,
        ),

        'contact_title' => array(
            'name'       => 'contact_title',
            'vname'      => 'LBL_CONTACT_TITLE',
            'type'       => 'enum',
            'dbType'     => 'char',
            'options'    => 'passenger_salutation_list',
            'len'        => 1,
            'default'    => '0',
            'importable' => true,
            'reportable' => false,
            'dependency' => false,
            'studio'     => 'visible',
            'audited' => 1,
        ),

        'agent_id' => array(
            'name'       => 'agent_id',
            'vname'      => '',
            'type'       => 'id',
            'len'        => 36,
            'default'    => '',
            'importable' => true,
            'reportable' => false,
        ),
        'agent_name' => array(
            'name'       => 'agent_name',
            'vname'      => 'LBL_AGENT_NAME',
            'type'       => 'relate',
            'source'     => 'non-db',
            'importable' => true,
            'reportable' => false,
            'id_name'    => 'agent_id',
            'ext2'       => 'Accounts',
            'module'     => 'Accounts',
            'rname'      => 'name',
            'studio'     => 'visible',
            'quicksearch' => 'enabled',
            'audited' => 1,
        ),

        'ip_address' => array(
            'name'       => 'ip_address',
            'vname'      => 'LBL_IP_ADDRESS',
            'type'       => 'varchar',
            'len'        => 42,
            'default'    => '',
            'importable' => true,
            'reportable' => false,
            'audited' => 1,
        ),

        'user_agent' => array(
            'name'       => 'user_agent',
            'vname'      => 'LBL_USER_AGENT',
            'type'       => 'varchar',
            'len'        => 255,
            'default'    => '',
            'importable' => true,
            'reportable' => false,
            'audited' => 1,
        ),

        'delivery_man_id' => array(
            'name'       => 'delivery_man_id',
            'vname'      => '',
            'type'       => 'id',
            'len'        => 36,
            'default'    => '',
            'importable' => true,
            'reportable' => false,
        ),
        'delivery_man' => array(
            'name'       => 'delivery_man',
            'vname'      => 'LBL_DELIVERY_MAN',
            'type'       => 'relate',
            'source'     => 'non-db',
            'importable' => true,
            'reportable' => false,
            'id_name'   => 'delivery_man_id',
            'ext2'      => 'Users',
            'module'    => 'Users',
            'rname'     => 'name',
            'studio'    => 'visible',
            'quicksearch' => 'enabled',
            'audited' => 1,
        ),

        'app_member_user' => array(
            'name'       => 'app_member_user',
            'vname'      => 'LBL_APP_MEMBER_USER',
            'type'       => 'varchar',
            'len'        => 50,
            'default'    => '',
            'importable' => true,
            'reportable' => false,
        ),

        'contact_id' => array(
            'name' => 'contact_id',
            'vname' => 'LBL_CONTACT_ID',
            'type' => 'id',
            'length' => 36,
            'default' => '',
            'reportable' => false,
            'audited' => true,
            'massupdate' => false,
            'comment' => 'The contact to which the case is associated'
        ),

        'journey' => array(
            'name'       => 'journey',
            'vname'      => 'LBL_JOURNEY',
            'type'       => 'varchar',
            'len'        => 10,
            'default'    => '',
            'importable' => true,
            'reportable' => false,
            'audited' => 1,
        ),

        'vouchers' => array(
            'name' => 'vouchers',
            'type' => 'link',
            'relationship' => 'bookings_vouchers',
            'module' => 'EC_Vouchers',
            'bean_name' => 'EC_Vouchers',
            'source' => 'non-db',
            'vname' => 'LBL_VOUCHERS',
        ),

        // Add by DucPham - 07/06/2025
        'is_output_invoice_checked' => array(
            'name'       => 'is_output_invoice_checked',
            'vname'      => 'LBL_IS_OUTPUT_INVOICE_CHECKED',
            'type'       => 'bool',
            'default'    => 0,
            'importable' => 0,
            'reportable' => 0,
            'audited'    => 0,
            'comment'    => 'Kiểm tra xuất đủ hóa đơn đầu ra hay chưa',
        ),

        'telesale_call_id' => array(
            'required'   => false,
            'name'       => 'telesale_call_id',
            'vname'      => '',
            'type'       => 'id',
            'comments'   => 'ID của cuộc gọi từ telesale gần nhất',
            'len'        => 36,
            'default'    => '',
            'importable' => true,
            'reportable' => false,
        ),
        'is_telesale' => array(
            'name'       => 'is_telesale',
            'vname'      => 'LBL_IS_TELESALE',
            'comments'   => 'Đánh dấu booking này là kết quả của cuộc gọi telesale',
            'type'       => 'bool',
            'default'    => 0,
            'importable' => true,
            'reportable' => false,
            'audited' => 1,
        ),
        'is_ctv' => array(
            'name'       => 'is_ctv',
            'vname'      => 'LBL_IS_CTV',
            'comments'   => 'Đánh dấu booking này là từ CTV',
            'type'       => 'bool',
            'default'    => 0,
            'importable' => true,
            'reportable' => false,
            'audited' => 1,
        ),
        'is_reference' => array(
            'name'       => 'is_reference',
            'vname'      => 'LBL_IS_REFERENCE',
            'comments'   => 'Đánh dấu booking tham khảo',
            'type'       => 'bool',
            'default'    => 0,
            'importable' => true,
            'reportable' => false,
        ),
        'is_prior' => array(
            'name'       => 'is_prior',
            'vname'      => 'LBL_IS_PRIOR',
            'comments'   => 'Đánh dấu booking cận',
            'type'       => 'bool',
            'default'    => 0,
            'importable' => true,
            'reportable' => false,
        ),
        
        // Add by DucPham - 13/01/2026
        'customer_source' => array(
            'name'       => 'customer_source',
            'vname'      => 'LBL_CUSTOMER_SOURCE',
            'type'       => 'enum',
            'options'    => 'booking_customer_source_list',
            'len'        => 10,
            'default'    => 'system',
            'massupdate' => 0,
            'importable' => 1,
            'reportable' => 1,
            'audited'    => 1,
            'studio'     => 'visible',
        ),
    ),
    'indices' => array(
        array('name' => 'idx_bk_name', 'type' => 'index', 'fields' => array('name')),
        array('name' => 'idx_bk_phone', 'type' => 'index', 'fields' => array('phone')),
        array('name' => 'idx_bk_email', 'type' => 'index', 'fields' => array('email')),
        array('name' => 'idx_bk_bkstatus', 'type' => 'index', 'fields' => array('booking_status')),
        array('name' => 'idx_bk_contact', 'type' => 'index', 'fields' => array('contact_name')),
        array('name' => 'idx_bk_contact_id', 'type' => 'index', 'fields' => array('contact_id')),
        array('name' => 'idx_bk_assign', 'type' => 'index', 'fields' => array('assigned_user_id')),
        array('name' => 'idx_bk_date_ticket_issue', 'type' => 'index', 'fields' => array('date_ticket_issue')),
        array('name' => 'idx_bk_dateen', 'type' => 'index', 'fields' => array('date_entered')),
    ),
    'relationships' => array(),
    'optimistic_locking' => true,
    'unified_search' => true,
);
if (!class_exists('VardefManager')) {
    require_once('include/SugarObjects/VardefManager.php');
}
VardefManager::createVardef('EC_Flight_Bookings', 'EC_Flight_Bookings', array('basic', 'assignable', 'security_groups'));
