<?php

$dictionary['EC_HoaDonMua'] = array(
    'table' => 'ec_hoadonmua',
    'audited' => true,
    'inline_edit' => true,
    'duplicate_merge' => true,
    'fields' => 
    array(
      'booking_id' =>
      array(
        'required' => false,
        'name' => 'booking_id',
        'vname' => '',
        'type' => 'id',
        'massupdate' => 0,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => 0,
        'audited' => 0,
        'reportable' => 0,
        'len' => 36,
      ),
      'booking' =>
      array(
        'required' => '0',
        'source' => 'non-db',
        'name' => 'booking',
        'vname' => 'LBL_BOOKING',
        'type' => 'relate',
        'massupdate' => 0,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => ' ',
        'audited' => 1,
        'reportable' => 0,
        'len' => '255',
        'id_name' => 'booking_id',
        'ext2' => 'EC_Flight_Bookings',
        'module' => 'EC_Flight_Bookings',
        'rname' => 'name',
        'quicksearch' => 'enabled',
        'studio' => 'visible',
      ),
      'nguoigiao' =>
      array(
        'required' => false,
        'name' => 'nguoigiao',
        'vname' => 'LBL_NGUOIGIAO',
        'type' => 'varchar',
        'massupdate' => 0,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => ' ',
        'audited' => 1,
        'reportable' => 0,
        'len' => '150',
      ),
      'diachi' =>
      array(
        'required' => false,
        'name' => 'diachi',
        'vname' => 'LBL_DIACHI',
        'type' => 'text',
        'massupdate' => 0,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => ' ',
        'audited' => 1,
        'reportable' => 0,
        'studio' => 'visible',
      ),
      'kemtheo' =>
      array(
        'required' => false,
        'name' => 'kemtheo',
        'vname' => 'LBL_KEMTHEO',
        'type' => 'text',
        'massupdate' => 0,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => ' ',
        'audited' => 1,
        'reportable' => 0,
        'studio' => 'visible',
      ),
      'nhacungcap_id' =>
      array(
        'required' => false,
        'name' => 'nhacungcap_id',
        'vname' => '',
        'type' => 'id',
        'massupdate' => 0,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => 0,
        'audited' => 0,
        'reportable' => 0,
        'len' => 36,
      ),
      'nhacungcap' =>
      array(
        'required' => false,
        'source' => 'non-db',
        'name' => 'nhacungcap',
        'vname' => 'LBL_NHACUNGCAP',
        'type' => 'relate',
        'massupdate' => 0,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => ' ',
        'audited' => 1,
        'reportable' => 0,
        'len' => '255',
        'id_name' => 'nhacungcap_id',
        'ext2' => 'Accounts',
        'module' => 'Accounts',
        'rname' => 'name',
        'quicksearch' => 'enabled',
        'studio' => 'visible',
      ),
      'nhanhoadon' =>
      array(
        'required' => false,
        'name' => 'nhanhoadon',
        'vname' => 'LBL_NHANHOADON',
        'type' => 'bool',
        'massupdate' => 0,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '',
        'audited' => 1,
        'reportable' => 0,
        'len' => '255',
      ),
      'sohoadon' =>
      array(
        'required' => false,
        'name' => 'sohoadon',
        'vname' => 'LBL_SOHOADON',
        'type' => 'varchar',
        'massupdate' => 0,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => ' ',
        'audited' => 1,
        'reportable' => 0,
        'len' => '10',
      ),
      'ngaychungtu' =>
      array(
        'required' => '1',
        'name' => 'ngaychungtu',
        'vname' => 'LBL_NGAYCHUNGTU',
        'type' => 'date',
        'massupdate' => 0,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => ' ',
        'audited' => 1,
        'reportable' => 0,
        'display_default' => 'now',
      ),
      'ngayhachtoan' =>
      array(
        'required' => false,
        'name' => 'ngayhachtoan',
        'vname' => 'LBL_NGAYHACHTOAN',
        'type' => 'date',
        'massupdate' => 0,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => ' ',
        'audited' => 1,
        'reportable' => 0,
        'display_default' => 'now',
      ),
      'hanthanhtoan' =>
      array(
        'required' => false,
        'name' => 'hanthanhtoan',
        'vname' => 'LBL_HANTHANHTOAN',
        'type' => 'date',
        'massupdate' => 0,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => ' ',
        'audited' => 1,
        'reportable' => 0,
      ),
      'loaitien' =>
      array(
        'required' => false,
        'name' => 'loaitien',
        'vname' => 'LBL_LOAITIEN',
        'type' => 'enum',
        'massupdate' => 0,
        'default' => 'VND',
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => ' ',
        'audited' => 1,
        'reportable' => 0,
        'len' => 100,
        'options' => 'loaitien_list',
        'studio' => 'visible',
        'dependency' => false,
      ),
      'pt_thanhtoan' =>
      array(
        'required' => false,
        'name' => 'pt_thanhtoan',
        'vname' => 'LBL_PT_THANHTOAN',
        'type' => 'enum',
        'massupdate' => 0,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => ' ',
        'audited' => 1,
        'reportable' => 0,
        'len' => 100,
        'options' => 'pt_thanhtoan_list',
        'studio' => 'visible',
        'dependency' => false,
      ),
      'thuesuat' =>
      array(
        'required' => false,
        'name' => 'thuesuat',
        'vname' => 'LBL_THUESUAT',
        'type' => 'enum',
        'massupdate' => 0,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => ' ',
        'audited' => 1,
        'reportable' => 0,
        'len' => 100,
        'options' => 'thuesuat_list',
        'studio' => 'visible',
        'dependency' => false,
      ),
      'thuevat' =>
      array(
        'required' => false,
        'name' => 'thuevat',
        'vname' => 'LBL_THUEVAT',
        'type' => 'currency',
        'massupdate' => 0,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => ' ',
        'audited' => 1,
        'reportable' => 0,
        'len' => 26,
      ),
      'currency_id' =>
      array(
        'required' => false,
        'name' => 'currency_id',
        'vname' => 'LBL_CURRENCY',
        'type' => 'id',
        'massupdate' => 0,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => 0,
        'audited' => 0,
        'reportable' => 0,
        'len' => 36,
        'studio' => 'visible',
        'function' =>
        array(
          'name' => 'getCurrencyDropDown',
          'returns' => 'html',
        ),
      ),
      'phikhac' =>
      array(
        'required' => false,
        'name' => 'phikhac',
        'vname' => 'LBL_PHIKHAC',
        'type' => 'currency',
        'massupdate' => 0,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => ' ',
        'audited' => 1,
        'reportable' => 0,
        'len' => 26,
      ),
      'tongtien' =>
      array(
        'required' => false,
        'name' => 'tongtien',
        'vname' => 'LBL_TONGTIEN',
        'type' => 'currency',
        'massupdate' => 0,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => ' ',
        'audited' => 1,
        'reportable' => 0,
        'len' => 26,
      ),
      'loaichungtu_id' =>
      array(
        'required' => false,
        'name' => 'loaichungtu_id',
        'vname' => '',
        'type' => 'id',
        'massupdate' => 0,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => 0,
        'audited' => 0,
        'reportable' => 0,
        'len' => 36,
      ),
      'loaichungtu' =>
      array(
        'required' => false,
        'source' => 'non-db',
        'name' => 'loaichungtu',
        'vname' => 'LBL_LOAICHUNGTU',
        'type' => 'relate',
        'massupdate' => 0,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => ' ',
        'audited' => 1,
        'reportable' => 0,
        'len' => '255',
        'id_name' => 'loaichungtu_id',
        'ext2' => 'EC_LoaiChungTu',
        'module' => 'EC_LoaiChungTu',
        'rname' => 'name',
        'quicksearch' => 'enabled',
        'studio' => 'visible',
      ),
      'phihanhly' =>
      array(
        'required' => false,
        'name' => 'phihanhly',
        'vname' => 'LBL_PHIHANHLY',
        'type' => 'currency',
        'massupdate' => 0,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => ' ',
        'audited' => 1,
        'reportable' => 0,
        'len' => 26,
      ),
      'phihoandoive' =>
      array(
        'required' => false,
        'name' => 'phihoandoive',
        'vname' => 'LBL_PHIHOANDOIVE',
        'type' => 'currency',
        'massupdate' => 0,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => ' ',
        'audited' => 1,
        'reportable' => 0,
        'len' => 26,
      ),
      'ptram_giamgia' =>
      array(
        'required' => false,
        'name' => 'ptram_giamgia',
        'vname' => 'LBL_PTRAM_GIAMGIA',
        'type' => 'enum',
        'massupdate' => 0,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => ' ',
        'audited' => 1,
        'reportable' => 0,
        'len' => 100,
        'options' => 'discount_percent_list',
        'studio' => 'visible',
        'dependency' => false,
      ),
      'giamgia' =>
      array(
        'required' => false,
        'name' => 'giamgia',
        'vname' => 'LBL_GIAMGIA',
        'type' => 'currency',
        'massupdate' => 0,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => ' ',
        'audited' => 1,
        'reportable' => 0,
        'len' => 26,
      ),
    ),
    'relationships' => array (
),
    'optimistic_locking' => true,
    'unified_search' => true,
);
if (!class_exists('VardefManager')) {
        require_once('include/SugarObjects/VardefManager.php');
}
VardefManager::createVardef('EC_HoaDonMua', 'EC_HoaDonMua', array('basic','assignable','security_groups'));
