<?php


// THIS CONTENT IS GENERATED BY MBPackage.php
$manifest = array(
  0 =>
  array(
    'acceptable_sugar_versions' =>
    array(
      0 => '',
    ),
  ),
  1 =>
  array(
    'acceptable_sugar_flavors' =>
    array(
      0 => 'CE',
      1 => 'PRO',
      2 => 'ENT',
    ),
  ),
  'readme' => '',
  'key' => 'EC',
  'author' => 'DucPham',
  'description' => 'Module quản lý Zalo OA gồm: chat, tin nhắn, quản lý người dùng OA,...',
  'icon' => '',
  'is_uninstallable' => true,
  'name' => 'Zalo',
  'published_date' => '2024-07-21 07:35:45',
  'type' => 'module',
  'version' => 1721547345,
  'remove_tables' => 'prompt',
);
