<?php


// THIS CONTENT IS GENERATED BY MBPackage.php
$manifest = array(
  0 =>
  array(
    'acceptable_sugar_versions' =>
    array(
      0 => '',
    ),
  ),
  1 =>
  array(
    'acceptable_sugar_flavors' =>
    array(
      0 => 'CE',
      1 => 'PRO',
      2 => 'ENT',
    ),
  ),
  'readme' => '',
  'key' => 'EC',
  'author' => 'DucPham',
  'description' => 'Manage apps in Zalo Developers',
  'icon' => '',
  'is_uninstallable' => true,
  'name' => 'Zalo_Apps',
  'published_date' => '2026-02-12 08:57:12',
  'type' => 'module',
  'version' => 1770886632,
  'remove_tables' => 'prompt',
);
