<?php
$dictionary['EC_Bank_Account'] = array(
    'table' => 'ec_bank_account',
    'audited' => true,
    'inline_edit' => true,
    'duplicate_merge' => true,
    'fields' => array(
        'account_number' => array(
            'name'      => 'account_number',
            'vname'     => 'LBL_ACCOUNT_NUMBER',
            'type'      => 'varchar',
            'required'  => '1',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => ' ',
            'audited' => 1,
            'reportable' => 0,
            'len' => '255',
        ),

        'account_holder' => array(
            'name'      => 'account_holder',
            'vname'     => 'LBL_ACCOUNT_HOLDER',
            'type'      => 'varchar',
            'required'  => '1',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => ' ',
            'audited' => 1,
            'reportable' => 0,
            'len' => '255',
        ),

        'account' => array(
            'name'      => 'account',
            'vname'     => 'LBL_ACCOUNT',
            'type'      => 'varchar',
            'required'  => '0',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => ' ',
            'audited' => 1,
            'reportable' => 0,
            'len' => '10',
        ),

        'bank_id' => array(
            'name'      => 'bank_id',
            'vname'     => '',
            'type'      => 'id',
            'required'  => false,
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => 0,
            'audited' => 0,
            'reportable' => 0,
            'len' => 36,
        ),

        'bank' => array(
            'name'      => 'bank',
            'vname'     => 'LBL_BANK',
            'type'      => 'relate',
            'required'  => true,
            'source'    => 'non-db',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => ' ',
            'audited' => 1,
            'reportable' => 0,
            'len' => '255',
            'id_name' => 'bank_id',
            'ext2' => 'EC_Banks',
            'module' => 'EC_Banks',
            'rname' => 'name',
            'quicksearch' => 'enabled',
            'studio' => 'visible',
        ),

        'branch' => array(
            'name'      => 'branch',
            'vname'     => 'LBL_BRANCH',
            'type'      => 'text',
            'required'  => false,
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => ' ',
            'audited' => 1,
            'reportable' => 0,
            'studio' => 'visible',
        ),

        'unfollow' => array(
            'name'      => 'unfollow',
            'vname'     => 'LBL_UNFOLLOW',
            'type'      => 'bool',
            'required'  => false,
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => ' ',
            'audited' => 1,
            'reportable' => 0,
            'len' => '1',
            'default' => '0',
        ),
        
        'is_display' => array(
            'name'      => 'is_display',
            'vname'     => 'LBL_IS_DISPLAY',
            'type'      => 'bool',
            'required'  => false,
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '',
            'audited' => 1,
            'reportable' => 0,
            'len' => '1',
            'default' => '0',
        ),

        'is_sms' => array(
            'name'      => 'is_sms',
            'vname'     => 'LBL_IS_SMS',
            'type'      => 'bool',
            'required'  => false,
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '',
            'audited' => 1,
            'reportable' => 0,
            'len' => '1',
            'default' => '0',
        ),

        'sort' => array(
            'name'      => 'sort',
            'vname'     => 'LBL_SORT',
            'type'      => 'int',
            'required'  => false,
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 1,
            'reportable' => 0,
            'len' => '11',
            'disable_num_format' => '',
        ),
    ),
    'indices' => array(
        array('name' => 'idx_tknh_name', 'type' => 'index', 'fields' => array('name')),
        array('name' => 'idx_tknh_accountnumber', 'type' => 'index', 'fields' => array('account_number')),
        array('name' => 'idx_tknh_bankid', 'type' => 'index', 'fields' => array('bank_id')),
        array('name' => 'idx_tknh_sort', 'type' => 'index', 'fields' => array('sort')),
        // array('name' => 'idx_tknh_del', 'type' => 'index', 'fields' => array('deleted')),
        // array('name' => 'idx_tknh_unfollow', 'type' => 'index', 'fields' => array('unfollow')),
        // array('name' => 'idx_tknh_display', 'type' => 'index', 'fields' => array('is_display')),
    ),
    'relationships' => array(),
    'optimistic_locking' => true,
    'unified_search' => true,
);

if (!class_exists('VardefManager')) {
    require_once('include/SugarObjects/VardefManager.php');
}
VardefManager::createVardef('EC_Bank_Account', 'EC_Bank_Account', array('basic', 'assignable', 'security_groups'));
