<?php


// THIS CONTENT IS GENERATED BY MBPackage.php
$manifest = array(
  0 =>
  array(
    'acceptable_sugar_versions' =>
    array(
      0 => '',
    ),
  ),
  1 =>
  array(
    'acceptable_sugar_flavors' =>
    array(
      0 => 'CE',
      1 => 'PRO',
      2 => 'ENT',
    ),
  ),
  'readme' => '',
  'key' => 'EC',
  'author' => 'Haihugn',
  'description' => 'Nghỉ phép',
  'icon' => '',
  'is_uninstallable' => true,
  'name' => 'LeaveAbsences',
  'published_date' => '2023-06-19 10:33:06',
  'type' => 'module',
  'version' => 1687170786,
  'remove_tables' => 'prompt',
);
