<?php
if (!defined('sugarEntry') || !sugarEntry) {
    die('Not A Valid Entry Point');
}

date_default_timezone_set('Asia/Ho_Chi_Minh');
header('Content-Type: application/json; charset=utf-8');

// Webhook target of the chat "/baogia" slash command. Unlike entryFareSystemWebhook
// the payload is the slash envelope { Code, Event, ConversationId, UserId, Data }
// and the answer is a rendered HTML card, so the two cannot share an endpoint.
//
// Credentials are generated by Chat when the webhook is registered and are stored
// in SuiteCRM configuration. They must never be echoed back or written to logs.

$sendResponse = static function ($httpCode, $body) {
    http_response_code($httpCode);
    echo $body;
    exit;
};

$respond = static function ($httpCode, $message) use ($sendResponse) {
    $body = json_encode([
        'error' => 1,
        'message' => $message,
        'data' => null,
    ], JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);

    if ($body === false) {
        $body = '{"error":1,"message":"Unable to encode response","data":null}';
    }

    $sendResponse($httpCode, $body);
};

$getRequestHeaders = static function () {
    $headers = function_exists('getallheaders') ? getallheaders() : [];
    if (!is_array($headers)) {
        $headers = [];
    }

    $normalizedHeaders = [];
    foreach ($headers as $name => $value) {
        $normalizedHeaders[strtolower($name)] = $value;
    }

    return $normalizedHeaders;
};

try {
    $requestMethod = strtoupper($_SERVER['REQUEST_METHOD'] ?? '');
    if ($requestMethod !== 'POST') {
        $respond(405, 'Method not allowed');
    }

    $headers = $getRequestHeaders();
    $contentType = $headers['content-type'] ?? ($_SERVER['CONTENT_TYPE'] ?? '');
    if (!is_string($contentType) || stripos($contentType, 'application/json') === false) {
        $respond(415, 'Content-Type must be application/json');
    }

    global $sugar_config;
    $webhookConfig = $sugar_config['webhook']['slash_quote'] ?? [];
    $registeredKey = is_string($webhookConfig['auth_key'] ?? null)
        ? trim($webhookConfig['auth_key'])
        : '';
    $signatureKey = is_string($webhookConfig['signature_key'] ?? null)
        ? trim($webhookConfig['signature_key'])
        : '';

    if (!preg_match('/^[a-f0-9]{64}$/i', $registeredKey)) {
        $respond(500, 'Slash quote webhook auth key is not configured');
    }
    if (!preg_match('/^[a-f0-9]{64}$/i', $signatureKey)) {
        $respond(500, 'Slash quote webhook signature key is not configured');
    }

    $requestKey = $headers['x-auth-key'] ?? ($_SERVER['HTTP_X_AUTH_KEY'] ?? '');
    if (!is_string($requestKey) || $requestKey === '' || !hash_equals($registeredKey, $requestKey)) {
        $respond(401, 'Unauthorized');
    }

    $rawBody = file_get_contents('php://input');
    if (!is_string($rawBody) || trim($rawBody) === '') {
        $respond(400, 'Request body is required');
    }

    $requestSignature = $headers['x-signature'] ?? ($_SERVER['HTTP_X_SIGNATURE'] ?? '');
    $requestSignature = is_string($requestSignature) ? strtolower(trim($requestSignature)) : '';
    $expectedSignature = hash_hmac('sha256', $rawBody, $signatureKey);
    if (!preg_match('/^[a-f0-9]{64}$/', $requestSignature)
        || !hash_equals($expectedSignature, $requestSignature)
    ) {
        $respond(401, 'Unauthorized');
    }

    $payload = json_decode($rawBody, true);
    if (json_last_error() !== JSON_ERROR_NONE || !is_array($payload)) {
        $respond(400, 'Invalid JSON payload');
    }

    $form = is_array($payload['Data'] ?? null) ? $payload['Data'] : [];
    $readString = static function ($value) {
        return is_string($value) ? trim($value) : '';
    };

    $departureCode = strtoupper($readString($form['depCode'] ?? null));
    $destinationCode = strtoupper($readString($form['desCode'] ?? null));
    $airlineCode = strtoupper($readString($form['airlineCode'] ?? null));
    $departureDate = $readString($form['depDate'] ?? null);
    $returnDate = $readString($form['retDate'] ?? null);
    $serviceFee = is_numeric($form['serviceFee'] ?? null) ? (float) $form['serviceFee'] : 0;

    if ($departureDate === '') {
        $respond(400, 'Thiếu ngày đi');
    }
    if ($airlineCode === '') {
        $respond(400, 'Thiếu hãng bay');
    }

    require_once 'modules/EC_Airports/EC_Airports.php';

    $allAirports = EC_Airports::getAirportList(EC_Airports::AIRPORT_SCOPE_ALL);
    if (
        !array_key_exists($departureCode, $allAirports)
        || !array_key_exists($destinationCode, $allAirports)
    ) {
        $respond(400, 'Mã sân bay không được hỗ trợ');
    }

    $domesticAirports = EC_Airports::getAirportList(EC_Airports::AIRPORT_SCOPE_DOMESTIC);
    $isInternational = !array_key_exists($departureCode, $domesticAirports)
        || !array_key_exists($destinationCode, $domesticAirports);

    $searchMethod = $isInternational ? 'searchInterFlightBM' : 'searchFlightBM';

    require_once 'custom/entrypoints/entryFactory.php';

    $entryClass = entryFactory::create('entryFareSystemClass');
    if (!$entryClass || !method_exists($entryClass, $searchMethod)) {
        $respond(500, 'Unable to initialize Fare System service');
    }

    $response = $entryClass->$searchMethod([
        'airlineCode' => $airlineCode,
        'depCode' => $departureCode,
        'desCode' => $destinationCode,
        'departDate' => $departureDate,
        'returnDate' => $returnDate,
    ]);
    if (!is_string($response) || trim($response) === '') {
        $respond(502, 'Hệ thống giá vé không phản hồi');
    }

    $responseData = json_decode($response, true);
    if (json_last_error() !== JSON_ERROR_NONE || !is_array($responseData) || !array_key_exists('error', $responseData)) {
        $respond(502, 'Hệ thống giá vé trả về dữ liệu không hợp lệ');
    }
    if ((int) $responseData['error'] !== 0) {
        $respond(502, is_string($responseData['message'] ?? null) && $responseData['message'] !== ''
            ? $responseData['message']
            : 'Hệ thống giá vé báo lỗi');
    }

    require_once 'custom/include/utils/FlightQuoteHtml.php';

    $flights = FlightQuoteHtml::mapFlights($responseData['data'] ?? []);
    if (!$flights) {
        // Business-level miss, not a transport failure: chat shows `message` in
        // the preview panel and sends nothing to the conversation.
        $respond(200, 'Không tìm thấy chuyến bay phù hợp');
    }

    $html = FlightQuoteHtml::build([
        'depCode' => $departureCode,
        'desCode' => $destinationCode,
        'depDate' => $departureDate,
        'retDate' => $returnDate,
    ], $flights, $serviceFee);

    $body = json_encode([
        'error' => 0,
        'type' => 'html',
        'data' => $html,
        'message' => '',
    ], JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);

    if ($body === false) {
        $respond(500, 'Unable to encode response');
    }

    $sendResponse(200, $body);
} catch (Throwable $throwable) {
    $logMessage = sprintf(
        'Slash quote webhook failed: %s on line %d in %s',
        $throwable->getMessage(),
        $throwable->getLine(),
        $throwable->getFile()
    );

    if (isset($GLOBALS['log']) && is_object($GLOBALS['log'])) {
        $GLOBALS['log']->fatal($logMessage);
    } else {
        error_log($logMessage);
    }

    $respond(500, 'Internal server error');
}
