<?php
if (!defined('sugarEntry') || !sugarEntry) {
    die('Not A Valid Entry Point');
}

use custom\services\Webhook\WebhookAuthenticator;

date_default_timezone_set('Asia/Ho_Chi_Minh');
header('Content-Type: application/json; charset=utf-8');

// Webhook target of the chat "/baogia" slash command. Unlike entryFareSystemWebhook
// the payload is the slash envelope { Code, Event, ConversationId, UserId, Data }
// and the answer is a rendered HTML card, so the two cannot share an endpoint.
//
// Credentials are generated by Chat when the webhook is registered and are stored
// in SuiteCRM configuration. They must never be echoed back or written to logs.

$slashQuoteSend = static function (int $httpCode, array $payload): void {
    http_response_code($httpCode);
    $body = json_encode($payload, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);
    echo $body === false ? '{"error":1,"message":"Unable to encode response","data":null}' : $body;
    exit;
};

$slashQuoteFail = static function (int $httpCode, string $message) use ($slashQuoteSend): void {
    $slashQuoteSend($httpCode, ['error' => 1, 'message' => $message, 'data' => null]);
};

$slashQuoteLog = static function (string $message): void {
    if (isset($GLOBALS['log']) && is_object($GLOBALS['log'])) {
        $GLOBALS['log']->fatal($message);
        return;
    }

    error_log($message);
};

try {
    if (strtoupper($_SERVER['REQUEST_METHOD'] ?? '') !== 'POST') {
        header('Allow: POST');
        $slashQuoteFail(405, 'Method not allowed');
    }

    $headers = WebhookAuthenticator::requestHeaders();
    if (stripos(WebhookAuthenticator::header($headers, 'content-type'), 'application/json') === false) {
        $slashQuoteFail(415, 'Content-Type must be application/json');
    }

    $authenticator = WebhookAuthenticator::fromConfig();
    if ($authenticator === null) {
        $slashQuoteLog('Slash quote webhook keys are not configured');
        $slashQuoteFail(500, 'Slash quote webhook is not configured');
    }

    if (!$authenticator->verifyAuthKey($headers)) {
        $slashQuoteFail(401, 'Unauthorized');
    }

    $rawBody = file_get_contents('php://input');
    if (!is_string($rawBody) || trim($rawBody) === '') {
        $slashQuoteFail(400, 'Request body is required');
    }

    if (!$authenticator->verifySignature($headers, $rawBody)) {
        $slashQuoteFail(401, 'Unauthorized');
    }

    $payload = json_decode($rawBody, true);
    if (json_last_error() !== JSON_ERROR_NONE || !is_array($payload)) {
        $slashQuoteFail(400, 'Invalid JSON payload');
    }

    $form = is_array($payload['Data'] ?? null) ? $payload['Data'] : [];
    $readString = static function ($value) {
        return is_string($value) ? trim($value) : '';
    };

    $departureCode = strtoupper($readString($form['depCode'] ?? null));
    $destinationCode = strtoupper($readString($form['desCode'] ?? null));
    $airlineCode = strtoupper($readString($form['airlineCode'] ?? null));
    $departureDate = $readString($form['depDate'] ?? null);
    $returnDate = $readString($form['retDate'] ?? null);
    $serviceFee = is_numeric($form['serviceFee'] ?? null) ? (float) $form['serviceFee'] : 0;

    if ($departureDate === '') {
        $slashQuoteFail(400, 'Thiếu ngày đi');
    }
    if ($airlineCode === '') {
        $slashQuoteFail(400, 'Thiếu hãng bay');
    }

    require_once 'modules/EC_Airports/EC_Airports.php';

    $allAirports = EC_Airports::getAirportList(EC_Airports::AIRPORT_SCOPE_ALL);
    if (
        !array_key_exists($departureCode, $allAirports)
        || !array_key_exists($destinationCode, $allAirports)
    ) {
        $slashQuoteFail(400, 'Mã sân bay không được hỗ trợ');
    }

    $domesticAirports = EC_Airports::getAirportList(EC_Airports::AIRPORT_SCOPE_DOMESTIC);
    $isInternational = !array_key_exists($departureCode, $domesticAirports)
        || !array_key_exists($destinationCode, $domesticAirports);

    $searchMethod = $isInternational ? 'searchInterFlightBM' : 'searchFlightBM';

    require_once 'custom/entrypoints/entryFactory.php';

    $entryClass = entryFactory::create('entryFareSystemClass');
    if (!$entryClass || !method_exists($entryClass, $searchMethod)) {
        $slashQuoteFail(500, 'Unable to initialize Fare System service');
    }

    $response = $entryClass->$searchMethod([
        'airlineCode' => $airlineCode,
        'depCode' => $departureCode,
        'desCode' => $destinationCode,
        'departDate' => $departureDate,
        'returnDate' => $returnDate,
    ]);
    if (!is_string($response) || trim($response) === '') {
        $slashQuoteFail(502, 'Hệ thống giá vé không phản hồi');
    }

    $responseData = json_decode($response, true);
    if (json_last_error() !== JSON_ERROR_NONE || !is_array($responseData) || !array_key_exists('error', $responseData)) {
        $slashQuoteFail(502, 'Hệ thống giá vé trả về dữ liệu không hợp lệ');
    }
    if ((int) $responseData['error'] !== 0) {
        $slashQuoteFail(502, is_string($responseData['message'] ?? null) && $responseData['message'] !== ''
            ? $responseData['message']
            : 'Hệ thống giá vé báo lỗi');
    }

    require_once 'custom/include/utils/FlightQuoteHtml.php';

    $flights = FlightQuoteHtml::mapFlights($responseData['data'] ?? []);
    if (!$flights) {
        // Business-level miss, not a transport failure: chat shows `message` in
        // the preview panel and sends nothing to the conversation.
        $slashQuoteFail(200, 'Không tìm thấy chuyến bay phù hợp');
    }

    $html = FlightQuoteHtml::build([
        'depCode' => $departureCode,
        'desCode' => $destinationCode,
        'depDate' => $departureDate,
        'retDate' => $returnDate,
    ], $flights, $serviceFee);

    $slashQuoteSend(200, [
        'error' => 0,
        'type' => 'html',
        'data' => $html,
        'message' => '',
    ]);
} catch (Throwable $throwable) {
    $slashQuoteLog(sprintf(
        'Slash quote webhook failed: %s on line %d in %s',
        $throwable->getMessage(),
        $throwable->getLine(),
        $throwable->getFile()
    ));
    $slashQuoteFail(500, 'Internal server error');
}
