#!/bin/bash
set -e

APACHE_UID=${APACHE_UID:-1000}
APACHE_GID=${APACHE_GID:-1000}

# Mirror Rocky Linux server setup: PHP runs as the site owner (usertui),
# not as www-data. Here we create a matching user for the host user (ducpham)
# so all files written by Apache/PHP are owned by ducpham — same as usertui on server.
if ! getent group siteuser > /dev/null 2>&1; then
    groupadd -g "$APACHE_GID" siteuser
fi
if ! getent passwd siteuser > /dev/null 2>&1; then
    useradd -u "$APACHE_UID" -g "$APACHE_GID" -M -s /sbin/nologin siteuser
fi

# Mirror host: ducpham (uid 1000) is in the www-data group (gid 33),
# so siteuser must be too — otherwise PHP can't write to www-data-owned dirs like custom/.
usermod -aG www-data siteuser 2>/dev/null || true

# Run Apache as siteuser instead of www-data.
# /etc/apache2/envvars uses ${VAR:=default} — pre-exporting takes priority.
export APACHE_RUN_USER=siteuser
export APACHE_RUN_GROUP=siteuser

# Ensure runtime dirs exist.
mkdir -p \
    /var/www/html/cache/tmp \
    /var/www/html/cache/modules \
    /var/www/html/upload/import \
    /var/www/html/sessions

# Mirror server setgid setup: new files inside these dirs inherit the siteuser
# group automatically, so PHP-generated cache and session files end up owned
# by siteuser — same as usertui on the Rocky Linux server.
chown -R siteuser:siteuser \
    /var/www/html/cache \
    /var/www/html/sessions
chmod 2755 \
    /var/www/html/cache \
    /var/www/html/sessions

# SuiteCRM cron job running as siteuser — mirrors the server crontab for usertui.
# This ensures cache files generated by cron are owned by siteuser, not apache.
echo "* * * * * cd /var/www/html && php -f cron.php > /dev/null 2>&1" | crontab -u siteuser -
cron

exec apache2-foreground
