<?php

$dictionary['EC_Completed_Bookings'] = array(
    'table' => 'ec_completed_bookings',
    'audited' => true,
    'inline_edit' => true,
    'duplicate_merge' => true,
    'fields' => array(
        'ec_flight_bookings_id_c' =>
        array(
            'required' => false,
            'name' => 'ec_flight_bookings_id_c',
            'vname' => '',
            'type' => 'id',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => 0,
            'audited' => 0,
            'reportable' => 0,
            'len' => 36,
        ),
        'booking_name' =>
        array(
            'required' => false,
            'source' => 'non-db',
            'name' => 'booking_name',
            'vname' => 'LBL_BOOKING_NAME',
            'type' => 'relate',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 1,
            'reportable' => 0,
            'len' => '255',
            'id_name' => 'ec_flight_bookings_id_c',
            'ext2' => 'EC_Flight_Bookings',
            'module' => 'EC_Flight_Bookings',
            'rname' => 'name',
            'quicksearch' => 'enabled',
            'studio' => 'visible',
        ),
        'completed_bk_type' =>
        array(
            'required' => false,
            'name' => 'completed_bk_type',
            'vname' => 'LBL_COMPLETED_BK_TYPE',
            'type' => 'enum',
            'massupdate' => 0,
            'default' => 'EXP_BK',
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 1,
            'reportable' => 0,
            'len' => 100,
            'options' => 'completed_bk_type_list',
            'studio' => 'visible',
            'dependency' => false,
        ),
        'bk_status' =>
        array(
            'required' => false,
            'name' => 'bk_status',
            'vname' => 'LBL_BK_STATUS',
            'type' => 'enum',
            'massupdate' => 0,
            'default' => '1',
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 0,
            'reportable' => 0,
            'len' => 100,
            'options' => 'booking_status_list',
            'studio' => 'visible',
            'dependency' => false,
        ),
        'bk_mark' =>
        array(
            'required' => false,
            'name' => 'bk_mark',
            'vname' => 'LBL_BK_MARK',
            'type' => 'int',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 0,
            'reportable' => 0,
            'len' => '11',
            'disable_num_format' => '',
        ),
        'ticket_qty' =>
        array(
            'required' => false,
            'name' => 'ticket_qty',
            'vname' => 'LBL_TICKET_QTY',
            'type' => 'int',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 0,
            'reportable' => 0,
            'len' => '5',
            'disable_num_format' => '',
        ),
        'total_amount' =>
        array(
            'required' => false,
            'name' => 'total_amount',
            'vname' => 'LBL_TOTAL_AMOUNT',
            'type' => 'currency',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 1,
            'reportable' => 0,
            'len' => 26,
        ),
        'bonus' =>
        array(
            'required' => false,
            'name' => 'bonus',
            'vname' => 'LBL_BONUS',
            'type' => 'currency',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 1,
            'reportable' => 0,
            'len' => 26,
        ),
        'init_called_time' =>
        array(
            'required' => false,
            'name' => 'init_called_time',
            'vname' => 'LBL_INIT_CALLED_TIME',
            'type' => 'date',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 1,
            'reportable' => 0,
        ),
        'completed_time' =>
        array(
            'required' => false,
            'name' => 'completed_time',
            'vname' => 'LBL_COMPLETED_TIME',
            'type' => 'date',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 1,
            'reportable' => 0,
        ),
        'payment_time' =>
        array(
            'required' => false,
            'name' => 'payment_time',
            'vname' => 'LBL_PAYMENT_TIME',
            'type' => 'date',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 1,
            'reportable' => 0,
        ),
    ),
    'relationships' => array (
),
    'optimistic_locking' => true,
    'unified_search' => true,
);
if (!class_exists('VardefManager')) {
        require_once('include/SugarObjects/VardefManager.php');
}
VardefManager::createVardef('EC_Completed_Bookings', 'EC_Completed_Bookings', array('basic','assignable','security_groups'));
