<?php
$dictionary['EC_Zalo'] = array(
    'table' => 'ec_zalo',
    'audited' => true,
    'inline_edit' => true,
    'duplicate_merge' => true,
    'fields' => array(
        'oa_alias' => array(
            'name' => 'oa_alias',
            'vname' => 'LBL_OA_ALIAS',
            'type' => 'varchar',
            'len' => 50,
            'required' => 0,
            'audited' => 1,
        ),
        'oa_type' => array(
            'name' => 'oa_type',
            'vname' => 'LBL_OA_TYPE',
            'type' => 'tinyint',
            'len' => 1,
            'required' => false,
            'audited' => 1,
        ),
        'cate_name' => array(
            'name' => 'cate_name',
            'vname' => 'LBL_CATE_NAME',
            'type' => 'varchar',
            'len' => 50,
            'required' => false,
            'audited' => 1,
        ),
        'is_verified' => array(
            'name' => 'is_verified',
            'vname' => 'LBL_IS_VERIFIED',
            'type' => 'bool',
            'default' => 0,
            'audited' => 1,
        ),
        'num_follower' => array(
            'name' => 'num_follower',
            'vname' => 'LBL_NUM_FOLLOWER',
            'type' => 'int',
            'required' => false,
            'audited' => 1,
        ),
        'avatar' => array(
            'name' => 'avatar',
            'vname' => 'LBL_AVATAR',
            'type' => 'varchar',
            'len' => 100,
            'comment' => 'Link to OA avatar',
            'required' => false,
            'audited' => 1,
        ),
        'cover' => array(
            'name' => 'cover',
            'vname' => 'LBL_COVER',
            'type' => 'varchar',
            'len' => 100,
            'comment' => 'Link to OA cover photo',
            'required' => 0,
            'audited' => 1,
        ),
        'package_name' => array(
            'name' => 'package_name',
            'vname' => 'LBL_PACKAGE_NAME',
            'type' => 'varchar',
            'len' => 50,
            'required' => false,
            'audited' => 1,
        ),
        'package_valid_through_date' => array(
            'name' => 'package_valid_through_date',
            'vname' => 'LBL_PACKAGE_VALID_THROUGH_DATE',
            'type' => 'date',
            'required' => false,
            'audited' => 1,
        ),
        'package_auto_renew_date' => array(
            'name' => 'package_auto_renew_date',
            'vname' => 'LBL_PACKAGE_AUTO_RENEW_DATE',
            'type' => 'date',
            'required' => false,
            'audited' => 1,
        ),
        'linked_zca' => array(
            'name' => 'linked_zca',
            'vname' => 'LBL_LINKED_ZCA',
            'type' => 'varchar',
            'len' => 24,
            'required' => false,
            'audited' => 1,
        ),
        'quota_info' => array(
            'name' => 'quota_info',
            'vname' => 'LBL_QUOTA_INFO',
            'type' => 'varchar',
            'len' => 1024,
            'comment' => 'Contain json string of quota OA',
            'required' => 0,
            'audited' => 1,
        ),
        'secret_key' => array(
            'name' => 'secret_key',
            'vname' => 'LBL_SECRET_KEY',
            'type' => 'varchar',
            'len' => 32,
            'required' => 0,
            'audited' => 1,
        ),
    ),
    'relationships' => array(),
    'optimistic_locking' => true,
    'unified_search' => true,
);
if (!class_exists('VardefManager')) {
    require_once('include/SugarObjects/VardefManager.php');
}
VardefManager::createVardef('EC_Zalo', 'EC_Zalo', array('basic', 'assignable', 'security_groups'));
