<?php
$dictionary['Alert'] = array(
    'table' => 'alerts',
    'audited' => false,
    'duplicate_merge' => true,
    'fields' => array(
        'is_read' =>
        array(
            'name'        => 'is_read',
            'vname'     => 'LBL_IS_READ',
            'type'        => 'bool',
            'massupdate' => false,
            'studio'     => 'false',
            'default'       => '0',
        ),
        'target_module' =>
        array(
            'name'        => 'target_module',
            'vname'     => 'LBL_TYPE',
            'type'        => 'varchar',
            'massupdate' => false,
            'studio' => 'false',
        ),
        'type' => array(
            'name'        => 'type',
            'vname'     => 'LBL_TYPE',
            'massupdate' => false,
            'studio' => 'false',
            'type' => 'enum',
            'options' => 'alert_type_list',
            'len' => 100,
            'audited' => true,
        ),
        'url_redirect' =>
        array(
            'name'        => 'url_redirect',
            'vname'     => 'LBL_TYPE',
            'type'        => 'varchar',
            'massupdate' => false,
            'studio' => 'false',
        ),
        'reminder_id' =>
        array(
            'name'        => 'reminder_id',
            'type' => 'id',
            'required' => false,
            'reportable' => false,
            'studio' => 'false',
            'comment' => 'The id of the reminder that created this alert',
        ),

        // custom
        'alert_photo' => array(
            'name' => 'alert_photo',
            'vname' => 'LBL_ALERT_PHOTO',
            'type' => 'image',
            'massupdate' => false,
            'comments' => '',
            'help' => '',
            'importable' => false,
            'border' => true,
            'reportable' => true,
            'len' => 255,
            'dbType' => 'varchar',
            'width' => '500',
            'height' => 'auto',
        ),
        'filename' => array(
            'name' => 'filename',
            'vname' => 'LBL_FILENAME',
            'type' => 'file',
            'dbType' => 'varchar',
            'len' => '255',
            'reportable' => true,
            'comment' => 'File name associated with the alert (attachment)',
            'importable' => false,
        ),
        'parent_type' =>
        array(
            'required' => false,
            'name' => 'parent_type',
            'vname' => 'LBL_PARENT_TYPE',
            'type' => 'parent_type',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'false',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => 0,
            'audited' => 0,
            'reportable' => 0,
            'len' => 100,
            'dbType' => 'varchar',
        ),
        'parent_id' =>
        array(
            'required' => false,
            'name' => 'parent_id',
            'vname' => 'LBL_PARENT_ID',
            'type' => 'id',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'false',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => 0,
            'audited' => 0,
            'reportable' => 0,
            'len' => 36,
        ),
        'parent_alert_id' => array(
            'required' => false,
            'name' => 'parent_alert_id',
            'vname' => 'LBL_PARENT_ALERT_ID',
            'type' => 'id',
            'massupdate' => 0,
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => 0,
            'audited' => 0,
            'reportable' => 0,
            'len' => 36,
            'comment' => 'Khi tạo nhiều alert 1 lúc. Alert tạo đầu tiên được tạo sẽ là parent_alert.',
        ),
        'priority' => array(
            'name' => 'priority',
            'vname' => 'LBL_PRIORITY',
            'type' => 'enum',
            'options' => 'alert_priority_list',
            'len' => 100,
            'audited' => true,
            'comment' => 'The priority of the alert',
        ),
        'viewed_at' => array(
            'required' => false,
            'name' => 'viewed_at',
            'vname' => 'LBL_VIEWED_AT',
            'type' => 'datetime',
            'dbType' => 'datetime',
            'comment' => 'Time when the alert was viewed',
        ),
    ),
    'relationships' => array(),
    'optimistic_locking' => true,
    'unified_search' => false,
);
if (!class_exists('VardefManager')) {
    require_once('include/SugarObjects/VardefManager.php');
}
VardefManager::createVardef('Alerts', 'Alert', array('basic', 'assignable'));
