<?php
$popupMeta = array(
    'moduleMain' => 'EC_Flight_Bookings',
    'varName' => 'EC_Flight_Bookings',
    'orderBy' => 'ec_flight_bookings.name',
    'whereClauses' => array(
        'name' => 'ec_flight_bookings.name',
        'contact_name' => 'ec_flight_bookings.contact_name',
        'phone' => 'ec_flight_bookings.phone',
        'email' => 'ec_flight_bookings.email',
        'pnr_outbound_search' => 'ec_flight_bookings.pnr_outbound_search',
        'pnr_inbound_search' => 'ec_flight_bookings.pnr_inbound_search',
        'date_entered' => 'ec_flight_bookings.date_entered',
        'date_ticket_issue' => 'ec_flight_bookings.date_ticket_issue',
        'total_amount' => 'ec_flight_bookings.total_amount',
        'ip_address' => 'ec_flight_bookings.ip_address',
        'assigned_user_name' => 'ec_flight_bookings.assigned_user_name',
        'departure_date' => 'ec_flight_bookings.departure_date',
        'created_by_name' => 'ec_flight_bookings.created_by_name',
        'payment_type' => 'ec_flight_bookings.payment_type',
        'booking_status' => 'ec_flight_bookings.booking_status',
    ),
    'searchInputs' => array(
        1 => 'name',
        4 => 'contact_name',
        5 => 'phone',
        6 => 'email',
        7 => 'pnr_outbound_search',
        8 => 'pnr_inbound_search',
        9 => 'date_entered',
        10 => 'date_ticket_issue',
        11 => 'total_amount',
        12 => 'ip_address',
        13 => 'assigned_user_name',
        14 => 'departure_date',
        15 => 'created_by_name',
        16 => 'payment_type',
        17 => 'booking_status',
    ),
    'searchdefs' => array(
        'name' => array(
            'name' => 'name',
            'width' => '10%',
        ),
        'contact_name' => array(
            'type' => 'varchar',
            'label' => 'LBL_CONTACT_NAME',
            'width' => '10%',
            'name' => 'contact_name',
        ),
        'phone' => array(
            'type' => 'phone',
            'label' => 'LBL_PHONE',
            'width' => '10%',
            'name' => 'phone',
        ),
        'email' => array(
            'type' => 'varchar',
            'label' => 'LBL_EMAIL',
            'width' => '10%',
            'name' => 'email',
        ),
        'pnr_outbound_search' => array(
            'type' => 'varchar',
            'label' => 'LBL_PNR_OUTBOUND_SEARCH',
            'width' => '10%',
            'name' => 'pnr_outbound_search',
        ),
        'pnr_inbound_search' => array(
            'type' => 'varchar',
            'label' => 'LBL_PNR_INBOUND_SEARCH',
            'width' => '10%',
            'name' => 'pnr_inbound_search',
        ),

        'date_entered' => array(
            'type' => 'datetime',
            'label' => 'LBL_DATE_ENTERED',
            'width' => '10%',
            'name' => 'date_entered',
        ),
        'date_ticket_issue' => array(
            'type' => 'date',
            'label' => 'LBL_DATE_TICKET_ISSUE',
            'width' => '10%',
            'name' => 'date_ticket_issue',
        ),
        'departure_date' => array(
            'type' => 'datetime',
            'label' => 'LBL_DEPARTURE_DATE',
            'width' => '10%',
            'name' => 'departure_date',
        ),
        'ip_address' => array(
            'type' => 'varchar',
            'label' => 'LBL_IP_ADDRESS',
            'width' => '10%',
            'name' => 'ip_address',
        ),
        'total_amount' => array(
            'type' => 'currency',
            'label' => 'LBL_TOTAL_AMOUNT',
            'currency_format' => true,
            'width' => '10%',
            'name' => 'total_amount',
        ),
        'assigned_user_name' => array(
            'link' => 'assigned_user_link',
            'type' => 'relate',
            'label' => 'LBL_ASSIGNED_TO_NAME',
            'width' => '10%',
            'name' => 'assigned_user_name',
        ),
        'created_by_name' => array(
            'type' => 'relate',
            'link' => 'created_by_link',
            'label' => 'LBL_CREATED',
            'width' => '10%',
            'name' => 'created_by_name',
        ),
        'payment_type' => array(
            'type' => 'enum',
            'studio' => 'visible',
            'label' => 'LBL_PAYMENT_TYPE',
            'width' => '10%',
            'name' => 'payment_type',
        ),
        'booking_status' => array(
            'type' => 'enum',
            'studio' => 'visible',
            'label' => 'LBL_BOOKING_STATUS',
            'width' => '10%',
            'name' => 'booking_status',
        ),
    ),
);
