<?php
$dictionary['EC_Revenue'] = array(
    'table' => 'ec_revenue',
    'audited' => true,
    'inline_edit' => true,
    'duplicate_merge' => true,
    'fields' => array(
        'booking_id' => array(
            'required'  => true,
            'name'      => 'booking_id',
            'vname'     => '',
            'type'      => 'id',
            'len'       => 36,
            'default'   => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => 0,
            'audited' => 0,
            'reportable' => 0,
        ),
        'booking_name' => array(
            'source' => 'non-db',
            'name'   => 'booking_name',
            'vname'  => 'LBL_BOOKING_NAME',
            'type'   => 'relate',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => ' ',
            'audited' => 1,
            'reportable' => 0,
            'id_name' => 'booking_id',
            'ext2' => 'EC_Flight_Bookings',
            'module' => 'EC_Flight_Bookings',
            'rname' => 'name',
            'quicksearch' => 'enabled',
        ),
        'date_entered_bk' => array(
            'require' => false,
            'name'       => 'date_entered_bk',
            'vname'      => 'LBL_DATE_ENTERED_BK',
            'type'       => 'datetime',
            'comments'   => 'Ngày đặt vé',
            'importable' => true,
            'reportable' => false,
            'audited'    => 1,
        ),
        'date_ticket_issue' => array(
            'require' => false,
            'name'       => 'date_ticket_issue',
            'vname'      => 'LBL_DATE_TICKET_ISSUE',
            'type'       => 'date',
            'comments'   => 'Ngày xuất vé',
            'importable' => true,
            'reportable' => false,
            'audited'    => 1,
        ),
        'ticket_type' => array(
            'require' => false,
            'name'       => 'ticket_type',
            'vname'      => 'LBL_TICKET_TYPE',
            'type'       => 'enum',
            'dbtype'     => 'char',
            'options'    => 'booking_ticket_type_list',
            'len'        => 1,
            'comments'   => '1: Nội địa / 2: Quốc tế',
            'default'    => 1,
            'audited' => 1,
        ),
        'ticket_qty' => array(
            'name'       => 'ticket_qty',
            'vname'      => 'LBL_TICKET_QTY',
            'type'       => 'int',
            'comments'   => 'Tổng số vé bk',
            'default'    => 0,
            'importable' => true,
            'reportable' => false,
            'audited' => 1,
        ),
        'is_prior' => array(
            'require' => false,
            'name'       => 'is_prior',
            'vname'      => 'LBL_IS_PRIOR',
            'type'       => 'bool',
            'len'        => 1,
            'default'    => 0,
            'comments'   => 'Là vé cận?',
            'importable' => true,
            'reportable' => false,
        ),
        'total_amount_bk' => array(
            'require' => false,
            'name'       => 'total_amount_bk',
            'vname'      => 'LBL_TOTAL_AMOUNT_BK',
            'type'       => 'currency',
            'comments'   => 'Tổng tiền trong booking (Đã bao gồm hành lý)',
            'len'        => 26,
            'default'    => 0,
            'importable' => true,
            'reportable' => false,
            'audited' => 1,
        ),
        'total_amount_points' => array(
            'require' => false,
            'name'       => 'total_amount_points',
            'vname'      => 'LBL_TOTAL_AMOUNT_POINTS',
            'type'       => 'currency',
            'comments'   => 'Tiền giảm giá sử dụng điểm tích lũy. Vì sử dụng discount nên làm giảm total_amount_bk.',
            'len'        => 26,
            'default'    => 0,
            'importable' => true,
            'reportable' => false,
            'audited' => 1,
        ),
        'total_amount_brand_refunded' => array(
            'require' => false,
            'name'       => 'total_amount_brand_refunded',
            'vname'      => 'LBL_TOTAL_AMOUNT_BRAND_REFUNDED',
            'type'       => 'currency',
            'comments'   => 'Tiền hãng hoàn vé là khoản tongtienhang',
            'len'        => 26,
            'default'    => 0,
            'importable' => true,
            'reportable' => false,
            'audited' => 1,
        ),
        'total_amount_receipt' => array(
            'require' => false,
            'name'       => 'total_amount_receipt',
            'vname'      => 'LBL_TOTAL_AMOUNT_RECEIPT',
            'type'       => 'currency',
            'comments'   => 'GIÁ bán Đổi giờ bay, hành trình, tên khách, phí mua hành lý, mua ghế (Loại thu 4, 5)',
            'len'        => 26,
            'default'    => 0,
            'importable' => true,
            'reportable' => false,
            'audited' => 1,
        ),
        'total_amount' => array(
            'require' => false,
            'name'       => 'total_amount',
            'vname'      => 'LBL_TOTAL_AMOUNT',
            'type'       => 'currency',
            'comments'   => 'Tổng doanh thu = total_amount_bk + total_amount_points + total_amount_brand_refunded + total_amount_receipt',
            'len'        => 26,
            'default'    => 0,
            'importable' => true,
            'reportable' => false,
            'audited' => 1,
        ),
        'total_purchase_booking' => array(
            'require' => false,
            'name'       => 'total_purchase_booking',
            'vname'      => 'LBL_TOTAL_PURCHASE_BOOKING',
            'type'       => 'currency',
            'comments'   => 'Giá mua BK',
            'len'        => 26,
            'default'    => 0,
            'importable' => true,
            'reportable' => false,
            'audited' => 1,
        ),
        'total_purchase_pass_refunded' => array(
            'require' => false,
            'name'       => 'total_purchase_pass_refunded',
            'vname'      => 'LBL_TOTAL_PURCHASE_PASS_REFUNDED',
            'type'       => 'currency',
            'comments'   => 'Tiền hoàn lại cho khách (Nếu bk đó bị hoàn vé - tongtienkhach)',
            'len'        => 26,
            'default'    => 0,
            'importable' => true,
            'reportable' => false,
            'audited' => 1,
        ),
        'total_purchase_points_refunded' => array(
            'require' => false,
            'name'       => 'total_purchase_points_refunded',
            'vname'      => 'LBL_TOTAL_PURCHASE_POINTS_REFUNDED',
            'type'       => 'currency',
            'comments'   => 'Tiền giảm giá sử dụng điểm tích lũy mà bị hoàn lại. UP',
            'len'        => 26,
            'default'    => 0,
            'importable' => true,
            'reportable' => false,
            'audited' => 1,
        ),
        'total_purchase_receipt' => array(
            'require' => false,
            'name'       => 'total_purchase_receipt',
            'vname'      => 'LBL_TOTAL_PURCHASE_RECEIPT',
            'type'       => 'currency',
            'comments'   => 'GIÁ MUA Đổi giờ bay, hành trình, tên khách, phí mua hành lý, mua ghế (Loại thu 4, 5)',
            'len'        => 26,
            'default'    => 0,
            'importable' => true,
            'reportable' => false,
            'audited' => 1,
        ),
        'total_purchase' => array(
            'require' => false,
            'name'       => 'total_purchase',
            'vname'      => 'LBL_TOTAL_PURCHASE',
            'type'       => 'currency',
            'comments'   => 'Tổng tiền mua = total_purchase_booking + giá mua hành lý bên trong booking + total_purchase_points_refunded + total_purchase_pass_refunded + total_purchase_receipt',
            'len'        => 26,
            'default'    => 0,
            'importable' => true,
            'reportable' => false,
            'audited' => 1,
        ),
        'total_profit' => array(
            'require' => false,
            'name'       => 'total_profit',
            'vname'      => 'LBL_TOTAL_PROFIT',
            'type'       => 'currency',
            'comments'   => 'Lợi nhuận = total_amount - total_purchase',
            'len'        => 26,
            'default'    => 0,
            'importable' => true,
            'reportable' => false,
            'audited' => 1,
        ),
    ),
    'indices' => array(
        array('name' => 'idx_rv_bkid', 'type' => 'index', 'fields' => array('booking_id')),
        array('name' => 'idx_rv_assign', 'type' => 'index', 'fields' => array('assigned_user_id')),
        array('name' => 'idx_rv_date_ticket_issue', 'type' => 'index', 'fields' => array('date_ticket_issue')),
        array(
            'name' => 'idx_rv_deleted_bkid_cover',
            'type' => 'index',
            'fields' => array('deleted', 'booking_id', 'total_amount', 'total_profit')
        ),
    ),
    'relationships' => array(),
    'optimistic_locking' => true,
    'unified_search' => true,
);
if (!class_exists('VardefManager')) {
    require_once('include/SugarObjects/VardefManager.php');
}
VardefManager::createVardef('EC_Revenue', 'EC_Revenue', array('basic', 'assignable', 'security_groups'));
