<?php
$dictionary['EC_Booking_Bonus'] = array(
    'table' => 'ec_booking_bonus',
    'audited' => true,
    'inline_edit' => true,
    'duplicate_merge' => true,
    'fields' => array(
        // One record per (booking, user): assigned_user_id is the user earning the bonus
        'booking_id' => array(
            'required'  => true,
            'name'      => 'booking_id',
            'vname'     => '',
            'type'      => 'id',
            'len'       => 36,
            'default'   => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => 0,
            'audited' => 0,
            'reportable' => 0,
        ),
        'booking_name' => array(
            'source' => 'non-db',
            'name'   => 'booking_name',
            'vname'  => 'LBL_BOOKING_NAME',
            'type'   => 'relate',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => ' ',
            'audited' => 1,
            'reportable' => 0,
            'id_name' => 'booking_id',
            'ext2' => 'EC_Flight_Bookings',
            'module' => 'EC_Flight_Bookings',
            'rname' => 'name',
            'quicksearch' => 'enabled',
        ),
        'flight_date' => array(
            'require'    => false,
            'name'       => 'flight_date',
            'vname'      => 'LBL_FLIGHT_DATE',
            'type'       => 'datetime',
            'comments'   => 'Last flight departure datetime (VN timezone), the report date dimension',
            'importable' => true,
            'reportable' => false,
            'audited'    => 1,
        ),
        'is_inter' => array(
            'require'    => false,
            'name'       => 'is_inter',
            'vname'      => 'LBL_IS_INTER',
            'type'       => 'bool',
            'len'        => 1,
            'default'    => 0,
            'comments'   => 'International ticket?',
            'importable' => true,
            'reportable' => false,
        ),
        'ticket_qty' => array(
            'name'       => 'ticket_qty',
            'vname'      => 'LBL_TICKET_QTY',
            'type'       => 'int',
            'comments'   => 'Total ticket quantity of the booking',
            'default'    => 0,
            'importable' => true,
            'reportable' => false,
            'audited'    => 1,
        ),
        'total_revenue' => array(
            'require'    => false,
            'name'       => 'total_revenue',
            'vname'      => 'LBL_TOTAL_REVENUE',
            'type'       => 'currency',
            'comments'   => 'Booking revenue used for the bonus calculation',
            'len'        => 26,
            'default'    => 0,
            'importable' => true,
            'reportable' => false,
            'audited'    => 1,
        ),
        'total_cost' => array(
            'require'    => false,
            'name'       => 'total_cost',
            'vname'      => 'LBL_TOTAL_COST',
            'type'       => 'currency',
            'comments'   => 'Booking cost (bought price + luggage + fees)',
            'len'        => 26,
            'default'    => 0,
            'importable' => true,
            'reportable' => false,
            'audited'    => 1,
        ),
        'total_profit' => array(
            'require'    => false,
            'name'       => 'total_profit',
            'vname'      => 'LBL_TOTAL_PROFIT',
            'type'       => 'currency',
            'comments'   => 'Profit = total_revenue - total_cost',
            'len'        => 26,
            'default'    => 0,
            'importable' => true,
            'reportable' => false,
            'audited'    => 1,
        ),
        'avg_profit' => array(
            'require'    => false,
            'name'       => 'avg_profit',
            'vname'      => 'LBL_AVG_PROFIT',
            'type'       => 'currency',
            'comments'   => 'Profit per ticket = total_profit / ticket_qty',
            'len'        => 26,
            'default'    => 0,
            'importable' => true,
            'reportable' => false,
            'audited'    => 1,
        ),
        'min_threshold_value' => array(
            'require'    => false,
            'name'       => 'min_threshold_value',
            'vname'      => 'LBL_MIN_THRESHOLD_VALUE',
            'type'       => 'currency',
            'comments'   => 'Minimum avg profit per ticket required to earn a bonus',
            'len'        => 26,
            'default'    => 0,
            'importable' => true,
            'reportable' => false,
        ),
        'extra_threshold_value' => array(
            'require'    => false,
            'name'       => 'extra_threshold_value',
            'vname'      => 'LBL_EXTRA_THRESHOLD_VALUE',
            'type'       => 'currency',
            'comments'   => 'Avg profit per ticket above which the extra bonus percent applies',
            'len'        => 26,
            'default'    => 0,
            'importable' => true,
            'reportable' => false,
        ),
        'bonus_percent' => array(
            'require'    => false,
            'name'       => 'bonus_percent',
            'vname'      => 'LBL_BONUS_PERCENT',
            'type'       => 'decimal',
            'len'        => '8,4',
            'default'    => 0,
            'comments'   => 'Bonus rate as a fraction (0.2 = 20%)',
            'importable' => true,
            'reportable' => false,
        ),
        'extra_bonus_percent' => array(
            'require'    => false,
            'name'       => 'extra_bonus_percent',
            'vname'      => 'LBL_EXTRA_BONUS_PERCENT',
            'type'       => 'decimal',
            'len'        => '8,4',
            'default'    => 0,
            'comments'   => 'Extra bonus rate as a fraction (0.3 = 30%)',
            'importable' => true,
            'reportable' => false,
        ),
        'bonus_per_ticket' => array(
            'require'    => false,
            'name'       => 'bonus_per_ticket',
            'vname'      => 'LBL_BONUS_PER_TICKET',
            'type'       => 'currency',
            'comments'   => 'Bonus amount per ticket',
            'len'        => 26,
            'default'    => 0,
            'importable' => true,
            'reportable' => false,
        ),
        'total_direct_bonus' => array(
            'require'    => false,
            'name'       => 'total_direct_bonus',
            'vname'      => 'LBL_TOTAL_DIRECT_BONUS',
            'type'       => 'currency',
            'comments'   => 'Booking-level direct bonus pool (70% of total bonus)',
            'len'        => 26,
            'default'    => 0,
            'importable' => true,
            'reportable' => false,
            'audited'    => 1,
        ),
        'total_indirect_bonus' => array(
            'require'    => false,
            'name'       => 'total_indirect_bonus',
            'vname'      => 'LBL_TOTAL_INDIRECT_BONUS',
            'type'       => 'currency',
            'comments'   => 'Booking-level indirect bonus pool (30% of total bonus)',
            'len'        => 26,
            'default'    => 0,
            'importable' => true,
            'reportable' => false,
            'audited'    => 1,
        ),
        'total_indirect_kpi' => array(
            'require'    => false,
            'name'       => 'total_indirect_kpi',
            'vname'      => 'LBL_TOTAL_INDIRECT_KPI',
            'type'       => 'int',
            'default'    => 0,
            'comments'   => 'Booking-level total KPI shared for the indirect bonus',
            'importable' => true,
            'reportable' => false,
        ),
        'kpi' => array(
            'require'    => false,
            'name'       => 'kpi',
            'vname'      => 'LBL_KPI',
            'type'       => 'int',
            'default'    => 0,
            'comments'   => 'KPI count of this user on this booking',
            'importable' => true,
            'reportable' => false,
            'audited'    => 1,
        ),
        'direct_bonus' => array(
            'require'    => false,
            'name'       => 'direct_bonus',
            'vname'      => 'LBL_DIRECT_BONUS',
            'type'       => 'currency',
            'comments'   => 'Direct bonus of this user (booking completer)',
            'len'        => 26,
            'default'    => 0,
            'importable' => true,
            'reportable' => false,
            'audited'    => 1,
        ),
        'indirect_bonus' => array(
            'require'    => false,
            'name'       => 'indirect_bonus',
            'vname'      => 'LBL_INDIRECT_BONUS',
            'type'       => 'currency',
            'comments'   => 'Indirect bonus of this user (per KPI share)',
            'len'        => 26,
            'default'    => 0,
            'importable' => true,
            'reportable' => false,
            'audited'    => 1,
        ),
        'total_bonus' => array(
            'require'    => false,
            'name'       => 'total_bonus',
            'vname'      => 'LBL_TOTAL_BONUS',
            'type'       => 'currency',
            'comments'   => 'Total bonus of this user = direct_bonus + indirect_bonus',
            'len'        => 26,
            'default'    => 0,
            'importable' => true,
            'reportable' => false,
            'audited'    => 1,
        ),
    ),
    'indices' => array(
        array('name' => 'idx_bkb_booking_user', 'type' => 'index', 'fields' => array('booking_id', 'assigned_user_id')),
        array('name' => 'idx_bkb_assign', 'type' => 'index', 'fields' => array('assigned_user_id')),
        array('name' => 'idx_bkb_flight_date', 'type' => 'index', 'fields' => array('flight_date')),
        array(
            'name' => 'idx_bkb_deleted_flight_cover',
            'type' => 'index',
            'fields' => array('deleted', 'flight_date', 'assigned_user_id', 'total_bonus')
        ),
    ),
    'relationships' => array(),
    'optimistic_locking' => true,
    'unified_search' => true,
);
if (!class_exists('VardefManager')) {
    require_once('include/SugarObjects/VardefManager.php');
}
VardefManager::createVardef('EC_Booking_Bonus', 'EC_Booking_Bonus', array('basic', 'assignable', 'security_groups'));
