<?php
    if (!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');
    function generateXLSTemplate($data) {
        $xls = "
        <html 
            xmlns:o=\"urn:schemas-microsoft-com:office:office\"
            xmlns:x=\"urn:schemas-microsoft-com:office:excel\"
            xmlns=\"http://www.w3.org/TR/REC-html40\">
            <head>
                <meta http-equiv=Content-Type content=\"text/html; charset=windows-1252\">
                <meta name=ProgId content=Excel.Sheet>
                <meta name=Generator content=\"Microsoft Excel 12\">
                <link rel=File-List href=\"doanhthubanve_files/filelist.xml\">
                <style id=\"doanhthubanve_24108_Styles\">
            </head>

            <body>
                <!--[if !excel]>&nbsp;&nbsp;<![endif]-->
                <!--The following information was generated by Microsoft Office Excel's Publish
                as Web Page wizard.-->
                <!--If the same item is republished from Excel, all information between the DIV
                tags will be replaced.-->
                <!----------------------------->
                <!--START OF OUTPUT FROM EXCEL PUBLISH AS WEB PAGE WIZARD -->
                <!----------------------------->
                <div id=\"congnophaitra\" align=center x:publishsource=\"Excel\">";

                $xls .= $data;

                $xls .= "</div>
                <!----------------------------->
                <!--END OF OUTPUT FROM EXCEL PUBLISH AS WEB PAGE WIZARD-->
                <!----------------------------->
            </body>
        </html>";

        return $xls;
    }