<?php
$dictionary['EC_ChuyenTienNoiBo'] = array(
    'table' => 'ec_chuyentiennoibo',
    'audited' => true,
    'fields' => 
    array(
        'ngaychungtu' => array(
            'required' => '1',
            'name' => 'ngaychungtu',
            'vname' => 'LBL_NGAYCHUNGTU',
            'type' => 'date',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '',
            'audited' => 1,
            'reportable' => 0,
            'display_default' => 'now',
        ),

        'ngayhachtoan' => array(
            'required' => '1',
            'name' => 'ngayhachtoan',
            'vname' => 'LBL_NGAYHACHTOAN',
            'type' => 'datetimecombo',
            'dbType' => 'datetime',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '',
            'audited' => 1,
            'reportable' => 0,
        ),

        'tutknganhang_id' => array(
            'required' => false,
            'name' => 'tutknganhang_id',
            'vname' => '',
            'type' => 'id',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => 0,
            'audited' => 1,
            'reportable' => 0,
            'len' => 36,
        ),

        'tutknganhang' => array(
            'required' => '1',
            'source' => 'non-db',
            'name' => 'tutknganhang',
            'vname' => 'LBL_TUTKNGANHANG',
            'type' => 'relate',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '',
            'audited' => 1,
            'reportable' => 0,
            'len' => '255',
            'id_name' => 'tutknganhang_id',
            'ext2' => 'EC_Bank_Account',
            'module' => 'EC_Bank_Account',
            'rname' => 'name',
            'quicksearch' => 'enabled',
            'studio' => 'visible',
        ),

        'dentknganhang_id' => array(
            'required' => false,
            'name' => 'dentknganhang_id',
            'vname' => '',
            'type' => 'id',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => 0,
            'audited' => 1,
            'reportable' => 0,
            'len' => 36,
        ),

        'dentknganhang' => array(
            'required' => '1',
            'source' => 'non-db',
            'name' => 'dentknganhang',
            'vname' => 'LBL_DENTKNGANHANG',
            'type' => 'relate',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '',
            'audited' => 1,
            'reportable' => 0,
            'len' => '255',
            'id_name' => 'dentknganhang_id',
            'ext2' => 'EC_Bank_Account',
            'module' => 'EC_Bank_Account',
            'rname' => 'name',
            'quicksearch' => 'enabled',
            'studio' => 'visible',
        ),

        'loaitien' => array(
            'required' => false,
            'name' => 'loaitien',
            'vname' => 'LBL_LOAITIEN',
            'type' => 'enum',
            'massupdate' => 0,
            'default' => 'VND',
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '',
            'audited' => 1,
            'reportable' => 0,
            'len' => 100,
            'options' => 'loaitien_list',
            'studio' => 'visible',
            'dependency' => false,
        ),

        'sotien' => array(
            'required' => '1',
            'name' => 'sotien',
            'vname' => 'LBL_SOTIEN',
            'type' => 'currency',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '',
            'audited' => 1,
            'reportable' => 0,
            'len' => 26,
        ),

        'ghiso' => array(
            'required' => false,
            'name' => 'ghiso',
            'vname' => 'LBL_GHISO',
            'type' => 'bool',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '',
            'audited' => 1,
            'reportable' => 0,
            'len' => '255',
        ),

        'tutienmat' => array(
            'required' => false,
            'name' => 'tutienmat',
            'vname' => 'LBL_TUTIENMAT',
            'type' => 'bool',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => ' ',
            'audited' => 1,
            'reportable' => 0,
            'len' => '255',
        ),

        'dentienmat' => array(
            'required' => false,
            'name' => 'dentienmat',
            'vname' => 'LBL_DENTIENMAT',
            'type' => 'bool',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => ' ',
            'audited' => 1,
            'reportable' => 0,
            'len' => '255',
        ),

        'tudiadiem_id' => array(
            'required' => false,
            'name' => 'tudiadiem_id',
            'vname' => '',
            'type' => 'id',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => 0,
            'audited' => 1,
            'reportable' => 0,
            'len' => 36,
        ),

        'tudiadiem' => array(
            'required' => false,
            'source' => 'non-db',
            'name' => 'tudiadiem',
            'vname' => 'LBL_TUDIADIEM',
            'type' => 'relate',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 1,
            'reportable' => 0,
            'len' => '255',
            'id_name' => 'tudiadiem_id',
            'ext2' => 'EC_Location',
            'module' => 'EC_Location',
            'rname' => 'name',
            'quicksearch' => 'enabled',
            'studio' => 'visible',
        ),
        
        'dendiadiem_id' => array(
            'required' => false,
            'name' => 'dendiadiem_id',
            'vname' => '',
            'type' => 'id',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => 0,
            'audited' => 1,
            'reportable' => 0,
            'len' => 36,
        ),

        'dendiadiem' => array(
            'required' => false,
            'source' => 'non-db',
            'name' => 'dendiadiem',
            'vname' => 'LBL_DENDIADIEM',
            'type' => 'relate',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 1,
            'reportable' => 0,
            'len' => '255',
            'id_name' => 'dendiadiem_id',
            'ext2' => 'EC_Location',
            'module' => 'EC_Location',
            'rname' => 'name',
            'quicksearch' => 'enabled',
            'studio' => 'visible',
        ),
    ),
    'indices' => array(
        array('name' => 'idx_ctnb_name', 'type' => 'index', 'fields' => array('name')),
        array('name' => 'idx_ctnb_del', 'type' => 'index', 'fields' => array('deleted')),
        array('name' => 'idx_ctnb_assign', 'type' => 'index', 'fields' => array('assigned_user_id')),
        array('name' => 'idx_ctnb_ghiso', 'type' => 'index', 'fields' => array('ghiso')),
        array('name' => 'idx_ctnb_tutknganhang', 'type' => 'index', 'fields' => array('tutknganhang_id')),
        array('name' => 'idx_ctnb_dentknganhang', 'type' => 'index', 'fields' => array('dentknganhang_id')),
        array('name' => 'idx_ctnb_tutienmat', 'type' => 'index', 'fields' => array('tutienmat')),
        array('name' => 'idx_ctnb_dentienmat', 'type' => 'index', 'fields' => array('dentienmat')),
        array('name' => 'idx_ctnb_tudiadiem', 'type' => 'index', 'fields' => array('tudiadiem_id')),
        array('name' => 'idx_ctnb_dendiadiem', 'type' => 'index', 'fields' => array('dendiadiem_id')),
    ),
    'relationships' => array(),
    'optimistic_lock' => true,
);

if (!class_exists('VardefManager')) {
    require_once('include/SugarObjects/VardefManager.php');
}
VardefManager::createVardef('EC_ChuyenTienNoiBo', 'EC_ChuyenTienNoiBo', array('basic', 'assignable'));
