<?php

$dictionary['EC_ChiTietHoaDon'] = array(
    'table' => 'ec_chitiethoadon',
    'audited' => true,
    'inline_edit' => true,
    'duplicate_merge' => true,
    'fields' =>  array(
        'parent_name' => array(
            'required' => false,
            'source' => 'non-db',
            'name' => 'parent_name',
            'vname' => 'LBL_FLEX_RELATE',
            'type' => 'parent',
            'massupdate' => 0,
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => ' ',
            'audited' => 1,
            'reportable' => 0,
            'len' => 25,
            'options' => 'parent_type_display',
            'studio' => 'visible',
            'type_name' => 'parent_type',
            'id_name' => 'parent_id',
            'parent_type' => 'record_type_display',
        ),
        'parent_type' => array(
            'required' => false,
            'name' => 'parent_type',
            'vname' => 'LBL_PARENT_TYPE',
            'type' => 'parent_type',
            'massupdate' => 0,
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => 0,
            'audited' => 0,
            'reportable' => 0,
            'len' => 100,
            'dbType' => 'varchar',
            'studio' => 'hidden',
        ),
        'parent_id' => array(
            'required' => false,
            'name' => 'parent_id',
            'vname' => 'LBL_PARENT_ID',
            'type' => 'id',
            'massupdate' => 0,
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => 0,
            'audited' => 0,
            'reportable' => 0,
            'len' => 36,
            'default' => '',
        ),

        'donvitinh' => array(
            'required' => false,
            'name' => 'donvitinh',
            'vname' => 'LBL_DONVITINH',
            'type' => 'varchar',
            'massupdate' => 0,
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '',
            'audited' => 1,
            'reportable' => 0,
            'len' => '10',
        ),

        'soluong' => array(
            'required' => false,
            'name' => 'soluong',
            'vname' => 'LBL_SOLUONG',
            'type' => 'int',
            'massupdate' => 0,
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '',
            'audited' => 1,
            'reportable' => 0,
            'len' => '11',
        ),

        // Giá mua (Bổ sung ngày 15/11/2023)
        'giamua' => array(
            'name'      => 'giamua',
            'vname'     => 'LBL_GIAMUA',
            'type'      => 'currency',
            'len'       => 26,
            'required'  => false,
            'default'   => 0,
            'massupdate' => 0,
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => ' ',
            'audited' => 1,
            'reportable' => 0,
        ),

        'dongia' => array(
            'required' => false,
            'name' => 'dongia',
            'vname' => 'LBL_DONGIA',
            'type' => 'currency',
            'massupdate' => 0,
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => ' ',
            'audited' => 1,
            'reportable' => 0,
            'len' => 26,
        ),

        'thanhtien' => array(
            'required' => false,
            'name' => 'thanhtien',
            'vname' => 'LBL_THANHTIEN',
            'type' => 'currency',
            'massupdate' => 0,
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => ' ',
            'audited' => 1,
            'reportable' => 0,
            'len' => 26,
        ),

        'thuesuat' => array(
            'required' => false,
            'name' => 'thuesuat',
            'vname' => 'LBL_THUESUAT',
            'type' => 'float',
            'massupdate' => 0,
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '',
            'audited' => 1,
            'reportable' => 0,
            'len' => '18',
            'precision' => '2',
        ),

        'tienthue' => array(
            'required' => false,
            'name' => 'tienthue',
            'vname' => 'LBL_TIENTHUE',
            'type' => 'currency',
            'massupdate' => 0,
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => ' ',
            'audited' => 1,
            'reportable' => 0,
            'len' => 26,
        ),

        // Phí thu hộ (sẽ gồm 2 loại: phí sân bay & phí khác)
        'phithuho' => array(
            'required' => false,
            'name' => 'phithuho',
            'vname' => 'LBL_PHITHUHO',
            'type' => 'currency',
            'massupdate' => 0,
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => ' ',
            'audited' => 1,
            'reportable' => 0,
            'len' => 26,
        ),

        // Phí sân bay (Bổ sung ngày 09/11/2023)
        'phisanbay' => array(
            'name'      => 'phisanbay',
            'vname'     => 'LBL_PHISANBAY',
            'type'      => 'currency',
            'len'       => 26,
            'default'   => 0,
            'required'   => false,
            'massupdate' => false,
            'importable' => true,
            'audited'    => true,
            'reportable' => false,
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '',
        ),

        // Phí khác (Bổ sung ngày 09/11/2023)
        'phikhac' => array(
            'name'      => 'phikhac',
            'vname'     => 'LBL_PHIKHAC',
            'type'      => 'currency',
            'len'       => 26,
            'default'   => 0,
            'required'   => false,
            'massupdate' => false,
            'importable' => true,
            'audited'    => true,
            'reportable' => false,
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '',
        ),

        // Phí dịch vụ (Bổ sung ngày 06/11/2023)
        'phidv' => array(
            'name'      => 'phidv',
            'vname'     => 'LBL_PHIDV',
            'type'      => 'currency',
            'len'       => 26,
            'default'   => 0,
            'required'   => false,
            'massupdate' => false,
            'importable' => true,
            'audited'    => true,
            'reportable' => false,
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '',
        ),

        'ptramgg' => array(
            'required' => false,
            'name' => 'ptramgg',
            'vname' => 'LBL_PTRAMGG',
            'type' => 'float',
            'massupdate' => 0,
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '',
            'audited' => 1,
            'reportable' => 0,
            'len' => '18',
            'precision' => '4',
        ),

        'tiengg' => array(
            'required' => false,
            'name' => 'tiengg',
            'vname' => 'LBL_TIENGG',
            'type' => 'currency',
            'massupdate' => 0,
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '',
            'audited' => 1,
            'reportable' => 0,
            'len' => 26,
        ),

        'ticket_number_id' => array(
            'required' => false,
            'name' => 'ticket_number_id',
            'vname' => '',
            'type' => 'id',
            'massupdate' => 0,
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => 0,
            'audited' => 0,
            'reportable' => 0,
            'len' => 36,
        ),

        'ticket_number' => array(
            'required' => false,
            'source' => 'non-db',
            'name' => 'ticket_number',
            'vname' => 'LBL_TICKET_NUMBER',
            'type' => 'relate',
            'massupdate' => 0,
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => ' ',
            'audited' => 1,
            'reportable' => 0,
            'len' => '255',
            'id_name' => 'ticket_number_id',
            'ext2' => 'EC_Input_Invoices',
            'module' => 'EC_Input_Invoices',
            'rname' => 'name',
            'quicksearch' => 'enabled',
            'studio' => 'visible',
        ),

        'booking_id' => array(
            'required' => false,
            'name' => 'booking_id',
            'vname' => '',
            'type' => 'id',
            'massupdate' => 0,
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => 0,
            'audited' => 0,
            'reportable' => 0,
            'len' => 36,
            'default' => ''
        ),
        'booking' => array(
            'required' => false,
            'name' => 'booking',
            'vname' => 'LBL_BOOKING',
            'type' => 'relate',
            'massupdate' => 0,
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => ' ',
            'audited' => 1,
            'reportable' => 0,
            'len' => '255',
            'id_name' => 'booking_id',
            'ext2' => 'EC_Flight_Bookings',
            'module' => 'EC_Flight_Bookings',
            'rname' => 'name',
            'quicksearch' => 'enabled',
            'studio' => 'visible',
        ),

        'order_by_no' => array(
            'required' => false,
            'name' => 'order_by_no',
            'vname' => 'LBL_ORDER_BY_NO',
            'type' => 'int',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 0,
            'reportable' => 0,
            'len' => '11',
            'disable_num_format' => '',
        ),

        // Mã hàng (Bổ sung ngày 16/11/2023)
        'mahang' => array(
            'name'      => 'mahang',
            'vname'     => 'LBL_MAHANG',
            'type'      => 'enum',
            'len'       => 10,
            'massupdate' => 0,
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => ' ',
            'audited' => 1,
            'reportable' => 0,
            'options' => 'invoice_mahang_list',
            'studio' => 'visible',
            'dependency' => false,
        ),
    ),
    'indices' => array(
        array('name' => 'idx_cthd_name', 'type' => 'index', 'fields' => array('name')),
        array('name' => 'idx_cthd_prtid', 'type' => 'index', 'fields' => array('parent_id')),
        array('name' => 'idx_cthd_ticket_number_id', 'type' => 'index', 'fields' => array('ticket_number_id')),
    ),
    'relationships' => array(),
    'optimistic_locking' => true,
    'unified_search' => true,
);
if (!class_exists('VardefManager')) {
    require_once('include/SugarObjects/VardefManager.php');
}
VardefManager::createVardef('EC_ChiTietHoaDon', 'EC_ChiTietHoaDon', array('basic', 'assignable', 'security_groups'));
