<?php

$dictionary['EC_Airports'] = array(
    'table' => 'ec_airports',
    'audited' => true,
    'inline_edit' => true,
    'duplicate_merge' => true,
    'fields' => array(
        'iata_code' => array(
            'name'      => 'iata_code',
            'vname'     => 'LBL_IATA_CODE',
            'type'      => 'varchar',
            'comment'   => 'Mã IATA sân bay: HAN, SGN, DXB, BKK, ... (AirportCode)',
            'len'       => 3,
            'required'  => true,
            'importable' => 'true',
            'audited'   => 1,
            'reportable' => 1,
            'unified_search' => true,
        ),
        'city_name' => array(
            'name'      => 'city_name',
            'vname'     => 'LBL_CITY_NAME',
            'type'      => 'varchar',
            'comment'   => 'Tên thành phố: "Hà Nội", "Hồ Chí Minh", "Dubai"',
            'len'       => 100,
            'default'   => '',
            'importable' => 'true',
            'audited'   => 0,
            'reportable' => 1,
        ),
        'region_code' => array(
            'required'  => false,
            'name'      => 'region_code',
            'vname'     => 'LBL_REGION_CODE',
            'type'      => 'varchar',
            'comment'   => 'Mã quốc gia ISO 2 ký tự: VN, AE, TH, SG, ... (RegionCode)',
            'len'       => 2,
            'default'   => '',
            'importable' => 'true',
            'audited'   => 0,
            'reportable' => 1,
        ),
        'region_name' => array(
            'required'  => false,
            'name'      => 'region_name',
            'vname'     => 'LBL_REGION_NAME',
            'type'      => 'varchar',
            'comment'   => 'Tên quốc gia: "Việt Nam", "Australia", ... (Region)',
            'len'       => 100,
            'default'   => '',
            'importable' => 'true',
            'audited'   => 0,
            'reportable' => 1,
        ),
        'prefix' => array(
            'required'  => false,
            'name'      => 'prefix',
            'vname'     => 'LBL_PREFIX',
            'type'      => 'enum',
            'comment'   => 'Loại sân bay (Prefix)',
            'len'       => 50,
            'options'   => 'airports_prefix_dom',
            'default'   => 'san-bay',
            'importable' => 'true',
            'audited'   => 0,
            'reportable' => 1,
        ),
        'geo_country' => array(
            'required'  => false,
            'name'      => 'geo_country',
            'vname'     => 'LBL_GEO_COUNTRY',
            'type'      => 'enum',
            'comment'   => 'Khu vực địa lý',
            'len'       => 5,
            'options'   => 'airports_geo_country_dom',
            'default'   => '1',
            'importable' => 'true',
            'audited'   => 0,
            'reportable' => 1,
        ),
        'is_active' => array(
            'required'  => false,
            'name'      => 'is_active',
            'vname'     => 'LBL_IS_ACTIVE',
            'type'      => 'bool',
            'default'   => true,
            'importable' => 'true',
            'audited'   => 1,
            'reportable' => 1,
        ),
    ),
    'indices' => array(
        array('name' => 'idx_airports_iata_code',      'type' => 'unique', 'fields' => array('iata_code')),
        array('name' => 'idx_airports_name',           'type' => 'index',  'fields' => array('name')),
        array('name' => 'idx_airports_city_name',      'type' => 'index',  'fields' => array('city_name')),
        array('name' => 'idx_airports_region_code',     'type' => 'index',  'fields' => array('region_code')),
        array('name' => 'idx_airports_geo_country',     'type' => 'index',  'fields' => array('geo_country')),
        array('name' => 'idx_airports_is_active',      'type' => 'index',  'fields' => array('is_active')),
    ),
    'relationships' => array(),
    'optimistic_locking' => true,
    'unified_search' => true,
);

if (!class_exists('VardefManager')) {
    require_once('include/SugarObjects/VardefManager.php');
}
VardefManager::createVardef('EC_Airports', 'EC_Airports', array('basic', 'assignable', 'security_groups'));
