<?php


// THIS CONTENT IS GENERATED BY MBPackage.php
$manifest = array(
  0 =>
  array(
    'acceptable_sugar_versions' =>
    array(
      0 => '',
    ),
  ),
  1 =>
  array(
    'acceptable_sugar_flavors' =>
    array(
      0 => 'CE',
      1 => 'PRO',
      2 => 'ENT',
    ),
  ),
  'readme' => '',
  'key' => 'EC',
  'author' => 'haihung',
  'description' => 'Cấu hình số điện thoại dùng để gọi ra',
  'icon' => '',
  'is_uninstallable' => true,
  'name' => 'Outbound_Phone',
  'published_date' => '2025-01-17 07:22:44',
  'type' => 'module',
  'version' => 1737098564,
  'remove_tables' => 'prompt',
);
