<?php
$dictionary['EC_Payment_Types'] = array(
    'table' => 'ec_payment_types',
    'audited' => true,
    'inline_edit' => true,
    'duplicate_merge' => true,
    'fields' =>
    array(
        'is_report' =>
        array(
            'required' => false,
            'name' => 'is_report',
            'vname' => 'LBL_IS_REPORT',
            'type' => 'bool',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '',
            'audited' => 1,
            'reportable' => 0,
            'len' => '1',
            'default' => '1',
        ),
        'is_payment_debt' =>
        array(
            'required' => false,
            'name' => 'is_payment_debt',
            'vname' => 'LBL_IS_PAYMENT_DEBT',
            'type' => 'bool',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '',
            'audited' => 1,
            'reportable' => 0,
            'len' => '1',
            'default' => '0',
        ),
        'is_receipt_debt' =>
        array(
            'required' => false,
            'name' => 'is_receipt_debt',
            'vname' => 'LBL_IS_RECEIPT_DEBT',
            'type' => 'bool',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '',
            'audited' => 1,
            'reportable' => 0,
            'len' => '1',
            'default' => '0',
        ),
        'aircode' =>
        array(
            'required' => false,
            'name' => 'aircode',
            'vname' => 'LBL_AIRCODE',
            'type' => 'enum',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 1,
            'reportable' => 0,
            'len' => 3,
            'options' => 'aircode_list',
            'studio' => 'visible',
            'dependency' => false,
        ),
        'is_other_amount' =>
        array(
            'required' => false,
            'name' => 'is_other_amount',
            'vname' => 'LBL_IS_OTHER_AMOUNT',
            'type' => 'bool',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '',
            'audited' => 1,
            'reportable' => 0,
            'len' => '1',
            'default' => '0',
        ),
    ),
    'relationships' => array(),
    'optimistic_locking' => true,
    'unified_search' => true,
);
if (!class_exists('VardefManager')) {
    require_once('include/SugarObjects/VardefManager.php');
}
VardefManager::createVardef('EC_Payment_Types', 'EC_Payment_Types', array('basic', 'assignable', 'security_groups'));
