<?php
$dictionary['EC_Booking_Passengers'] = array(
    'table' => 'ec_booking_passengers',
    'audited' => true,
    'inline_edit' => true,
    'duplicate_merge' => true,
    'fields' => array(
        'salutation' => array(
            'required' => false,
            'name' => 'salutation',
            'vname' => 'LBL_SALUTATION',
            'type' => 'enum',
            'options' => 'passenger_salutation_list',
            'len' => 2,
            'massupdate' => '1',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '',
            'audited' => 1,
            'reportable' => 0,
            'studio' => 'visible',
            'dependency' => false,
        ),

        'birthday' => array(
            'required' => false,
            'name' => 'birthday',
            'vname' => 'LBL_BIRTHDAY',
            'type' => 'date',
            'massupdate' => 0,
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => ' ',
            'audited' => 1,
            'reportable' => 0,
        ),

        'booking_id' => array(
            'required' => false,
            'name' => 'booking_id',
            'vname' => '',
            'type' => 'id',
            'len' => 36,
            'default' => '',
            'massupdate' => 0,
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => 0,
            'audited' => 0,
            'reportable' => 0,
        ),
        'booking' => array(
            'required' => '0',
            'source' => 'non-db',
            'name' => 'booking',
            'vname' => 'LBL_BOOKING',
            'type' => 'relate',
            'id_name' => 'booking_id',
            'ext2' => 'EC_Flight_Bookings',
            'module' => 'EC_Flight_Bookings',
            'rname' => 'name',
            'quicksearch' => 'enabled',
            'studio' => 'visible',
        ),

        'type' => array(
            'required' => false,
            'name' => 'type',
            'vname' => 'LBL_TYPE',
            'type' => 'enum',
            'options' => 'passenger_type_list',
            'len' => 2,
            'massupdate' => 0,
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => ' ',
            'audited' => 1,
            'reportable' => 0,
            'studio' => 'visible',
            'dependency' => false,
        ),

        // Số vé
        'eticket_outbound' => array(
            'required' => false,
            'name' => 'eticket_outbound',
            'vname' => 'LBL_ETICKET_OUTBOUND',
            'type' => 'varchar',
            'default' => '',
            'massupdate' => 0,
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => ' ',
            'audited' => 1,
            'reportable' => 0,
            'len' => '25',
        ),
        'eticket_inbound' => array(
            'required' => false,
            'name' => 'eticket_inbound',
            'vname' => 'LBL_ETICKET_INBOUND',
            'type' => 'varchar',
            'default' => '',
            'massupdate' => 0,
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => ' ',
            'audited' => 1,
            'reportable' => 0,
            'len' => '25',
        ),

        // Số vé hành lý
        'eluggage_outbound' => array(
            'required' => false,
            'name' => 'eluggage_outbound',
            'vname' => 'LBL_ELUGGAGE_OUTBOUND',
            'type' => 'varchar',
            'comment' => 'Số vé hành lý, Hãng BBA và VNA có số vé hành lý riêng',
            'massupdate' => 0,
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => ' ',
            'audited' => 1,
            'reportable' => 0,
            'len' => '25',
            'default' => '',
        ),
        'eluggage_inbound' => array(
            'required' => false,
            'name' => 'eluggage_inbound',
            'vname' => 'LBL_ELUGGAGE_INBOUND',
            'type' => 'varchar',
            'comment' => 'Số vé hành lý, Hãng BBA và VNA có số vé hành lý riêng',
            'massupdate' => 0,
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => ' ',
            'audited' => 1,
            'reportable' => 0,
            'len' => '25',
            'default' => '',
        ),

        // PNR (Mã đặt chỗ)
        'pnr_outbound' => array(
            'required' => false,
            'name' => 'pnr_outbound',
            'vname' => 'LBL_PNR_OUTBOUND',
            'type' => 'varchar',
            'default' => '',
            'massupdate' => 0,
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => ' ',
            'audited' => 1,
            'reportable' => 0,
            'len' => '25',
        ),
        'pnr_inbound' => array(
            'required' => false,
            'name' => 'pnr_inbound',
            'vname' => 'LBL_PNR_INBOUND',
            'type' => 'varchar',
            'default' => '',
            'massupdate' => 0,
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => ' ',
            'audited' => 1,
            'reportable' => 0,
            'len' => '25',
        ),

        // Tổng giá bán hành lý từng lượt
        'luggage_price' => array(
            'required' => false,
            'name' => 'luggage_price',
            'vname' => 'LBL_LUGGAGE_PRICE',
            'type' => 'int',
            'massupdate' => 0,
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 1,
            'reportable' => 0,
            'len' => '11',
            'disable_num_format' => '',
        ),
        'luggage_price_inbound' => array(
            'required' => false,
            'name' => 'luggage_price_inbound',
            'vname' => 'LBL_LUGGAGE_PRICE_INBOUND',
            'type' => 'int',
            'massupdate' => 0,
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 1,
            'reportable' => 0,
            'len' => '11',
            'disable_num_format' => '',
        ),

        'supplier_id' => array(
            'required' => false,
            'name' => 'supplier_id',
            'vname' => '',
            'type' => 'id',
            'default' => '',
            'massupdate' => 0,
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => 0,
            'audited' => 0,
            'reportable' => 0,
            'len' => 36,
        ),
        'supplier' => array(
            'required' => '0',
            'source' => 'non-db',
            'name' => 'supplier',
            'vname' => 'LBL_SUPPLIER',
            'type' => 'relate',
            'massupdate' => 0,
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => ' ',
            'audited' => 1,
            'reportable' => 0,
            'id_name' => 'supplier_id',
            'ext2' => 'Accounts',
            'module' => 'Accounts',
            'rname' => 'name',
            'quicksearch' => 'enabled',
            'studio' => 'visible',
        ),

        'supplier_inbound_id' => array(
            'required' => false,
            'name' => 'supplier_inbound_id',
            'vname' => '',
            'type' => 'id',
            'default' => '',
            'massupdate' => 0,
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => 0,
            'audited' => 0,
            'reportable' => 0,
            'len' => 36,
        ),
        'supplier_inbound' => array(
            'required' => '0',
            'source' => 'non-db',
            'name' => 'supplier_inbound',
            'vname' => 'LBL_SUPPLIER_INBOUND',
            'type' => 'relate',
            'massupdate' => 0,
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => ' ',
            'audited' => 1,
            'reportable' => 0,
            'id_name' => 'supplier_inbound_id',
            'ext2' => 'Accounts',
            'module' => 'Accounts',
            'rname' => 'name',
            'quicksearch' => 'enabled',
            'studio' => 'visible',
        ),

        'direction' => array(
            'required' => false,
            'name' => 'direction',
            'vname' => 'LBL_DIRECTION',
            'type' => 'enum',
            'options' => 'bk_direction_list',
            'len' => 2,
            'default' => '',
            'massupdate' => 0,
            'importable' => 1,
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '',
            'audited' => 1,
            'reportable' => 0,
            'studio' => 'visible',
            'dependency' => false,
        ),

        'go_with' => array(
            'name' => 'go_with',
            'vname' => 'LBL_GO_WITH',
            'type' => 'int',
            'dbtype' => 'tinyint',
            'default' => 0,
            'comment' => 'Show sorted changes history',
            'required' => 0,
            'audited' => 1,
            'massupdate' => 0,
            'importable' => 1,
            'reportable' => 0,
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => ' ',
            'disable_num_format' => '',
        ),

        'agent_pax_detail_id' => array(
            'required' => false,
            'name' => 'agent_pax_detail_id',
            'vname' => '',
            'type' => 'id',
            'massupdate' => 0,
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => 0,
            'audited' => 0,
            'reportable' => 0,
            'len' => 36,
        ),

        'ob_bag_wgt' => array(
            'required' => false,
            'name' => 'ob_bag_wgt',
            'vname' => 'LBL_OB_BAG_WGT',
            'type' => 'int',
            'massupdate' => 0,
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => ' ',
            'audited' => 1,
            'reportable' => 0,
            'len' => '11',
            'disable_num_format' => '',
        ),

        'ib_bag_wgt' => array(
            'required' => false,
            'name' => 'ib_bag_wgt',
            'vname' => 'LBL_IB_BAG_WGT',
            'type' => 'int',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => ' ',
            'audited' => 1,
            'reportable' => 0,
            'len' => '11',
            'disable_num_format' => '',
        ),

        // Phân biệt dòng chi tiết được booker đổi thông tin (=2) hay thêm hành lý (=1)
        'add_type' => array(
            'required' => false,
            'name' => 'add_type',
            'vname' => 'LBL_ADD_TYPE',
            'type' => 'int',
            'dbtype' => 'tinyint',
            'massupdate' => 0,
            'importable' => 1,
            'audited' => 1,
            'reportable' => 0,
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => ' ',
            'disable_num_format' => '',
        ),

        // Phân biệt các dòng chi tiết mới được thay đổi thông tin
        'parent_detail_id' => array(
            'required' => false,
            'name' => 'parent_detail_id',
            'vname' => 'LBL_PARENT_DETAIL_ID',
            'type' => 'char',
            'massupdate' => 0,
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => ' ',
            'audited' => 0,
            'reportable' => 0,
            'len' => '36',
        ),

        // Giá mua thêm hành lý từng lượt (Chưa VAT)
        'luggage_purchase_no_vat' => array(
            'required' => false,
            'name' => 'luggage_purchase_no_vat',
            'vname' => 'LBL_LUGGAGE_PURCHASE_NO_VAT',
            'type' => 'int',
            'massupdate' => 0,
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 1,
            'reportable' => 0,
            'len' => '11',
            'disable_num_format' => '',
        ),
        'luggage_purchase_inbound_no_vat' => array(
            'required' => false,
            'name' => 'luggage_purchase_inbound_no_vat',
            'vname' => 'LBL_LUGGAGE_PURCHASE_INBOUND_NO_VAT',
            'type' => 'int',
            'massupdate' => 0,
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 1,
            'reportable' => 0,
            'len' => '11',
            'disable_num_format' => '',
        ),

        // VAT giá mua thêm hành lý từng lượt
        'vat_luggage_purchase' => array(
            'required' => false,
            'name' => 'vat_luggage_purchase',
            'vname' => 'LBL_VAT_LUGGAGE_PURCHASE',
            'type' => 'int',
            'massupdate' => 0,
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 1,
            'reportable' => 0,
            'len' => '11',
            'disable_num_format' => '',
        ),
        'vat_luggage_purchase_inbound' => array(
            'required' => false,
            'name' => 'vat_luggage_purchase_inbound',
            'vname' => 'LBL_VAT_LUGGAGE_PURCHASE_INBOUND',
            'type' => 'int',
            'massupdate' => 0,
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 1,
            'reportable' => 0,
            'len' => '11',
            'disable_num_format' => '',
        ),

        // Tổng giá mua thêm hành lý từng lượt
        'luggage_purchase' => array(
            'required' => false,
            'name' => 'luggage_purchase',
            'vname' => 'LBL_LUGGAGE_PURCHASE',
            'type' => 'int',
            'massupdate' => 0,
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 1,
            'reportable' => 0,
            'len' => '11',
            'disable_num_format' => '',
        ),
        'luggage_purchase_inbound' => array(
            'required' => false,
            'name' => 'luggage_purchase_inbound',
            'vname' => 'LBL_LUGGAGE_PURCHASE_INBOUND',
            'type' => 'int',
            'massupdate' => 0,
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 1,
            'reportable' => 0,
            'len' => '11',
            'disable_num_format' => '',
        ),

        /**
         * Mô tả thông tin hành lý mua thêm từng lượt (Không cần dùng tệp ngôn ngữ)
         * Updated at 25/07/2025 by DucPham
         */
        'luggage_purchase_text' => array(
            'name'  => 'luggage_purchase_text',
            'vname' => 'LBL_LUGGAGE_PURCHASE_TEXT',
            'type'  => 'varchar',
            'len'   => 100,
            'required'      => 0,
            'massupdate'    => 0,
            'importable'    => 1,
            'audited'       => 1,
            'reportable'    => 0,
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
        ),
        'luggage_purchase_text_inbound' => array(
            'name'  => 'luggage_purchase_text_inbound',
            'vname' => 'LBL_LUGGAGE_PURCHASE_TEXT_INBOUND',
            'type'  => 'varchar',
            'len'   => 100,
            'required'      => 0,
            'massupdate'    => 0,
            'importable'    => 1,
            'audited'       => 1,
            'reportable'    => 0,
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
        ),

        /**
         * Index hành lý từng lượt (Thông tin trường này được lưu từ website)
         * Cũ: Index dùng cho hãng VJ
         * Mới: Dùng để lưu hành lý ký gửi có sẵn của các hãng. VD: 1x14 (1 kiện 14kg), 2x14 (2 kiện 14kg, tổng 28kg)
         * Updated at 25/07/2025 by DucPham
         */
        'luggage_index_outbound' => array(
            'name'  => 'luggage_index_outbound',
            'vname' => 'LBL_LUGGAGE_INDEX_OUTBOUND',
            'type'  => 'varchar',
            'len'   => 6,
            'required'      => 0,
            'massupdate'    => 0,
            'importable'    => 1,
            'audited'       => 1,
            'reportable'    => 0,
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
        ),
        'luggage_index_inbound' => array(
            'name'  => 'luggage_index_inbound',
            'vname' => 'LBL_LUGGAGE_INDEX_INBOUND',
            'type'  => 'varchar',
            'len'   => 6,
            'required'      => 0,
            'massupdate'    => 0,
            'importable'    => 1,
            'audited'       => 1,
            'reportable'    => 0,
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
        ),

        // Citizen Identity Card (CIC)
        'cic' => array(
            'name' => 'cic',
            'vname' => 'LBL_CIC',
            'type' => 'varchar',
            'len' => 16,
            'default' => '',
            'required' => false,
            'massupdate' => 0,
            'importable' => 1,
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '',
            'audited' => 1,
            'reportable' => 0,
        ),

        'passport_number' => array(
            'name' => 'passport_number',
            'vname' => 'LBL_PASSPORT_NUMBER',
            'type' => 'varchar',
            'len' => 10,
            'default' => '',
            'required' => false,
            'massupdate' => 0,
            'importable' => 1,
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '',
            'audited' => 1,
            'reportable' => 0,
        ),

        /**
         * Hành lý xách tay lượt đi
         * VD: 1x7 (1 kiện 7kg), 2x14 (2 kiện 14kg, tổng 28kg)
         * Updated at 05/03/2026 by DucPham
         */
        'hand_baggage_outbound' => array(
            'name' => 'hand_baggage_outbound',
            'vname' => 'LBL_HAND_BAGGAGE_OUTBOUND',
            'type' => 'varchar',
            'len' => 6,
            'default' => '',
            'required' => false,
            'audited' => 1,
            'importable' => 1,
            'reportable' => 0,
            'massupdate' => 0,
        ),

        /**
         * Hành lý xách tay lượt về
         * VD: 1x7 (1 kiện 7kg), 2x14 (2 kiện 14kg, tổng 28kg)
         * Updated at 05/03/2026 by DucPham
         */
        'hand_baggage_inbound' => array(
            'name' => 'hand_baggage_inbound',
            'vname' => 'LBL_HAND_BAGGAGE_INBOUND',
            'type' => 'varchar',
            'len' => 6,
            'default' => '',
            'required' => false,
            'audited' => 1,
            'importable' => 1,
            'reportable' => 0,
            'massupdate' => 0,
        ),
    ),
    'indices' => array(
        array('name' => 'idx_psg_name', 'type' => 'index', 'fields' => array('name')),
        array('name' => 'idx_psg_booking', 'type' => 'index', 'fields' => array('booking_id')),
        array('name' => 'idx_psg_eout', 'type' => 'index', 'fields' => array('eticket_outbound')),
        array('name' => 'idx_psg_ein', 'type' => 'index', 'fields' => array('eticket_inbound')),
        array('name' => 'idx_psg_pnrout', 'type' => 'index', 'fields' => array('pnr_outbound')),
        array('name' => 'idx_psg_pnrin', 'type' => 'index', 'fields' => array('pnr_inbound')),
        array('name' => 'idx_psg_suin', 'type' => 'index', 'fields' => array('supplier_id')),
        array('name' => 'idx_psg_suout', 'type' => 'index', 'fields' => array('supplier_inbound_id')),
        array('name' => 'idx_psg_eticket_bag_out', 'type' => 'index', 'fields' => array('eluggage_outbound')),
        array('name' => 'idx_psg_eticket_bag_in', 'type' => 'index', 'fields' => array('eluggage_inbound')),
        array('name' => 'idx_psg_cic', 'type' => 'index', 'fields' => array('cic')),
        array('name' => 'idx_psg_passport_number', 'type' => 'index', 'fields' => array('passport_number')),
    ),
    'relationships' => array(),
    'optimistic_locking' => true,
    'unified_search' => true,
);

if (!class_exists('VardefManager')) {
    require_once('include/SugarObjects/VardefManager.php');
}
VardefManager::createVardef('EC_Booking_Passengers', 'EC_Booking_Passengers', array('basic', 'assignable', 'security_groups'));
