<?php


$dictionary['EC_Debts'] = array(
    'table' => 'ec_debts',
    'audited' => true,
    'inline_edit' => true,
    'duplicate_merge' => true,
    'fields' =>
    array(
        'debt_amount' =>
        array(
            'required' => '1',
            'name' => 'debt_amount',
            'vname' => 'LBL_DEBT_AMOUNT',
            'type' => 'currency',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => ' ',
            'audited' => 1,
            'reportable' => 0,
            'len' => 26,
        ),
        'date_limit' =>
        array(
            'required' => false,
            'name' => 'date_limit',
            'vname' => 'LBL_DATE_LIMIT',
            'type' => 'date',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => ' ',
            'audited' => 1,
            'reportable' => 0,
            'display_default' => 'now',
        ),
        'booking_id' =>
        array(
            'required' => false,
            'name' => 'booking_id',
            'vname' => '',
            'type' => 'id',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => 0,
            'audited' => 0,
            'reportable' => 0,
            'len' => 36,
        ),
        'booking' =>
        array(
            'required' => false,
            'source' => 'non-db',
            'name' => 'booking',
            'vname' => 'LBL_BOOKING',
            'type' => 'relate',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => ' ',
            'audited' => 1,
            'reportable' => 0,
            'len' => '255',
            'id_name' => 'booking_id',
            'ext2' => 'EC_Flight_Bookings',
            'module' => 'EC_Flight_Bookings',
            'rname' => 'name',
            'quicksearch' => 'enabled',
            'studio' => 'visible',
        ),
        'contact_name' =>
        array(
            'required' => false,
            'name' => 'contact_name',
            'vname' => 'LBL_CONTACT_NAME',
            'type' => 'varchar',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => ' ',
            'audited' => 1,
            'reportable' => 0,
            'len' => '150',
        ),
        'phone_office' =>
        array(
            'required' => false,
            'name' => 'phone_office',
            'vname' => 'LBL_PHONE_OFFICE',
            'type' => 'phone',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => ' ',
            'audited' => 1,
            'reportable' => 0,
            'len' => '25',
            'dbType' => 'varchar',
        ),
        'phone_fax' =>
        array(
            'required' => false,
            'name' => 'phone_fax',
            'vname' => 'LBL_PHONE_FAX',
            'type' => 'phone',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => ' ',
            'audited' => 1,
            'reportable' => 0,
            'len' => '25',
            'dbType' => 'varchar',
        ),
        'phone_mobile' =>
        array(
            'required' => false,
            'name' => 'phone_mobile',
            'vname' => 'LBL_PHONE_MOBILE',
            'type' => 'phone',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => ' ',
            'audited' => 1,
            'reportable' => 0,
            'len' => '25',
            'dbType' => 'varchar',
        ),
        'email' =>
        array(
            'required' => false,
            'name' => 'email',
            'vname' => 'LBL_EMAIL',
            'type' => 'varchar',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => ' ',
            'audited' => 1,
            'reportable' => 0,
            'len' => '100',
        ),
        'address' =>
        array(
            'required' => false,
            'name' => 'address',
            'vname' => 'LBL_ADDRESS',
            'type' => 'text',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => ' ',
            'audited' => 1,
            'reportable' => 0,
            'studio' => 'visible',
        ),
        'supplier_id' =>
        array(
            'required' => false,
            'name' => 'supplier_id',
            'vname' => '',
            'type' => 'id',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => 0,
            'audited' => 0,
            'reportable' => 0,
            'len' => 36,
        ),
        'supplier' =>
        array(
            'required' => false,
            'source' => 'non-db',
            'name' => 'supplier',
            'vname' => 'LBL_SUPPLIER',
            'type' => 'relate',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => ' ',
            'audited' => 1,
            'reportable' => 0,
            'len' => '255',
            'id_name' => 'supplier_id',
            'ext2' => 'Accounts',
            'module' => 'Accounts',
            'rname' => 'name',
            'quicksearch' => 'enabled',
            'studio' => 'visible',
        ),
        'debt_type' =>
        array(
            'required' => false,
            'name' => 'debt_type',
            'vname' => 'LBL_DEBT_TYPE',
            'type' => 'enum',
            'massupdate' => 0,
            'default' => 'Buy',
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => ' ',
            'audited' => 0,
            'reportable' => 0,
            'len' => 100,
            'options' => 'debt_type_list',
            'studio' => 'visible',
            'dependency' => false,
        ),
        'ngayhachtoan' =>
        array(
            'required' => '1',
            'name' => 'ngayhachtoan',
            'vname' => 'LBL_NGAYHACHTOAN',
            'type' => 'datetimecombo',
            'dbType' => 'datetime',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '',
            'audited' => 1,
            'reportable' => 0,
            'display_default' => 'now',
        ),
    ),
    'indices' =>
    array(
        0 => array('name' => 'idx_dbt_name', 'type' => 'index', 'fields' => array('name')),
        1 => array('name' => 'idx_dbt_del', 'type' => 'index', 'fields' => array('deleted')),
        2 => array('name' => 'idx_dbt_supplier', 'type' => 'index', 'fields' => array('supplier_id')),
        3 => array('name' => 'idx_dbt_booking', 'type' => 'index', 'fields' => array('booking_id')),
    ),
    'relationships' => array(

        'debt_supplier' =>
        array(
            'lhs_module' => 'Accounts',
            'lhs_table' => 'accounts',
            'lhs_key' => 'id',
            'rhs_module' => 'EC_Debts',
            'rhs_table' => 'ec_debts',
            'rhs_key' => 'supplier_id',
            'relationship_type' => 'one-to-many',
        ),
        'debt_booking' =>
        array(
            'lhs_module' => 'EC_Flight_Bookings',
            'lhs_table' => 'ec_flight_bookings',
            'lhs_key' => 'id',
            'rhs_module' => 'EC_Debts',
            'rhs_table' => 'ec_debts',
            'rhs_key' => 'booking_id',
            'relationship_type' => 'one-to-one',
        ),
    ),
    'optimistic_locking' => true,
    'unified_search' => true,
);
if (!class_exists('VardefManager')) {
    require_once('include/SugarObjects/VardefManager.php');
}
VardefManager::createVardef('EC_Debts', 'EC_Debts', array('basic', 'assignable', 'security_groups'));
