<?php

$dictionary['EC_LeaveAbsences'] = array(
    'table' => 'ec_leaveabsences',
    'audited' => true,
    'inline_edit' => true,
    'duplicate_merge' => true,
    'fields' => array(
        'reason' =>
        array(
          'required' => false,
          'name' => 'reason',
          'vname' => 'LBL_REASON',
          'type' => 'text',
          'massupdate' => 0,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => 0,
          'reportable' => 0,
        ),
        'from_date' =>
        array(
          'required' => false,
          'name' => 'from_date',
          'vname' => 'LBL_FROM_DATE',
          'type' => 'date',
          'massupdate' => 0,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => 1,
          'reportable' => 0,
          'display_default' => 'now',
        ),
        'to_date' =>
        array(
          'required' => false,
          'name' => 'to_date',
          'vname' => 'LBL_TO_DATE',
          'type' => 'date',
          'massupdate' => 0,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => 1,
          'reportable' => 0,
          'display_default' => 'now',
        ),
        'absence_days' =>
        array(
          'required' => false,
          'name' => 'absence_days',
          'vname' => 'LBL_ABSENCE_DAYS',
          'type' => 'float',
          'massupdate' => 0,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => 1,
          'reportable' => 0,
          'len' => '18',
          'precision' => '1',
        ),
        'working_hour' =>
        array(
          'required' => false,
          'name' => 'working_hour',
          'vname' => 'LBL_WORKING_HOUR',
          'type' => 'int',
          'massupdate' => 0,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => 0,
          'reportable' => 0,
          'len' => '11',
          'disable_num_format' => '',
        ),
        'ec_leaveabsencetypes_id_c' =>
        array(
          'required' => true,
          'name' => 'ec_leaveabsencetypes_id_c',
          'vname' => '',
          'type' => 'id',
          'massupdate' => 0,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => 0,
          'audited' => 0,
          'reportable' => 0,
          'len' => 36,
        ),
        'absence_type' =>
        array(
          'required' => true,
          'source' => 'non-db',
          'name' => 'absence_type',
          'vname' => 'LBL_ABSENCE_TYPE',
          'type' => 'relate',
          'massupdate' => 0,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => 1,
          'reportable' => 0,
          'len' => '255',
          'id_name' => 'ec_leaveabsencetypes_id_c',
          'ext2' => 'EC_LeaveAbsenceTypes',
          'module' => 'EC_LeaveAbsenceTypes',
          'rname' => 'name',
          'quicksearch' => 'enabled',
          'studio' => 'visible',
        ),
        'status' =>
        array(
          'required' => false,
          'name' => 'status',
          'vname' => 'LBL_STATUS',
          'type' => 'enum',
          'massupdate' => 0,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => 1,
          'reportable' => 0,
          'len' => 100,
          'options' => 'absence_status_list',
          'studio' => 'visible',
          'dependency' => false,
          'default' => '0',
        ),
        'partofday' =>
        array(
          'required' => false,
          'name' => 'partofday',
          'vname' => 'LBL_PARTOFDAY',
          'type' => 'enum',
          'massupdate' => 0,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => 1,
          'reportable' => 0,
          'len' => 100,
          'options' => 'partofday_list',
          'studio' => 'visible',
          'dependency' => false,
          'default' => '0',
        ),
        'part_date' =>
        array(
          'required' => false,
          'name' => 'part_date',
          'vname' => 'LBL_PART_DATE',
          'type' => 'date',
          'massupdate' => 0,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => 1,
          'reportable' => 0,
          'display_default' => '',
        ),
        'user_id_c' =>
        array(
          'required' => false,
          'name' => 'user_id_c',
          'vname' => '',
          'type' => 'id',
          'massupdate' => 0,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => 0,
          'audited' => 0,
          'reportable' => 0,
          'len' => 36,
        ),
        'approved_by_user' =>
        array(
          'required' => false,
          'source' => 'non-db',
          'name' => 'approved_by_user',
          'vname' => 'LBL_APPROVED_BY_USER',
          'type' => 'relate',
          'massupdate' => 0,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => 0,
          'reportable' => 0,
          'len' => '255',
          'id_name' => 'user_id_c',
          'ext2' => 'Users',
          'module' => 'Users',
          'rname' => 'name',
          'quicksearch' => 'enabled',
          'studio' => 'visible',
        ),
        'approved_date' =>
        array(
          'required' => false,
          'name' => 'approved_date',
          'vname' => 'LBL_APPROVED_DATE',
          'type' => 'datetime',
          'massupdate' => 0,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => 1,
          'reportable' => 0,
        ),
        'paid_days' =>
        array(
          'required' => false,
          'name' => 'paid_days',
          'vname' => 'LBL_PAID_DAYS',
          'type' => 'float',
          'massupdate' => 0,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => 1,
          'reportable' => 0,
          'len' => '18',
          'precision' => '1',
        ),
        'no_paid_days' =>
        array(
          'required' => false,
          'name' => 'no_paid_days',
          'vname' => 'LBL_NO_PAID_DAYS',
          'type' => 'float',
          'massupdate' => 0,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => 1,
          'reportable' => 0,
          'len' => '18',
          'precision' => '1',
        ),
        'remain_leave_days' =>
        array(
          'required' => false,
          'name' => 'remain_leave_days',
          'vname' => 'LBL_REMAIN_LEAVE_DAYS',
          'type' => 'float',
          'massupdate' => 0,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => 1,
          'reportable' => 0,
          'len' => '18',
          'precision' => '1',
        ),
        'used_leave_days_curr_m' =>
        array(
          'required' => false,
          'name' => 'used_leave_days_curr_m',
          'vname' => 'LBL_USED_LEAVE_DAYS',
          'type' => 'float',
          'massupdate' => 0,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => 1,
          'reportable' => 0,
          'len' => '18',
          'precision' => '1',
        ),
        'used_leave_days_next_m' =>
        array(
          'required' => false,
          'name' => 'used_leave_days_next_m',
          'vname' => 'LBL_USED_LEAVE_DAYS',
          'type' => 'float',
          'massupdate' => 0,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => 1,
          'reportable' => 0,
          'len' => '18',
          'precision' => '1',
        ),
      ),
    'relationships' => array (
),
    'optimistic_locking' => true,
    'unified_search' => true,
);
if (!class_exists('VardefManager')) {
        require_once('include/SugarObjects/VardefManager.php');
}
VardefManager::createVardef('EC_LeaveAbsences', 'EC_LeaveAbsences', array('basic','assignable','security_groups'));
