{literal}
<style id="Book1_28718_Styles">
#content{margin:0 !important; padding:0 !important;}
<!--table
	{mso-displayed-decimal-separator:"\.";
	mso-displayed-thousand-separator:"\,";}
.xl1528718
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:10.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:Calibri, sans-serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:general;
	vertical-align:bottom;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl6328718
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:10.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:Calibri, sans-serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:left;
	vertical-align:top;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
-->
.tbl_inside{
	font-family:"Times New Roman", Times, serif;
	font-size:10pt;
	margin:5px 10px;
	line-height:20px;
	width:100%;
}
.tbl_details{
	font-family:"Times New Roman", Times, serif;
	font-size:10pt;
	border-collapse:collapse;
	width:100%;
}
.tbl_details td{
	border:1px solid #000000;
	padding:2px;
}
</style>
{/literal}

<!--[if !excel]>&nbsp;&nbsp;<![endif]-->
<!--The following information was generated by Microsoft Office Excel's Publish
as Web Page wizard.-->
<!--If the same item is republished from Excel, all information between the DIV
tags will be replaced.-->
<!----------------------------->
<!--START OF OUTPUT FROM EXCEL PUBLISH AS WEB PAGE WIZARD -->
<!----------------------------->

<div id="Book1_28718" align=center x:publishsource="Excel">

<table border=0 cellpadding=0 cellspacing=0 width=576 style='border-collapse: collapse;table-layout:fixed;width:432pt; border:1px solid #000000;'>
 <col width=64 span=9 style='width:48pt'>
 <tr height=20 style='height:15.0pt'>
  <td colspan=9 rowspan=50 height=1000 class=xl6328718 width=576
  style='height:750.0pt;width:432pt'>
  
  
  	<table class="tbl_inside" cellpadding="0" cellspacing="0" border="0">
            <tr>
                <td width="25%"><img src="custom/themes/default/images/vmb_invoice_logo.jpg" border="0" style="width:140px; height:100px;" /></td>
                <td width="50%" style="text-align:center;">
                    <label style="font-weight:bold; font-size:15pt;">HOÁ ĐƠN GIÁ TRỊ GIA TĂNG</label>
                    <br /><label style="font-style:italic;">Liên 1: Lưu</label>
                    <br /><label style="font-style:italic;">Ngày 23 Tháng 01 Năm 2014</label>
                </td>
                <td width="25%">
                    Mẫu số: 01GTKT2/001
                    <br />Ký hiệu: NP/13T
                    <br />Số: <label style="font-weight:bold;">0000589</label>
                </td>
            </tr>
            <tr>
                <td colspan="3">
                    Đơn vị bán hàng: CÔNG TY TNHH VMB NAM PHƯƠNG
                    <br />Mã số thuế: 0312253052
                    <br />Địa chỉ: 647 Đường 3/2 , Phường 06 , Quận 10 , TP. Hồ Chí Minh
                    <br />Điện thoại: (08) 6680 6320 - 0932 802 802 - 0906 874187
                    <br />Website : www.vemaybaynamphuong.com Mail : vmbsale@gmail.com
                </td>
            </tr>
            <tr>
                <td colspan="3">
                    Họ tên người mua hàng: ..................................................................................................................
                    <br />Tên đơn vị: CÔNG TY TNHH TƯ VẤN XÂY DỰNG CHẤT LƯỢNG VIỆT
                    <br />Mã số thuế: 0302438625
                    <br />Địa chỉ: Lầu 3, P.301, 49 Lê Trung Nghĩa, P.12, Quận Tân Bình, TP. HCM
                    <br />Hình thức thanh toán: TM/CK &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Số tài khoản: ...................................
                </td>
            </tr>
            <tr>
                <td colspan="3">
                    <table class="tbl_details" border="0" cellpadding="0" cellspacing="0">
                        <tr>
                            <td width="5%" style="text-align:center; font-weight:bold;">STT</td>
                            <td width="46%" style="text-align:center; font-weight:bold;">Tên hàng hóa, dịch vụ</td>
                            <td width="12%" style="text-align:center; font-weight:bold;">Đơn vị tính</td>
                            <td width="10%" style="text-align:center; font-weight:bold;">Số lượng</td>
                            <td width="12%" style="text-align:center; font-weight:bold;">Đơn giá</td>
                            <td width="15%" style="text-align:center; font-weight:bold;">Thành tiền</td>
                        </tr>
                        <tr>
                            <td style="text-align:center; font-weight:bold; height:15px !important;">A</td>
                            <td style="text-align:center; font-weight:bold; height:15px !important;">B</td>
                            <td style="text-align:center; font-weight:bold; height:15px !important;">C</td>
                            <td style="text-align:center; font-weight:bold; height:15px !important;">1</td>
                            <td style="text-align:center; font-weight:bold; height:15px !important;">2</td>
                            <td style="text-align:center; font-weight:bold; height:15px !important;">3 = 1 x 2</td>
                        </tr>
                        <tr>
                            <td style="text-align:center;">1</td>
                            <td>Vé Máy Bay Nội Địa (SGN - UIH)</td>
                            <td>Vé</td>
                            <td style="text-align:right;">1</td>
                            <td style="text-align:right;">870.909</td>
                            <td style="text-align:right;">870.909</td>
                        </tr>
                        <tr>
                            <td style="text-align:center;">2</td>
                            <td>Phí Sân Bay ( Không chịu Thuế GTGT)</td>
                            <td>&nbsp;</td>
                            <td style="text-align:right;">1</td>
                            <td style="text-align:right;">60.000</td>
                            <td style="text-align:right;">60.000</td>
                        </tr>
                        <tr>
                            <td colspan="2">&nbsp;</td>
                            <td colspan="3">Cộng tiền hàng:</td>
                            <td style="text-align:right; font-weight:bold;">930.909</td>
                        </tr>
                        <tr>
                            <td colspan="2">Thuế suất thuế GT 10%</td>
                            <td colspan="3">Tiền thuế GTGT:</td>
                            <td style="text-align:right; font-weight:bold;">930.909</td>
                        </tr>
                        <tr>
                            <td colspan="2">&nbsp;</td>
                            <td colspan="3">Tổng cộng tiền thanh toán:</td>
                            <td style="text-align:right; font-weight:bold;">1.018.000</td>
                        </tr>
                        <tr>
                            <td colspan="6">Số tiền viết bằng chữ: <label style="font-weight:bold; font-style:italic;">Một triệu không trăm mười tám nghìn đồng chẵn.</label></td>
                        </tr>
                        
                    </table><!-- END TABLE DETAILS -->
                </td>
            </tr>
            <tr>
                <td colspan="3">
                    <table class="tbl_signatures" cellpadding="0" cellspacing="0" border="0">
                        <tr>
                            <td width="50%" style="text-align:center;">
                                <label style="font-weight:bold;">Người mua hàng</label>
                                <label style="font-style:italic;">(Ký, ghi rõ họ, tên)</label>
                                <br />
                                <span style="padding:5px; border:1px solid #000000;">BÁN HÀNG QUA ĐIỆN THOẠI</span>
                            </td>
                            <td width="50%" style="text-align:center;">
                                <label style="font-weight:bold;">Người bán hàng</label>
                                <label style="font-style:italic;">(Ký, ghi rõ họ, tên)</label>
                            </td>
                        </tr>
                    </table><!-- END TABLE SIGNATURES -->
                </td>
            </tr>
        </table>

  
  
  </td>
 </tr>
 <tr height=20 style='height:15.0pt'>
 </tr>
 <tr height=20 style='height:15.0pt'>
 </tr>
 <tr height=20 style='height:15.0pt'>
 </tr>
 <tr height=20 style='height:15.0pt'>
 </tr>
 <tr height=20 style='height:15.0pt'>
 </tr>
 <tr height=20 style='height:15.0pt'>
 </tr>
 <tr height=20 style='height:15.0pt'>
 </tr>
 <tr height=20 style='height:15.0pt'>
 </tr>
 <tr height=20 style='height:15.0pt'>
 </tr>
 <tr height=20 style='height:15.0pt'>
 </tr>
 <tr height=20 style='height:15.0pt'>
 </tr>
 <tr height=20 style='height:15.0pt'>
 </tr>
 <tr height=20 style='height:15.0pt'>
 </tr>
 <tr height=20 style='height:15.0pt'>
 </tr>
 <tr height=20 style='height:15.0pt'>
 </tr>
 <tr height=20 style='height:15.0pt'>
 </tr>
 <tr height=20 style='height:15.0pt'>
 </tr>
 <tr height=20 style='height:15.0pt'>
 </tr>
 <tr height=20 style='height:15.0pt'>
 </tr>
 <tr height=20 style='height:15.0pt'>
 </tr>
 <tr height=20 style='height:15.0pt'>
 </tr>
 <tr height=20 style='height:15.0pt'>
 </tr>
 <tr height=20 style='height:15.0pt'>
 </tr>
 <tr height=20 style='height:15.0pt'>
 </tr>
 <tr height=20 style='height:15.0pt'>
 </tr>
 <tr height=20 style='height:15.0pt'>
 </tr>
 <tr height=20 style='height:15.0pt'>
 </tr>
 <tr height=20 style='height:15.0pt'>
 </tr>
 <tr height=20 style='height:15.0pt'>
 </tr>
 <tr height=20 style='height:15.0pt'>
 </tr>
 <tr height=20 style='height:15.0pt'>
 </tr>
 <tr height=20 style='height:15.0pt'>
 </tr>
 <tr height=20 style='height:15.0pt'>
 </tr>
 <tr height=20 style='height:15.0pt'>
 </tr>
 <tr height=20 style='height:15.0pt'>
 </tr>
 <tr height=20 style='height:15.0pt'>
 </tr>
 <tr height=20 style='height:15.0pt'>
 </tr>
 <tr height=20 style='height:15.0pt'>
 </tr>
 <tr height=20 style='height:15.0pt'>
 </tr>
 <tr height=20 style='height:15.0pt'>
 </tr>
 <tr height=20 style='height:15.0pt'>
 </tr>
 <tr height=20 style='height:15.0pt'>
 </tr>
 <tr height=20 style='height:15.0pt'>
 </tr>
 <tr height=20 style='height:15.0pt'>
 </tr>
 <tr height=20 style='height:15.0pt'>
 </tr>
 <tr height=20 style='height:15.0pt'>
 </tr>
 <tr height=20 style='height:15.0pt'>
 </tr>
 <tr height=20 style='height:15.0pt'>
 </tr>
 <tr height=20 style='height:15.0pt'>
 </tr>
 <![if supportMisalignedColumns]>
 <tr height=0 style='display:none'>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
 </tr>
 <![endif]>
</table>

</div>

