<?php
$dictionary['EC_WorkingOverTimes'] = array(
    'table' => 'ec_workingovertimes',
    'audited' => true,
    'inline_edit' => true,
    'duplicate_merge' => true,
    'fields' => 
    array(
        'status' =>
        array(
            'required' => false,
            'name' => 'status',
            'vname' => 'LBL_STATUS',
            'type' => 'enum',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 1,
            'reportable' => 0,
            'len' => 100,
            'options' => 'overtime_status_list',
            'studio' => 'visible',
            'dependency' => false,
            'default' => '0',
        ),
        'type' =>
        array(
            'required' => false,
            'name' => 'type',
            'vname' => 'LBL_TYPE',
            'type' => 'enum',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 1,
            'reportable' => 0,
            'len' => 100,
            'options' => 'overtime_type_list',
            'studio' => 'visible',
            'dependency' => false,
            'default' => 0,
        ),
        'user_id_c' =>
        array(
            'required' => false,
            'name' => 'user_id_c',
            'vname' => '',
            'type' => 'id',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => 0,
            'audited' => 0,
            'reportable' => 0,
            'len' => 36,
        ),
        'approved_by_user' =>
        array(
            'required' => false,
            'source' => 'non-db',
            'name' => 'approved_by_user',
            'vname' => 'LBL_APPROVED_BY_USER',
            'type' => 'relate',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 0,
            'reportable' => 0,
            'len' => '255',
            'id_name' => 'user_id_c',
            'ext2' => 'Users',
            'module' => 'Users',
            'rname' => 'name',
            'quicksearch' => 'enabled',
            'studio' => 'visible',
        ),
        'approved_date' =>
        array(
            'required' => false,
            'name' => 'approved_date',
            'vname' => 'LBL_APPROVED_DATE',
            'type' => 'datetime',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 1,
            'reportable' => 0,
        ),
        // tháng bù công, tháng đc bù lại công của những tháng trước
        'bonus_month' =>
        array(
            'required' => false,
            'name' => 'bonus_month',
            'vname' => 'LBL_BONUS_MONTH',
            'type' => 'date',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 1,
            'reportable' => 0,
        ),
    ),
    'relationships' => array (
),
    'optimistic_locking' => true,
    'unified_search' => true,
);
if (!class_exists('VardefManager')) {
        require_once('include/SugarObjects/VardefManager.php');
}
VardefManager::createVardef('EC_WorkingOverTimes', 'EC_WorkingOverTimes', array('basic','assignable','security_groups'));
