<?php
$dictionary['EC_TaiKhoan'] = array(
    'table' => 'ec_taikhoan',
    'audited' => true,
    'inline_edit' => true,
    'duplicate_merge' => true,
    'fields' => 
    array(
        'sotaikhoan' =>
        array(
          'required' => '1',
          'name' => 'sotaikhoan',
          'vname' => 'LBL_SOTAIKHOAN',
          'type' => 'varchar',
          'massupdate' => 0,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '',
          'audited' => 1,
          'reportable' => 0,
          'len' => '10',
        ),
        'tentienganh' =>
        array(
          'required' => false,
          'name' => 'tentienganh',
          'vname' => 'LBL_TENTIENGANH',
          'type' => 'varchar',
          'massupdate' => 0,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '',
          'audited' => 1,
          'reportable' => 0,
          'len' => '150',
        ),
        'taikhoantonghop' =>
        array(
          'required' => false,
          'name' => 'taikhoantonghop',
          'vname' => 'LBL_TAIKHOANTONGHOP',
          'type' => 'varchar',
          'massupdate' => 0,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '',
          'audited' => 0,
          'reportable' => 0,
          'len' => '10',
        ),
        'nhomtaikhoan' =>
        array(
          'required' => '1',
          'name' => 'nhomtaikhoan',
          'vname' => 'LBL_NHOMTAIKHOAN',
          'type' => 'varchar',
          'massupdate' => 0,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '',
          'audited' => 1,
          'reportable' => 0,
          'len' => '10',
        ),
        'tinhchat' =>
        array(
          'required' => '1',
          'name' => 'tinhchat',
          'vname' => 'LBL_TINHCHAT',
          'type' => 'enum',
          'massupdate' => 0,
          'default' => 'DuNo',
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '',
          'audited' => 1,
          'reportable' => 0,
          'len' => 100,
          'options' => 'tinhchat_list',
          'studio' => 'visible',
          'dependency' => false,
        ),
        'loaidoituong' =>
        array(
          'required' => false,
          'name' => 'loaidoituong',
          'vname' => 'LBL_LOAIDOITUONG',
          'type' => 'enum',
          'massupdate' => 0,
          'default' => 'NCC',
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '',
          'audited' => 1,
          'reportable' => 0,
          'len' => 100,
          'options' => 'loaidoituong_list',
          'studio' => 'visible',
          'dependency' => false,
        ),
        'taphopchiphi' =>
        array(
          'required' => false,
          'name' => 'taphopchiphi',
          'vname' => 'LBL_TAPHOPCHIPHI',
          'type' => 'bool',
          'massupdate' => 0,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '',
          'audited' => 1,
          'reportable' => 0,
          'len' => '255',
        ),
        'doituong' =>
        array(
          'required' => false,
          'name' => 'doituong',
          'vname' => 'LBL_DOITUONG',
          'type' => 'bool',
          'massupdate' => 0,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '',
          'audited' => 1,
          'reportable' => 0,
          'len' => '255',
        ),
        'chitiettheo' =>
        array(
          'required' => false,
          'name' => 'chitiettheo',
          'vname' => 'LBL_CHITIETTHEO',
          'type' => 'bool',
          'massupdate' => 0,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '',
          'audited' => 1,
          'reportable' => 0,
          'len' => '255',
        ),
        'hopdong' =>
        array(
          'required' => false,
          'name' => 'hopdong',
          'vname' => 'LBL_HOPDONG',
          'type' => 'bool',
          'massupdate' => 0,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '',
          'audited' => 1,
          'reportable' => 0,
          'len' => '255',
        ),
        'vthh_ccdc' =>
        array(
          'required' => false,
          'name' => 'vthh_ccdc',
          'vname' => 'LBL_VTHH_CCDC',
          'type' => 'bool',
          'massupdate' => 0,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '',
          'audited' => 1,
          'reportable' => 0,
          'len' => '255',
        ),
        'taikhoannganhang' =>
        array(
          'required' => false,
          'name' => 'taikhoannganhang',
          'vname' => 'LBL_TAIKHOANNGANHANG',
          'type' => 'bool',
          'massupdate' => 0,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '',
          'audited' => 1,
          'reportable' => 0,
          'len' => '255',
        ),
        'khoanmucchiphi' =>
        array(
          'required' => false,
          'name' => 'khoanmucchiphi',
          'vname' => 'LBL_KHOANMUCCHIPHI',
          'type' => 'bool',
          'massupdate' => 0,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '',
          'audited' => 1,
          'reportable' => 0,
          'len' => '255',
        ),
        'theongoaite' =>
        array(
          'required' => false,
          'name' => 'theongoaite',
          'vname' => 'LBL_THEONGOAITE',
          'type' => 'bool',
          'massupdate' => 0,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '',
          'audited' => 1,
          'reportable' => 0,
          'len' => '255',
        ),
        'theophongban' =>
        array(
          'required' => false,
          'name' => 'theophongban',
          'vname' => 'LBL_THEOPHONGBAN',
          'type' => 'bool',
          'massupdate' => 0,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '',
          'audited' => 1,
          'reportable' => 0,
          'len' => '255',
        ),
        'theothuchi' =>
        array(
          'required' => false,
          'name' => 'theothuchi',
          'vname' => 'LBL_THEOTHUCHI',
          'type' => 'bool',
          'massupdate' => 0,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '',
          'audited' => 1,
          'reportable' => 0,
          'len' => '255',
        ),
        'ngungtheodoi' =>
        array(
          'required' => false,
          'name' => 'ngungtheodoi',
          'vname' => 'LBL_NGUNGTHEODOI',
          'type' => 'bool',
          'massupdate' => 0,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '',
          'audited' => 1,
          'reportable' => 0,
          'len' => '255',
        ),
        'cap' =>
        array(
          'required' => false,
          'name' => 'cap',
          'vname' => 'LBL_CAP',
          'type' => 'int',
          'massupdate' => 0,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => 1,
          'reportable' => 0,
          'len' => '3',
          'disable_num_format' => '',
        ),
      ),
    'relationships' => array(),
    'optimistic_locking' => true,
    'unified_search' => true,
);

if (!class_exists('VardefManager')) {
    require_once('include/SugarObjects/VardefManager.php');
}
VardefManager::createVardef('EC_TaiKhoan', 'EC_TaiKhoan', array('basic', 'assignable', 'security_groups'));
