<?php


// THIS CONTENT IS GENERATED BY MBPackage.php
$manifest = array(
  0 =>
  array(
    'acceptable_sugar_versions' =>
    array(
      0 => '',
    ),
  ),
  1 =>
  array(
    'acceptable_sugar_flavors' =>
    array(
      0 => 'CE',
      1 => 'PRO',
      2 => 'ENT',
    ),
  ),
  'readme' => '',
  'key' => 'EC',
  'author' => 'Haihugn',
  'description' => 'Chuyển tiền nội bộ',
  'icon' => '',
  'is_uninstallable' => true,
  'name' => 'ChuyenTienNoiBo',
  'published_date' => '2023-06-19 10:09:59',
  'type' => 'module',
  'version' => 1687169399,
  'remove_tables' => 'prompt',
);


$installdefs = array(
  'id' => 'ChuyenTienNoiBo',
  'beans' =>
  array(
    0 =>
    array(
      'module' => 'EC_ChuyenTienNoiBo',
      'class' => 'EC_ChuyenTienNoiBo',
      'path' => 'modules/EC_ChuyenTienNoiBo/EC_ChuyenTienNoiBo.php',
      'tab' => true,
    ),
  ),
  'layoutdefs' =>
  array(),
  'relationships' =>
  array(),
  'image_dir' => '<basepath>/icons',
  'copy' =>
  array(
    0 =>
    array(
      'from' => '<basepath>/SugarModules/modules/EC_ChuyenTienNoiBo',
      'to' => 'modules/EC_ChuyenTienNoiBo',
    ),
  ),
  'language' =>
  array(
    0 =>
    array(
      'from' => '<basepath>/SugarModules/language/application/en_us.lang.php',
      'to_module' => 'application',
      'language' => 'en_us',
    ),
    1 =>
    array(
      'from' => '<basepath>/SugarModules/language/application/vi_VN.lang.php',
      'to_module' => 'application',
      'language' => 'vi_VN',
    ),
  ),
);
