<?php

$dictionary['EC_HoaDonBan'] = array(
    'table' => 'ec_hoadonban',
    'audited' => true,
    'inline_edit' => true,
    'duplicate_merge' => true,
    'fields' => array(
        'doituong_id' => array(
            'required' => false,
            'name' => 'doituong_id',
            'vname' => '',
            'type' => 'id',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => 0,
            'audited' => 0,
            'reportable' => 0,
            'len' => 36,
        ),
        'doituong' => array(
            'required' => false,
            'source' => 'non-db',
            'name' => 'doituong',
            'vname' => 'LBL_DOITUONG',
            'type' => 'relate',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => ' ',
            'audited' => 1,
            'reportable' => 0,
            'len' => '255',
            'id_name' => 'doituong_id',
            'ext2' => 'Accounts',
            'module' => 'Accounts',
            'rname' => 'name',
            'quicksearch' => 'enabled',
            'studio' => 'visible',
        ),

        'lienhe' => array(
            'required' => false,
            'name' => 'lienhe',
            'vname' => 'LBL_LIENHE',
            'type' => 'varchar',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => ' ',
            'audited' => 1,
            'reportable' => 0,
            'len' => '255',
        ),

        'diachi' => array(
            'required' => false,
            'name' => 'diachi',
            'vname' => 'LBL_DIACHI',
            'type' => 'text',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => ' ',
            'audited' => 1,
            'reportable' => 0,
            'studio' => 'visible',
        ),

        'masothue' => array(
            'required' => false,
            'name' => 'masothue',
            'vname' => 'LBL_MASOTHUE',
            'type' => 'varchar',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => ' ',
            'audited' => 1,
            'reportable' => 0,
            'len' => '25',
        ),

        'ngaychungtu' => array(
            'required' => true,
            'name' => 'ngaychungtu',
            'vname' => 'LBL_NGAYCHUNGTU',
            'type' => 'date',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => ' ',
            'audited' => 1,
            'reportable' => 0,
            'display_default' => 'now',
        ),

        'ngayhachtoan' => array(
            'required' => true,
            'name' => 'ngayhachtoan',
            'vname' => 'LBL_NGAYHACHTOAN',
            'type' => 'date',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => ' ',
            'audited' => 1,
            'reportable' => 0,
            'display_default' => 'now',
        ),

        'ngayhoadon' => array(
            'required' => false,
            'name' => 'ngayhoadon',
            'vname' => 'LBL_NGAYHOADON',
            'type' => 'date',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => ' ',
            'audited' => 1,
            'reportable' => 0,
            'display_default' => 'now',
        ),

        'sohoadon' => array(
            'required' => false,
            'name' => 'sohoadon',
            'vname' => 'LBL_SOHOADON',
            'type' => 'varchar',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => ' ',
            'audited' => 1,
            'reportable' => 0,
            'len' => '10',
        ),

        'mauhoadon' => array(
            'required' => false,
            'name' => 'mauhoadon',
            'vname' => 'LBL_MAUHOADON',
            'type' => 'enum',
            'massupdate' => 0,
            'default' => '2',
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => ' ',
            'audited' => 1,
            'reportable' => 0,
            'len' => 100,
            'options' => 'mauhoadon_list',
            'studio' => 'visible',
            'dependency' => false,
        ),

        'kyhieuhd' => array(
            'required' => false,
            'name' => 'kyhieuhd',
            'vname' => 'LBL_KYHIEUHD',
            'type' => 'varchar',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => ' ',
            'audited' => 1,
            'reportable' => 0,
            'len' => '50',
        ),

        'loaihoadon' => array(
            'required' => false,
            'name' => 'loaihoadon',
            'vname' => 'LBL_LOAIHOADON',
            'type' => 'enum',
            'massupdate' => 0,
            'default' => 'hdgtgt',
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => ' ',
            'audited' => 1,
            'reportable' => 0,
            'len' => 100,
            'options' => 'loaihoadon_list',
            'studio' => 'visible',
            'dependency' => false,
        ),

        'hinhthuchd' => array(
            'required' => false,
            'name' => 'hinhthuchd',
            'vname' => 'LBL_HINHTHUCHD',
            'type' => 'enum',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => ' ',
            'audited' => 1,
            'reportable' => 0,
            'len' => 100,
            'options' => 'hinhthuchoadon_list',
            'studio' => 'visible',
            'dependency' => false,
        ),

        'hanthanhtoan' => array(
            'required' => false,
            'name' => 'hanthanhtoan',
            'vname' => 'LBL_HANTHANHTOAN',
            'type' => 'date',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => ' ',
            'audited' => 1,
            'reportable' => 0,
            'display_default' => 'now',
        ),

        'loaitien' => array(
            'required' => false,
            'name' => 'loaitien',
            'vname' => 'LBL_LOAITIEN',
            'type' => 'enum',
            'massupdate' => 0,
            'default' => 'VND',
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => ' ',
            'audited' => 1,
            'reportable' => 0,
            'len' => 100,
            'options' => 'loaitien_list',
            'studio' => 'visible',
            'dependency' => false,
        ),

        'tongtien' => array(
            'required' => false,
            'name' => 'tongtien',
            'vname' => 'LBL_TONGTIEN',
            'type' => 'currency',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => ' ',
            'audited' => 1,
            'reportable' => 0,
            'len' => 26,
        ),

        'tongtienthue' => array(
            'required' => false,
            'name' => 'tongtienthue',
            'vname' => 'LBL_TONGTIENTHUE',
            'type' => 'currency',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => ' ',
            'audited' => 1,
            'reportable' => 0,
            'len' => 26,
        ),

        'tongchietkhau' => array(
            'required' => false,
            'name' => 'tongchietkhau',
            'vname' => 'LBL_TONGCHIETKHAU',
            'type' => 'currency',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => ' ',
            'audited' => 1,
            'reportable' => 0,
            'len' => 26,
        ),

        'tongthanhtoan' => array(
            'required' => false,
            'name' => 'tongthanhtoan',
            'vname' => 'LBL_TONGTHANHTOAN',
            'type' => 'currency',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => ' ',
            'audited' => 1,
            'reportable' => 0,
            'len' => 26,
        ),

        'hinhthuctt' => array(
            'required' => false,
            'name' => 'hinhthuctt',
            'vname' => 'LBL_HINHTHUCTT',
            'type' => 'enum',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => ' ',
            'audited' => 1,
            'reportable' => 0,
            'len' => 100,
            'options' => 'hinhthucthanhtoan_list',
            'studio' => 'visible',
            'dependency' => false,
        ),

        'solanin' => array(
            'required' => false,
            'name' => 'solanin',
            'vname' => 'LBL_SOLANIN',
            'type' => 'int',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => ' ',
            'audited' => 1,
            'reportable' => 0,
            'len' => '11',
            'disable_num_format' => '',
        ),

        'tongsl' => array(
            'required' => false,
            'name' => 'tongsl',
            'vname' => 'LBL_TONGSL',
            'type' => 'float',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '',
            'audited' => 1,
            'reportable' => 0,
            'len' => '18',
            'precision' => '2',
        ),

        'nganhang' => array(
            'name'       => 'nganhang',
            'vname'      => 'LBL_NGANHANG',
            'type'       => 'varchar',
            'dbtype'     => 'varchar',
            'len'        => '150',
            // 'options'    => 'LIST_BANK_VIET_NAM',
            'massupdate' => 0,
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => ' ',
            'audited' => 1,
            'reportable' => 0,
            'required' => false,
            'default' => ''
        ),

        'sotaikhoan' => array(
            'required' => false,
            'name' => 'sotaikhoan',
            'vname' => 'LBL_SOTAIKHOAN',
            'type' => 'varchar',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => ' ',
            'audited' => 1,
            'reportable' => 0,
            'len' => '30',
        ),

        'tencongty' => array(
            'required' => false,
            'name' => 'tencongty',
            'vname' => 'LBL_TENCONGTY',
            'type' => 'varchar',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => ' ',
            'audited' => 1,
            'reportable' => 0,
            'len' => '255',
        ),

        'email' => array(
            'required' => false,
            'name' => 'email',
            'vname' => 'LBL_EMAIL',
            'type' => 'varchar',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => ' ',
            'audited' => 1,
            'reportable' => 0,
            'len' => '255',
        ),

        'tongtruocvat' => array(
            'required' => false,
            'source' => 'non-db',
            'name' => 'tongtruocvat',
            'vname' => 'LBL_TONGTRUOCVAT',
            'type' => 'varchar',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => ' ',
            'audited' => 0,
            'reportable' => 0,
            'quicksearch' => 'enabled',
            'studio' => 'visible',
        ),

        'tongvat' => array(
            'required' => false,
            'source' => 'non-db',
            'name' => 'tongvat',
            'vname' => 'LBL_TONGVAT',
            'type' => 'varchar',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => ' ',
            'audited' => 0,
            'reportable' => 0,
            'quicksearch' => 'enabled',
            'studio' => 'visible',
        ),
        
        'tongthuho' => array(
            'required' => false,
            'source' => 'non-db',
            'name' => 'tongthuho',
            'vname' => 'LBL_TONGTHUHO',
            'type' => 'varchar',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => ' ',
            'audited' => 0,
            'reportable' => 0,
            'quicksearch' => 'enabled',
            'studio' => 'visible',
        ),

        'tinhtrang' => array(
            'name'       => 'tinhtrang',
            'vname'      => 'LBL_TINHTRANG',
            'type'       => 'enum',
            'dbtype'     => 'char',
            'options'    => 'invoice_status_list',
            'len'        => 2,
            'default'    => '0', // Mới tạo
            'required'   => true,
            'importable' => true,
            'reportable' => false,
            'dependency' => false,
            'studio'     => 'visible',
            'audited'    => 1,
        ),

        'loaikh' => array(
            'name'       => 'loaikh',
            'vname'      => 'LBL_LOAIKH',
            'type'       => 'enum',
            'dbtype'     => 'char',
            'options'    => 'invoice_cus_type_list',
            'len'        => 2,
            'default'    => '1', // Cá nhân
            'required'   => true,
            'importable' => true,
            'reportable' => false,
            'dependency' => false,
            'studio'     => 'visible',
            'audited'    => 1,
        ),

        // Ký hóa đơn
        'is_signed' => array(
            'name'      => 'is_signed',
            'vname'     => 'LBL_IS_SIGNED',
            'type'      => 'bool',
            'len'       => 1,
            'default'   => 0,
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '',
            'audited' => 1,
            'reportable' => 0,
        ),

        // Dữ liệu hóa đơn
        'invoice_data' => array(
            'required'      => false,
            'name'          => 'invoice_data',
            'vname'         => 'LBL_INVOICE_DATA',
            'type'          => 'longtext',
            'massupdate'    => 0,
            'comments'      => 'JSON string stores invoice information on Winincoive system',
            'importable'    => true,
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '',
            'audited'       => 0,
            'reportable'    => false,
            'studio'        => 'visible',
            'default'       => ''
        ),

        // Đơn vị thuộc về
        'company_unit' => array(
            'required' => false,
            'name' => 'company_unit',
            'vname' => 'LBL_COMPANY_UNIT',
            'type' => 'enum',
            'options' => 'company_unit_invoice_list',
            'default' => 'MHV',
            'len' => '25',
            'massupdate' => 0,
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 1,
            'reportable' => 0,
        ),
    ),
    'indices' => array(
        array('name' => 'idx_hdb_name', 'type' => 'index', 'fields' => array('name')),
        array('name' => 'idx_hdb_assign', 'type' => 'index', 'fields' => array('assigned_user_id')),
        array('name' => 'idx_hdb_dt', 'type' => 'index', 'fields' => array('doituong_id')),
        array('name' => 'idx_hdb_lh', 'type' => 'index', 'fields' => array('lienhe')),
        array('name' => 'idx_hdb_shd', 'type' => 'index', 'fields' => array('sohoadon')),
    ),
    'relationships' => array (),
    'optimistic_locking' => true,
    'unified_search' => true,
);

if (!class_exists('VardefManager')) {
    require_once('include/SugarObjects/VardefManager.php');
}
VardefManager::createVardef('EC_HoaDonBan', 'EC_HoaDonBan', array('basic','assignable','security_groups'));
