<?php

$dictionary['EC_Input_Invoices'] = array(
    'table' => 'ec_input_invoices',
    'audited' => true,
    'inline_edit' => false,
    'duplicate_merge' => true,
    'fields' => array(
        'qty' => array(
            'required' => false,
            'name' => 'qty',
            'vname' => 'LBL_QTY',
            'type' => 'int',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 1,
            'reportable' => 0,
            'len' => '11',
            'disable_num_format' => '',
        ),

        'invoice_number' => array(
            'required' => false,
            'name' => 'invoice_number',
            'vname' => 'LBL_INVOICE_NUMBER',
            'type' => 'varchar',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 1,
            'reportable' => 0,
            'len' => '25',
        ),

        'invoice_serial' => array(
            'required' => false,
            'name' => 'invoice_serial',
            'vname' => 'LBL_INVOICE_SERIAL',
            'type' => 'varchar',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 1,
            'reportable' => 0,
            'len' => '25',
        ),

        'invoice_date' => array(
            'required' => false,
            'name' => 'invoice_date',
            'vname' => 'LBL_INVOICE_DATE',
            'type' => 'date',
            'massupdate' => 0,
            'comments' => 'Ngày hóa đơn vào',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 1,
            'reportable' => 0,
        ),

        'accounting_date' => array(
            'required' => false,
            'name' => 'accounting_date',
            'vname' => 'LBL_ACCOUNTING_DATE',
            'type' => 'date',
            'massupdate' => 0,
            'comments' => 'Ngày hạch toán',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 1,
            'reportable' => 0,
        ),

        // NCC
        'supplier' => array(
            'required' => false,
            'name' => 'supplier',
            'vname' => 'LBL_SUPPLIER',
            'type' => 'varchar',
            'len' => 25,
            'audited' => 1,
            'massupdate' => 0,
            'importable' => 1,
            'reportable' => 0,
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
        ),

        // Đơn vị
        'company_unit' => array(
            'required' => false,
            'name' => 'company_unit',
            'vname' => 'LBL_COMPANY_UNIT',
            'type' => 'varchar',
            'len' => 25,
            'default' => 'MHV',
            'audited' => 1,
            'massupdate' => 1,
            'importable' => 1,
            'reportable' => 0,
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
        ),
        
        // Hành trình
        'itinerary' => array(
            'required' => false,
            'name' => 'itinerary',
            'vname' => 'LBL_ITINERARY',
            'type' => 'varchar',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 1,
            'reportable' => 0,
            'len' => '255',
        ),

        // Giá vốn có VAT
        'cost' => array(
            'required' => false,
            'name' => 'cost',
            'vname' => 'LBL_COST',
            'type' => 'currency',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '',
            'audited' => 1,
            'reportable' => 0,
            'len' => 26,
        ),

        // Giá vốn chưa VAT
        'cost_no_vat' => array(
            'required' => false,
            'name' => 'cost_no_vat',
            'vname' => 'LBL_COST_NO_VAT',
            'type' => 'currency',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '',
            'audited' => 1,
            'reportable' => 0,
            'len' => 26,
        ),

        // Phần trăm VAT
        'vat_per' => array(
            'name' => 'vat_per',
            'vname' => 'LBL_VAT_PER',
            'required' => false,
            'type' => 'float',
            'len' => '6',
            'precision' => '2',
            'default' => 0.08,
            'massupdate' => 0,
            'importable' => 1,
            'audited' => 1,
            'reportable' => 0,
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '',
        ),

        // Tiền VAT giá vốn
        'vat' => array(
            'required' => false,
            'name' => 'vat',
            'vname' => 'LBL_VAT',
            'type' => 'currency',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '',
            'audited' => 1,
            'reportable' => 0,
            'len' => 26,
        ),

        'booking_id' => array(
            'name' => 'booking_id',
            'vname' => 'LBL_BOOKING_ID',
            'type' => 'id',
            'len' => 36,
            'required' => 0,
            'massupdate' => 0,
            'importable' => 1,
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => 0,
            'audited' => 0,
            'reportable' => 0,
        ),
        'booking' => array(
            'required' => false,
            'source' => 'non-db',
            'name' => 'booking',
            'vname' => 'LBL_BOOKING',
            'type' => 'relate',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '',
            'audited' => 1,
            'reportable' => 0,
            'len' => '255',
            'id_name' => 'booking_id',
            'ext2' => 'EC_Flight_Bookings',
            'module' => 'EC_Flight_Bookings',
            'rname' => 'name',
            'quicksearch' => 'enabled',
            'studio' => 'visible',
        ),

        // 0: chưa nạp, 1: đã nạp
        'status' => array(
            'required' => false,
            'name' => 'status',
            'vname' => 'LBL_STATUS',
            'type' => 'varchar',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 1,
            'reportable' => 0,
            'len' => 2,
        ),

        // Đánh dấu số vé là tính phí, để người dùng dò lại
        'is_other_fee' => array(
            'required' => false,
            'name' => 'is_other_fee',
            'vname' => 'LBL_IS_OTHER_FEE',
            'type' => 'bool',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 1,
            'reportable' => 0,
            'len' => 1,
        ),

        'order_by_no' => array(
            'required' => false,
            'name' => 'order_by_no',
            'vname' => 'LBL_ORDER_BY_NO',
            'type' => 'int',
            'massupdate' => 0,
            'comments' => 'STT số vé khi nạp hoá đơn',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 1,
            'reportable' => 0,
            'len' => '11',
            'disable_num_format' => '',
        ),

        'authorized_fee' => array(
            'name' => 'authorized_fee',
            'vname' => 'LBL_AUTHORIZED_FEE',
            'type' => 'currency',
            'len' => 26,
            'comments' => 'Phí thu hộ (Phí sân bay, admin)',
            'required' => 0,
            'reportable' => 0,
            'audited' => 1,
            'massupdate' => 0,
            'importable' => 1,
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '',
        ),

        'from_value' => array(
            'required' => false,
            'source' => 'non-db',
            'name' => 'from_value',
            'vname' => 'LBL_FROM_VALUE',
            'type' => 'varchar',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '',
            'audited' => 1,
            'reportable' => 0,
            'len' => '255',
            'quicksearch' => 'enabled',
            'studio' => 'visible',
        ),

        'to_value' => array(
            'required' => false,
            'source' => 'non-db',
            'name' => 'to_value',
            'vname' => 'LBL_TO_VALUE',
            'type' => 'varchar',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '',
            'audited' => 1,
            'reportable' => 0,
            'len' => '255',
            'quicksearch' => 'enabled',
            'studio' => 'visible',
        ),

        'left_qty' => array(
            'required' => false,
            'source' => 'non-db',
            'name' => 'left_qty',
            'vname' => 'LBL_LEFT_QTY',
            'type' => 'varchar',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '',
            'audited' => 1,
            'reportable' => 0,
            'len' => '16',
            'quicksearch' => 'enabled',
            'studio' => 'visible',
        ),

        // Tổng tiền
        'total' => array(
            'required' => false,
            'name' => 'total',
            'vname' => 'LBL_TOTAL',
            'type' => 'currency',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '',
            'audited' => 1,
            'reportable' => 0,
            'len' => 26,
        ),

        // Đánh dấu số vé đã xuất hết
        'out_of_stock' => array(
            'name' => 'out_of_stock',
            'vname' => 'LBL_OUT_OF_STOCK',
            'type' => 'bool',
            'len' => 1,
            'default' => 0,
            'required' => 0,
            'massupdate' => 0,
            'audited' => 1,
            'reportable' => 0,
            'importable' => 1,
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
        ),

        'ticket_code' => array(
            'name' => 'ticket_code',
            'vname' => 'LBL_TICKET_CODE',
            'type' => 'varchar',
            'len' => 25,
            'required' => 0,
            'audited' => 1,
            'massupdate' => 0,
            'comments' => 'Code vé dùng cho xuất hoá đơn BBA',
            'importable' => 1,
            'reportable' => 0,
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
        ),

        'ticket_type' => array(
            'name' => 'ticket_type',
            'vname' => 'LBL_TICKET_TYPE',
            'type' => 'enum',
            'options' => 'ticket_type_list',
            'len' => 16,
            'required' => 0,
            'comments' => 'Loại vé (Vé máy bay, vé hành lý, vé chỗ ngồi, phí xuất vé....)',
            'audited' => 1,
            'massupdate' => 1,
            'importable' => 1,
            'reportable' => 0,
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
        ),
    ),
    'indices' => array(
        array('name' => 'idx_ticket_number', 'type' => 'index', 'fields' => array('name')),
        array('name' => 'idx_booking', 'type' => 'index', 'fields' => array('booking_id')),
        array('name' => 'idx_invoice_number', 'type' => 'index', 'fields' => array('invoice_number')),
    ),
    'relationships' => array(),
    'optimistic_locking' => true,
    'unified_search' => true,
);
if (!class_exists('VardefManager')) {
    require_once('include/SugarObjects/VardefManager.php');
}
VardefManager::createVardef('EC_Input_Invoices', 'EC_Input_Invoices', array('basic', 'assignable', 'security_groups'));
