<?php

$dictionary['EC_Input_Invoices'] = array(
    'table' => 'ec_input_invoices',
    'audited' => true,
    'inline_edit' => true,
    'duplicate_merge' => true,
    'fields' => array(
        'qty' =>
        array(
            'required' => false,
            'name' => 'qty',
            'vname' => 'LBL_QTY',
            'type' => 'int',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 1,
            'reportable' => 0,
            'len' => '11',
            'disable_num_format' => '',
        ),
        'invoice_number' =>
        array(
            'required' => false,
            'name' => 'invoice_number',
            'vname' => 'LBL_INVOICE_NUMBER',
            'type' => 'varchar',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 1,
            'reportable' => 0,
            'len' => '25',
        ),
        'invoice_date' =>
        array(
            'required' => false,
            'name' => 'invoice_date',
            'vname' => 'LBL_INVOICE_DATE',
            'type' => 'date',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 1,
            'reportable' => 0,
        ),
        'invoice_serial' =>
        array(
            'required' => false,
            'name' => 'invoice_serial',
            'vname' => 'LBL_INVOICE_SERIAL',
            'type' => 'varchar',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 1,
            'reportable' => 0,
            'len' => '25',
        ),
        // NCC
        'supplier' =>
        array(
            'required' => false,
            'name' => 'supplier',
            'vname' => 'LBL_SUPPLIER',
            'type' => 'varchar',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 1,
            'reportable' => 0,
            'len' => '25',
        ),

        // Đơn vị
        'company_unit' => array(
            'required' => false,
            'name' => 'company_unit',
            'vname' => 'LBL_COMPANY_UNIT',
            'type' => 'varchar',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 1,
            'reportable' => 0,
            'len' => '25',
        ),
        
        // hành trình
        'itinerary' =>
        array(
            'required' => false,
            'name' => 'itinerary',
            'vname' => 'LBL_ITINERARY',
            'type' => 'varchar',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 1,
            'reportable' => 0,
            'len' => '255',
        ),
        // giá vốn
        'cost' =>
        array(
            'required' => false,
            'name' => 'cost',
            'vname' => 'LBL_COST',
            'type' => 'currency',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '',
            'audited' => 1,
            'reportable' => 0,
            'len' => 26,
        ),
        // giá chưa VAT
        'cost_no_vat' =>
        array(
            'required' => false,
            'name' => 'cost_no_vat',
            'vname' => 'LBL_COST_NO_VAT',
            'type' => 'currency',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '',
            'audited' => 1,
            'reportable' => 0,
            'len' => 26,
        ),
        // // % vat
        // 'vat_per' =>
        // array(
        //     'required' => false,
        //     'name' => 'vat_per',
        //     'vname' => 'LBL_VAT_PER',
        //     'type' => 'int',
        //     'massupdate' => 0,
        //     'comments' => '',
        //     'help' => '',
        //     'importable' => 'true',
        //     'duplicate_merge' => 'disabled',
        //     'duplicate_merge_dom_value' => '',
        //     'audited' => 1,
        //     'reportable' => 0,
        //     'len' => 2,
        // ),
        // tiền vat
        'vat' =>
        array(
            'required' => false,
            'name' => 'vat',
            'vname' => 'LBL_VAT',
            'type' => 'currency',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '',
            'audited' => 1,
            'reportable' => 0,
            'len' => 26,
        ),
        // booking chứa số vé
        'booking_id' =>
        array(
            'required' => false,
            'name' => 'booking_id',
            'vname' => '',
            'type' => 'id',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => 0,
            'audited' => 0,
            'reportable' => 0,
            'len' => 36,
        ),
        // booking id
        'booking' =>
        array(
            'required' => false,
            'source' => 'non-db',
            'name' => 'booking',
            'vname' => 'LBL_BOOKING',
            'type' => 'relate',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '',
            'audited' => 1,
            'reportable' => 0,
            'len' => '255',
            'id_name' => 'booking_id',
            'ext2' => 'EC_Flight_Bookings',
            'module' => 'EC_Flight_Bookings',
            'rname' => 'name',
            'quicksearch' => 'enabled',
            'studio' => 'visible',
        ),
        // 0: chưa nạp, 1: đã nạp
        'status' =>
        array(
            'required' => false,
            'name' => 'status',
            'vname' => 'LBL_STATUS',
            'type' => 'varchar',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 1,
            'reportable' => 0,
            'len' => 2,
        ),
        // đánh dấu số vé là tính phí, để người dùng dò lại
        'is_other_fee' =>
        array(
            'required' => false,
            'name' => 'is_other_fee',
            'vname' => 'LBL_IS_OTHER_FEE',
            'type' => 'bool',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 1,
            'reportable' => 0,
            'len' => 1,
        ),
        // stt số vé khi nạp hoá đơn
        'order_by_no' =>
        array(
            'required' => false,
            'name' => 'order_by_no',
            'vname' => 'LBL_ORDER_BY_NO',
            'type' => 'int',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 1,
            'reportable' => 0,
            'len' => '11',
            'disable_num_format' => '',
        ),
        // thu hộ
        'authorized_fee' =>
        array(
            'required' => false,
            'name' => 'authorized_fee',
            'vname' => 'LBL_AUTHORIZED_FEE',
            'type' => 'currency',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '',
            'audited' => 1,
            'reportable' => 0,
            'len' => 26,
        ),
        'from_value' =>
        array(
            'required' => false,
            'source' => 'non-db',
            'name' => 'from_value',
            'vname' => 'LBL_FROM_VALUE',
            'type' => 'varchar',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '',
            'audited' => 1,
            'reportable' => 0,
            'len' => '255',
            'quicksearch' => 'enabled',
            'studio' => 'visible',
        ),
        'to_value' =>
        array(
            'required' => false,
            'source' => 'non-db',
            'name' => 'to_value',
            'vname' => 'LBL_TO_VALUE',
            'type' => 'varchar',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '',
            'audited' => 1,
            'reportable' => 0,
            'len' => '255',
            'quicksearch' => 'enabled',
            'studio' => 'visible',
        ),
        'left_qty' =>
        array(
            'required' => false,
            'source' => 'non-db',
            'name' => 'left_qty',
            'vname' => 'LBL_LEFT_QTY',
            'type' => 'varchar',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '',
            'audited' => 1,
            'reportable' => 0,
            'len' => '255',
            'quicksearch' => 'enabled',
            'studio' => 'visible',
        ),
        // tổng tiền
        'total' =>
        array(
            'required' => false,
            'name' => 'total',
            'vname' => 'LBL_TOTAL',
            'type' => 'currency',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '',
            'audited' => 1,
            'reportable' => 0,
            'len' => 26,
        ),
        // đánh dấu số vé đã xuất hết
        'out_of_stock' =>
        array(
            'required' => false,
            'name' => 'out_of_stock',
            'vname' => 'LBL_OUT_OF_STOCK',
            'type' => 'bool',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 1,
            'reportable' => 0,
            'len' => 1,
        ),
        // code vé dùng cho xuất hoá đơn BBA
        'ticket_code' =>
        array(
            'required' => false,
            'name' => 'ticket_code',
            'vname' => 'LBL_TICKET_CODE',
            'type' => 'varchar',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 1,
            'reportable' => 0,
            'len' => '25',
        ),
        // ngày hạch toán
        'accounting_date' =>
        array(
            'required' => false,
            'name' => 'accounting_date',
            'vname' => 'LBL_ACCOUNTING_DATE',
            'type' => 'date',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => 1,
            'reportable' => 0,
        ),
    ),
    'relationships' => array(),
    'optimistic_locking' => true,
    'unified_search' => true,
);
if (!class_exists('VardefManager')) {
    require_once('include/SugarObjects/VardefManager.php');
}
VardefManager::createVardef('EC_Input_Invoices', 'EC_Input_Invoices', array('basic', 'assignable', 'security_groups'));
