<?php

$dictionary['EC_ChiTietHoanVe'] = array(
    'table' => 'ec_chitiethoanve',
    'audited' => true,
    'inline_edit' => true,
    'duplicate_merge' => true,
    'fields' =>  
    array(
    'loaihk' =>
    array(
      'required' => false,
      'name' => 'loaihk',
      'vname' => 'LBL_LOAIHK',
      'type' => 'enum',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '',
      'audited' => 1,
      'reportable' => 0,
      'len' => 1,
      'options' => 'passenger_type_list',
      'studio' => 'visible',
      'dependency' => false,
    ),
    'danhxung' =>
    array(
      'required' => false,
      'name' => 'danhxung',
      'vname' => 'LBL_DANHXUNG',
      'type' => 'enum',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '',
      'audited' => 1,
      'reportable' => 0,
      'len' => 1,
      'options' => 'passenger_salutation_list',
      'studio' => 'visible',
      'dependency' => false,
    ),
    'ngaysinh' =>
    array(
      'required' => false,
      'name' => 'ngaysinh',
      'vname' => 'LBL_NGAYSINH',
      'type' => 'date',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '',
      'audited' => 1,
      'reportable' => 0,
    ),
    'sove' =>
    array(
      'required' => false,
      'name' => 'sove',
      'vname' => 'LBL_SOVE',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '',
      'audited' => 1,
      'reportable' => 0,
      'len' => '25',
    ),
    'pnr' =>
    array(
      'required' => false,
      'name' => 'pnr',
      'vname' => 'LBL_PNR',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '',
      'audited' => 1,
      'reportable' => 0,
      'len' => '25',
    ),
    'chieubay' =>
    array(
      'required' => false,
      'name' => 'chieubay',
      'vname' => 'LBL_CHIEUBAY',
      'type' => 'enum',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '',
      'audited' => 1,
      'reportable' => 0,
      'len' => 1,
      'options' => 'bk_direction_list',
      'studio' => 'visible',
      'dependency' => false,
    ),
    'airline_code' =>
    array(
      'required' => false,
      'name' => 'airline_code',
      'vname' => 'LBL_AIRLINE_CODE',
      'type' => 'enum',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '',
      'audited' => 1,
      'reportable' => 0,
      'len' => 3,
      'options' => 'aircode_list',
      'studio' => 'visible',
      'dependency' => false,
    ),
    'noidi' =>
    array(
      'required' => false,
      'name' => 'noidi',
      'vname' => 'LBL_NOIDI',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '',
      'audited' => 1,
      'reportable' => 0,
      'len' => '3',
    ),
    'noiden' =>
    array(
      'required' => false,
      'name' => 'noiden',
      'vname' => 'LBL_NOIDEN',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '',
      'audited' => 1,
      'reportable' => 0,
      'len' => '3',
    ),
    'sotienhang' =>
    array(
      'required' => false,
      'name' => 'sotienhang',
      'vname' => 'LBL_SOTIENHANG',
      'type' => 'currency',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '',
      'audited' => 1,
      'reportable' => 0,
      'len' => 26,
    ),
    'sotienkhach' =>
    array(
      'required' => false,
      'name' => 'sotienkhach',
      'vname' => 'LBL_SOTIENKHACH',
      'type' => 'currency',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '',
      'audited' => 1,
      'reportable' => 0,
      'len' => 26,
    ),
    'phidichvu' =>
    array(
      'required' => false,
      'name' => 'phidichvu',
      'vname' => 'LBL_PHIDICHVU',
      'type' => 'currency',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '',
      'audited' => 1,
      'reportable' => 0,
      'len' => 26,
    ),
    'hoanve_id' =>
    array(
      'required' => false,
      'name' => 'hoanve_id',
      'vname' => '',
      'type' => 'id',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => 0,
      'audited' => 0,
      'reportable' => 0,
      'len' => 36,
    ),
    'hoanve' =>
    array(
      'required' => false,
      'source' => 'non-db',
      'name' => 'hoanve',
      'vname' => 'LBL_HOANVE',
      'type' => 'relate',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '',
      'audited' => 1,
      'reportable' => 0,
      'len' => '255',
      'id_name' => 'hoanve_id',
      'ext2' => 'EC_HoanVe',
      'module' => 'EC_HoanVe',
      'rname' => 'name',
      'quicksearch' => 'enabled',
      'studio' => 'visible',
    ),
    'nhacc_id' =>
    array(
      'required' => false,
      'name' => 'nhacc_id',
      'vname' => '',
      'type' => 'id',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => 0,
      'audited' => 0,
      'reportable' => 0,
      'len' => 36,
    ),
    'nhacc' =>
    array(
      'required' => false,
      'source' => 'non-db',
      'name' => 'nhacc',
      'vname' => 'LBL_NHACC',
      'type' => 'relate',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '',
      'audited' => 1,
      'reportable' => 0,
      'len' => '255',
      'id_name' => 'nhacc_id',
      'ext2' => 'Accounts',
      'module' => 'Accounts',
      'rname' => 'name',
      'quicksearch' => 'enabled',
      'studio' => 'visible',
    ),
    'dahoan' =>
    array(
      'required' => false,
      'name' => 'dahoan',
      'vname' => 'LBL_DAHOAN',
      'type' => 'bool',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => ' ',
      'audited' => 0,
      'reportable' => 0,
      'len' => '255',
      'default' => '1',
    ),
  ),
    'indices' =>
    array(
    0 => array('name' => 'idx_cthv_name', 'type' => 'index', 'fields' => array('name')),
    1 => array('name' => 'idx_cthv_del', 'type' => 'index', 'fields' => array('deleted')),
    2 => array('name' => 'idx_cthv_loaihk', 'type' => 'index', 'fields' => array('loaihk')),
    3 => array('name' => 'idx_cthv_cbay', 'type' => 'index', 'fields' => array('chieubay')),
    4 => array('name' => 'idx_cthv_ndi', 'type' => 'index', 'fields' => array('noidi')),
    5 => array('name' => 'idx_cthv_nden', 'type' => 'index', 'fields' => array('noiden')),
    6 => array('name' => 'idx_cthv_hv', 'type' => 'index', 'fields' => array('hoanve_id')),
    7 => array('name' => 'idx_cthv_ncc', 'type' => 'index', 'fields' => array('nhacc_id')),
    8 => array('name' => 'idx_cthv_dhoan', 'type' => 'index', 'fields' => array('dahoan')),
  ),
    'relationships' => array (
),
    'optimistic_locking' => true,
    'unified_search' => true,
);
if (!class_exists('VardefManager')) {
        require_once('include/SugarObjects/VardefManager.php');
}
VardefManager::createVardef('EC_ChiTietHoanVe', 'EC_ChiTietHoanVe', array('basic','assignable','security_groups'));
