<?php

$dictionary['EC_HoanVe'] = array(
    'table' => 'ec_hoanve',
    'audited' => true,
    'inline_edit' => true,
    'duplicate_merge' => true,
    'fields' =>  array(
        'ngaychungtu' =>
        array(
            'required' => '1',
            'name' => 'ngaychungtu',
            'vname' => 'LBL_NGAYCHUNGTU',
            'type' => 'date',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '',
            'audited' => 1,
            'reportable' => 0,
            'display_default' => 'now',
        ),
        'ngayhachtoan' =>
        array(
            'required' => '1',
            'name' => 'ngayhachtoan',
            'vname' => 'LBL_NGAYHACHTOAN',
            'type' => 'date',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '',
            'audited' => 1,
            'reportable' => 0,
            'display_default' => 'now',
        ),
        'booking_id' =>
        array(
            'required' => false,
            'name' => 'booking_id',
            'vname' => '',
            'type' => 'id',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => 0,
            'audited' => 0,
            'reportable' => 0,
            'len' => 36,
        ),
        'booking' =>
        array(
            'required' => '1',
            'source' => 'non-db',
            'name' => 'booking',
            'vname' => 'LBL_BOOKING',
            'type' => 'relate',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '',
            'audited' => 1,
            'reportable' => 0,
            'len' => '255',
            'id_name' => 'booking_id',
            'ext2' => 'EC_Flight_Bookings',
            'module' => 'EC_Flight_Bookings',
            'rname' => 'name',
            'quicksearch' => 'enabled',
            'studio' => 'visible',
        ),
        'tinhtrang' =>
        array(
            'required' => false,
            'name' => 'tinhtrang',
            'vname' => 'LBL_TINHTRANG',
            'type' => 'enum',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '',
            'audited' => 1,
            'reportable' => 0,
            'len' => 1,
            'options' => 'tinhtranghoanve_list',
            'studio' => 'visible',
            'dependency' => false,
            'default' => '2',
        ),
        'tongtienhang' =>
        array(
            'required' => false,
            'name' => 'tongtienhang',
            'vname' => 'LBL_TONGTIENHANG',
            'type' => 'currency',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '',
            'audited' => 1,
            'reportable' => 0,
            'len' => 26,
        ),
        'tongtienkhach' =>
        array(
            'required' => false,
            'name' => 'tongtienkhach',
            'vname' => 'LBL_TONGTIENKHACH',
            'type' => 'currency',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '',
            'audited' => 1,
            'reportable' => 0,
            'len' => 26,
        ),
        'tongtiendv' =>
        array(
            'required' => false,
            'name' => 'tongtiendv',
            'vname' => 'LBL_TONGTIENDV',
            'type' => 'currency',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '',
            'audited' => 1,
            'reportable' => 0,
            'len' => 26,
        ),
        'thongbao' =>
        array(
            'source' => 'non-db',
            'required' => false,
            'name' => 'thongbao',
            'vname' => 'LBL_THONGBAO',
            'type' => 'varchar',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => ' ',
            'audited' => 1,
            'reportable' => 0,
            'len' => '255',
        ),
    ),
    'indices' =>
    array(
        0 => array('name' => 'idx_hv_name', 'type' => 'index', 'fields' => array('name')),
        1 => array('name' => 'idx_hv_del', 'type' => 'index', 'fields' => array('deleted')),
        2 => array('name' => 'idx_hv_assign', 'type' => 'index', 'fields' => array('assigned_user_id')),
        3 => array('name' => 'idx_hv_bk', 'type' => 'index', 'fields' => array('booking_id')),
        4 => array('name' => 'idx_hv_tt', 'type' => 'index', 'fields' => array('tinhtrang')),
    ),
    'relationships' => array(),
    'optimistic_locking' => true,
    'unified_search' => true,
);
if (!class_exists('VardefManager')) {
    require_once('include/SugarObjects/VardefManager.php');
}
VardefManager::createVardef('EC_HoanVe', 'EC_HoanVe', array('basic', 'assignable', 'security_groups'));
