<?php


// THIS CONTENT IS GENERATED BY MBPackage.php
$manifest = array(
  0 =>
  array(
    'acceptable_sugar_versions' =>
    array(
      0 => '',
    ),
  ),
  1 =>
  array(
    'acceptable_sugar_flavors' =>
    array(
      0 => 'CE',
      1 => 'PRO',
      2 => 'ENT',
    ),
  ),
  'readme' => '',
  'key' => 'EC',
  'author' => 'DucPham',
  'description' => '',
  'icon' => '',
  'is_uninstallable' => true,
  'name' => 'Zalo_Contacts',
  'published_date' => '2025-10-29 02:28:28',
  'type' => 'module',
  'version' => 1761704909,
  'remove_tables' => 'prompt',
);
