name: SuiteCRM Prod CI/CD

on:
  workflow_run:
    workflows: ["SuiteCRM Dev CI/CD"]
    types:
      - completed
    branches: [ "dev" ]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
    - name: Debug
      run: echo "Workflow triggered!"

    - name: Deploy to Production via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.PROD_HOST }}     
        username: ${{ secrets.PROD_USER }} 
        key: ${{ secrets.PROD_SSH_KEY }}   
        script: |
          echo "=== Deploy hoàn tất! ==="
