name: SuiteCRM Production Deploy

on:
  workflow_run:
    workflows: ["SuiteCRM Dev CI/CD"]
    types:
      - completed
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to Production via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        script: |
          echo "=== Deploy hoàn tất! ==="